"use client";
import {useCallback,useEffect,useState} from "react";
import Link from "next/link";
import {useAdminAuth} from "@/contexts/AdminAuthContext";
import {adminFetch} from "@/services/adminApi";
import AdminHelp from "@/components/admin/AdminHelp";
type Rule={id:number;code:string;name:string;branch_id:number|null;minimum_completed_orders:number};
export default function VisitOffers(){
 const {authorization,hasPermission,profile}=useAdminAuth(),[rules,setRules]=useState<Rule[]>([]),[error,setError]=useState(""),[busy,setBusy]=useState<number|null>(null);
 const load=useCallback(async(signal?:AbortSignal)=>{if(!authorization||!hasPermission("REBATE_VIEW"))return;const result=await adminFetch("/api/admin/rebates/visit-rules",authorization,{signal});if(!result.ok)throw new Error("Could not load earned-visit offer rules.");const values=await result.json();if(!signal?.aborted){setRules(values);setError("");}},[authorization,hasPermission]);
 useEffect(()=>{const controller=new AbortController();void Promise.resolve().then(()=>load(controller.signal)).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[load]);
 async function save(rule:Rule,event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(!authorization||busy!==null)return;const values=new FormData(event.currentTarget),minimumCompletedOrders=Number(values.get("minimum")),reason=String(values.get("reason")??"").trim();setBusy(rule.id);setError("");try{const result=await adminFetch(`/api/admin/rebates/visit-rules/${rule.id}`,authorization,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({minimumCompletedOrders,reason}),signal:AbortSignal.timeout(15000)});if(!result.ok){const body=await result.json();throw new Error(body.message??"Could not save this offer rule.");}await load();}catch(e){setError(e instanceof Error?e.message:"Could not save.");}finally{setBusy(null);}}
 return <main className="mx-auto max-w-4xl p-4 sm:p-8"><Link href="/admin/notifications" className="inline-flex min-h-11 items-center text-sm underline">Offers</Link><div className="flex items-center gap-2"><h1 className="text-2xl font-bold text-[#143936]">Offers for earned visits</h1><AdminHelp title="Earned-visit eligibility" description="Give loyal customers a dedicated offer by setting the minimum number of completed paid visits. Paid orders awaiting collection do not count, and refunded orders do not count. All original offer dates, branch limits, minimum spend and exclusions still apply." guidance="0 keeps the offer open to everyone. Use 1 for grey First visit, 5 for blue Regular, or 20 for gold Gokul favourite; a custom minimum is also allowed. Create the offer in Offers first, then add its visit rule here with an audit reason. Customers must sign in to qualify. The best eligible saving remains automatic, and customers can choose another eligible offer at checkout. Only administrators can change global offers."/></div><p className="mt-3 text-sm">Reward recognition is earned from completed paid orders. Ticks describe visit milestones, not identity verification.</p>{error&&<p role="alert" className="mt-4 rounded-xl border p-3">{error}</p>}<button type="button" className="mt-3 min-h-11 rounded-xl border px-4" onClick={()=>void load().catch(e=>setError(e.message))}>Refresh rules</button><div className="mt-5 space-y-4">{rules.map(rule=><form key={`${rule.id}:${rule.minimum_completed_orders}`} onSubmit={event=>void save(rule,event)} className="rounded-2xl border bg-white p-4"><h2 className="font-bold">{rule.name} · {rule.code}</h2><p className="mt-1 text-sm">{rule.branch_id==null?"All branches":`Branch ${rule.branch_id}`} · current minimum {rule.minimum_completed_orders} completed visits</p><label className="mt-3 block text-sm">Minimum completed visits<input type="number" name="minimum" defaultValue={rule.minimum_completed_orders} min="0" max="100000" step="1" required className="mt-2 block min-h-11 w-full rounded-xl border p-3"/></label><label className="mt-3 block text-sm">Why are you changing this rule?<input name="reason" required maxLength={500} className="mt-2 block min-h-11 w-full rounded-xl border p-3"/></label>{hasPermission("REBATE_MANAGE")&&(rule.branch_id!=null||profile?.roleName==="OWNER_ADMIN")&&<button type="submit" disabled={busy!==null} className="mt-3 min-h-11 rounded-xl bg-[#143936] px-4 font-bold text-white disabled:opacity-50">{busy===rule.id?"Saving…":"Save eligibility"}</button>}</form>)}</div>{!rules.length&&!error&&<p className="mt-4">Create an offer first to configure its earned-visit eligibility.</p>}</main>;
}
