"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {useAdminAuth} from "@/contexts/AdminAuthContext";
import {apiClient} from "@/services/apiClient";
import {adminFetch} from "@/services/adminApi";
import {getAdminBranchMenu} from "@/services/adminMenuApi";
import {preferredAdminBranchId,rememberAdminBranchId} from "@/lib/adminBranchSelection";
import type {AdminBranchProduct} from "@/types/adminMenu";
type Rule={branchProductId:number;startsAt:string|null;endsAt:string|null;weekdays:number;soldOut:boolean;requiresBranchProductId:number|null};
type Settings={enabled:boolean;revision:number;items:Rule[]};
const initial=(id:number):Rule=>({branchProductId:id,startsAt:null,endsAt:null,weekdays:127,soldOut:false,requiresBranchProductId:null});
const input="mt-1 min-h-11 w-full rounded-xl border bg-white px-3";
export default function MenuServiceHoursPage(){
 const {profile,authorization,hasPermission}=useAdminAuth(),allowed=hasPermission("MENU_MANAGE");
 const [branches,setBranches]=useState<{id:number;name:string}[]>([]),[branchId,setBranchId]=useState<number|null>(null);
 const [settings,setSettings]=useState<Settings|null>(null),[products,setProducts]=useState<AdminBranchProduct[]>([]);
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState(""),[reload,setReload]=useState(0);
 const [category,setCategory]=useState<number|null>(null),[start,setStart]=useState("11:00"),[end,setEnd]=useState("21:30");
 useEffect(()=>{if(!profile||!allowed)return;const controller=new AbortController();void apiClient<{id:number;name:string;active:boolean}[]>("/api/branches",{signal:controller.signal}).then(all=>{const values=all.filter(b=>b.active&&(profile.roleName==="OWNER_ADMIN"||profile.branchIds.includes(b.id)));setBranches(values);setBranchId(preferredAdminBranchId(profile.staffId,values));}).catch(()=>{if(!controller.signal.aborted)setError("Unable to load branches.");});return()=>controller.abort();},[profile,allowed]);
 useEffect(()=>{if(!branchId||!authorization||!allowed)return;const controller=new AbortController();
  void(async()=>{try{const response=await adminFetch(`/api/admin/branches/${branchId}/menu-service-windows`,authorization,{signal:controller.signal});if(!response.ok)throw Error("Unable to load service hours.");const saved:Settings=await response.json();const menu=await getAdminBranchMenu(branchId,authorization,controller.signal);if(!controller.signal.aborted){setSettings(saved);setProducts(menu);}}catch(reason){if(!controller.signal.aborted)setError(reason instanceof Error?reason.message:"Unable to load service hours.");}})();return()=>controller.abort();
 },[branchId,authorization,allowed,reload]);
 function update(rule:Rule){setSettings(current=>current?{...current,items:[...current.items.filter(i=>i.branchProductId!==rule.branchProductId),rule]}:current);}
 async function save(){if(!settings||!branchId||!authorization)return;setBusy(true);setError("");setNotice("");try{const response=await adminFetch(`/api/admin/branches/${branchId}/menu-service-windows`,authorization,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(settings)});if(!response.ok){const value=await response.json().catch(()=>null);throw Error(response.status===409?"Another staff member changed these rules. Reload before saving.":value?.message??"Could not save service hours.");}setSettings(await response.json());setNotice("Saved. New orders use these IST rules; existing orders stay unchanged.");}catch(reason){setError(reason instanceof Error?reason.message:"Could not save service hours.");}finally{setBusy(false);}}
 if(!profile)return null;if(!allowed)return <p className="p-6">Menu-management permission is required.</p>;
 return <main className="mx-auto max-w-6xl p-4 sm:p-8"><h1 className="text-2xl font-bold text-[#143936]">Menu service hours</h1><p className="mt-3 text-sm leading-6">Choose when customers may place new orders, in IST. Opening is inclusive and closing is exclusive. Overnight hours use the opening day. Sold-out items and their dependent dishes are blocked. Existing stock and pickup protections still apply.</p>
 <label className="my-5 block max-w-md text-sm font-semibold">Branch<select className={input} disabled={busy} value={branchId??""} onChange={e=>{const id=Number(e.target.value);setSettings(null);setProducts([]);setError("");setNotice("");setBranchId(id);rememberAdminBranchId(profile.staffId,id);}}>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>
 {error&&<p role="alert" className="my-4 rounded-xl border border-red-300 p-4 text-red-800">{error}</p>}{notice&&<p role="status" className="my-4 rounded-xl bg-green-50 p-4">{notice}</p>}
 <button type="button" disabled={busy} className="min-h-11 rounded-xl border px-4" onClick={()=>{setSettings(null);setError("");setReload(v=>v+1);}}>Reload saved rules</button>
 {settings&&<><fieldset disabled={busy} className="my-5"><label className="flex min-h-11 items-center gap-3 rounded-xl bg-[#fffaf2] p-4 font-bold"><input type="checkbox" checked={settings.enabled} onChange={e=>setSettings({...settings,enabled:e.target.checked})}/>Enforce service hours and sold-out rules for this branch</label>
 <section className="my-5 rounded-2xl border bg-white p-4"><h2 className="font-bold">Set hours for a category</h2><p className="mt-2 text-sm">Applies to the category’s current items. Item weekdays, sold-out status and dependencies are retained. Category hours replace the current items’ hours.</p><div className="mt-3 grid gap-3 sm:grid-cols-3"><label className="text-sm">Category<select className={input} value={category??""} onChange={e=>setCategory(Number(e.target.value)||null)}><option value="">Choose category</option>{Array.from(new Map(products.map(p=>[p.categoryId,p.categoryName])).entries()).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label className="text-sm">Opens (IST)<input className={input} type="time" value={start} onChange={e=>setStart(e.target.value)}/></label><label className="text-sm">Closes (IST)<input className={input} type="time" value={end} onChange={e=>setEnd(e.target.value)}/></label></div><button type="button" disabled={!category||!start||!end||start===end} className="mt-3 min-h-11 rounded-xl border px-4" onClick={()=>setSettings(current=>current?{...current,items:products.reduce((rules,p)=>p.categoryId===category?[...rules.filter(i=>i.branchProductId!==p.branchProductId),{...(rules.find(i=>i.branchProductId===p.branchProductId)??initial(p.branchProductId)),startsAt:start,endsAt:end}]:rules,current.items)}:current)}>Apply category hours to draft</button></section>
 <div className="grid gap-4 lg:grid-cols-2">{products.map(p=>{const rule=settings.items.find(i=>i.branchProductId===p.branchProductId)??initial(p.branchProductId);return <section key={p.branchProductId} className="rounded-2xl border bg-white p-4"><h2 className="font-bold">{p.productName}</h2><p className="text-xs text-slate-600">{p.categoryName}{!p.available?" · Marked unavailable in live menu":""}</p><div className="mt-3 grid grid-cols-2 gap-3"><label className="text-sm">Opens (IST)<input className={input} type="time" value={rule.startsAt?.slice(0,5)??""} onChange={e=>update({...rule,startsAt:e.target.value||null})}/></label><label className="text-sm">Closes (IST)<input className={input} type="time" value={rule.endsAt?.slice(0,5)??""} onChange={e=>update({...rule,endsAt:e.target.value||null})}/></label></div><button type="button" className="mt-2 min-h-11 text-sm underline" onClick={()=>update({...rule,startsAt:null,endsAt:null})}>Clear daily hours</button><div className="my-3 flex flex-wrap gap-2" aria-label={`${p.productName} weekdays`}>{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map((day,index)=><label key={day} className="flex min-h-11 items-center gap-1 rounded-lg border px-2 text-xs"><input type="checkbox" checked={!!(rule.weekdays&(1<<index))} onChange={e=>update({...rule,weekdays:e.target.checked?rule.weekdays|(1<<index):rule.weekdays&~(1<<index)})}/>{day}</label>)}</div><label className="flex min-h-11 items-center gap-2 font-semibold"><input type="checkbox" checked={rule.soldOut} onChange={e=>update({...rule,soldOut:e.target.checked})}/>Sold out until cleared</label><label className="mt-3 block text-sm">Requires an available item<select className={input} value={rule.requiresBranchProductId??""} onChange={e=>update({...rule,requiresBranchProductId:Number(e.target.value)||null})}><option value="">No dependency</option>{products.filter(q=>q.branchProductId!==p.branchProductId).map(q=><option key={q.branchProductId} value={q.branchProductId}>{q.productName}</option>)}</select></label></section>;})}</div></fieldset>
 <button type="button" disabled={busy} onClick={()=>void save()} className="min-h-12 rounded-xl bg-[#143936] px-6 font-bold text-white">{busy?"Saving…":"Save branch service rules"}</button><Link className="ml-4 inline-block py-3 underline" href="/admin/menu/live">Live menu and stock controls</Link></>}
 </main>;
}
