"use client";
import "./reward-controls.css";
import {useEffect,useRef,useState} from 'react';
import type {AvailableRebateResponse} from '@/types/rebate';
import {T} from '@/lib/language';
export default function OfferChoiceDialog({offers,selected,onApply,onClose}:{offers:AvailableRebateResponse[];selected:string|null;onApply:(code:string)=>Promise<void>;onClose:()=>void}){
 const dialog=useRef<HTMLDialogElement>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[code,setCode]=useState('');
 useEffect(()=>{const value=dialog.current;value?.showModal();return()=>value?.close();},[]);
 async function apply(code:string){setBusy(true);setError('');try{await onApply(code);onClose();}catch(failure){setError(failure instanceof Error?failure.message:'This offer could not be verified. Try again.');}finally{setBusy(false);}}
 return <dialog ref={dialog} className="checkout-offer-dialog" aria-labelledby="offer-choice-title" onCancel={e=>{e.preventDefault();if(!busy)onClose();}} onClick={e=>{if(e.target===e.currentTarget&&!busy)onClose();}}><div><header><h2 id="offer-choice-title"><T text="Choose an offer" /></h2><button type="button" disabled={busy} onClick={onClose}><T text="Close" /> ×</button></header><p><T text="One offer per order. Rewards apply first; fees are excluded." /></p><div className="checkout-offer-list">{offers.length?offers.map(offer=><article key={offer.code}><div><strong>{offer.name}</strong><small>{offer.code}</small>{offer.description&&<p>{offer.description}</p>}<span><T text="Save" /> ₹{Number(offer.rebateAmount).toFixed(2)}</span></div><button type="button" disabled={busy||offer.code===selected} onClick={()=>void apply(offer.code)}><T text={offer.code===selected?'Applied':'Apply'} /></button></article>):<p><T text="No offers qualify for this order." /></p>}</div><form onSubmit={e=>{e.preventDefault();if(code.trim()&&!busy)void apply(code.trim().toUpperCase());}} className="mt-4 flex gap-2"><label className="min-w-0 flex-1"><T text="Have an offer code?" /><input className="mt-2 w-full rounded-xl border p-3" value={code} maxLength={100} disabled={busy} onChange={e=>setCode(e.target.value)} autoCapitalize="characters" /></label><button type="submit" disabled={busy||!code.trim()}><T text="Apply" /></button></form>{busy&&<p role="status"><T text="Verifying this offer…" /></p>}{error&&<p role="alert">{error}</p>}</div></dialog>;
}
