"use client";
import {T,useTranslation} from "@/lib/language";
import {useEffect,useRef,useState} from "react";
import {useRouter} from "next/navigation";
/** Intercept deliberate storefront navigation while money/reservations are unresolved. */
export default function PaymentLeaveChoice({active,busy,error,onCancel}:{active:boolean;busy:boolean;error?:string|null;onCancel:()=>Promise<void>}) {
    const translate = useTranslation();
 const router=useRouter();const allowed=useRef(false);const [destination,setDestination]=useState<string|null>(null);
 useEffect(()=>{if(!active)return;const click=(event:MouseEvent)=>{const link=(event.target as Element)?.closest?.("a[href]") as HTMLAnchorElement|null;if(!link||allowed.current||event.defaultPrevented||event.button!==0||event.metaKey||event.ctrlKey||event.shiftKey||link.target==="_blank")return;const target=new URL(link.href);if(target.origin!==location.origin||target.pathname===location.pathname)return;event.preventDefault();event.stopImmediatePropagation();setDestination(target.pathname+target.search+target.hash);};document.addEventListener("click",click,true);return()=>{document.removeEventListener("click",click,true);};},[active]);
 if(!active||!destination)return null;
 return <div role="dialog" aria-modal="true" aria-labelledby="leave-payment-title" className="fixed inset-0 z-[100] flex items-center justify-center bg-black/40 p-4" onKeyDown={e=>{if(e.key==="Escape"&&!busy)setDestination(null);if(e.key==="Tab"){const buttons=Array.from(e.currentTarget.querySelectorAll<HTMLButtonElement>("button:not(:disabled)"));const first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}}><section className="w-full max-w-md rounded-2xl bg-[#fffaf2] p-6 text-[#173c39]"><h2 id="leave-payment-title" className="text-xl font-bold"><T text="Before you leave payment" /></h2><p className="mt-3 text-sm leading-6"><T text="Keep this order to pay later, or check payment and cancel the unpaid reservation now. Your cart stays saved. A confirmed payment will preserve the order." /></p>{error&&<p role="alert" className="mt-3 rounded-xl border border-red-300 p-3 text-sm">{translate(error)} <T text="Your reservation is unchanged if provider verification failed. You can retry the check or stay on payment." /></p>}<div className="mt-4 grid gap-3"><button autoFocus type="button" disabled={busy} className="min-h-11 rounded-xl bg-[#173c39] px-4 font-bold text-white" onClick={()=>setDestination(null)}><T text="Stay & retry payment" /></button><button type="button" disabled={busy} className="min-h-11 rounded-xl border px-4 font-bold" onClick={()=>{allowed.current=true;router.push(destination);}}><T text="Leave & keep order for later" /></button><button type="button" disabled={busy} className="min-h-11 rounded-xl border px-4 font-bold" onClick={()=>void onCancel()}>{busy?"Checking provider…":translate("Cancel order & keep cart")}</button></div></section></div>;
}
