"use client";
import {menuFamily,menuShortcuts} from "@/lib/menuPresentation";
import Image from "next/image";
import {useState} from "react";
import MenuDiscoverySheet from "./MenuDiscoverySheet";
import {T} from "@/lib/language";
import type {MenuCategory} from "@/types/menu";
export default function MobileMenuFilters({categories,selected,onCategories,maximum,onMaximum,portions,onPortions,onResetSearch,offersAvailable=false,onBrowse,activeId,showChips=true}:{categories:MenuCategory[];selected:number[];onCategories:(ids:number[])=>void;maximum:number|null;onMaximum:(n:number|null)=>void;portions:boolean;onPortions:(b:boolean)=>void;onResetSearch:()=>void;offersAvailable?:boolean;onBrowse?:(id:number|null)=>void;activeId?:number;showChips?:boolean}){
 const [open,setOpen]=useState(false);
 const [failed,setFailed]=useState<string[]>([]);
 const activeFamily=menuFamily(categories.find(c=>c.id===activeId)?.name??"");
 function browse(id:number){if(onBrowse){onCategories([]);onMaximum(null);onPortions(false);onBrowse(id);onResetSearch();return;}if(selected.length)onCategories([]);if(maximum!==null)onMaximum(null);if(portions)onPortions(false);onResetSearch();requestAnimationFrame(()=>{const section=document.getElementById(`menu-category-${id}`);const disclosure=section?.querySelector("details");if(disclosure)disclosure.open=true;section?.scrollIntoView({block:"start",behavior:matchMedia("(prefers-reduced-motion: reduce)").matches?"instant":"smooth"});});}
 return <>
  <nav className="menu-illustrated-categories" aria-label="Item categories">{menuShortcuts(categories).map((c,index)=>{const photo=(c.name==="Snacks"?c.products.find(p=>p.available&&p.imageUrl&&/snack|namkeen/i.test(p.categoryName)):undefined)??c.products.find(p=>p.available&&p.imageUrl)??c.products.find(p=>p.imageUrl);return <button type="button" key={c.id} onClick={()=>browse(c.id)} data-menu-family={c.name} className={`menu-category-tile menu-category-tone-${index%4}`} aria-current={activeFamily===c.name?true:undefined} aria-label={`Browse ${c.name}`}><span>{photo?.imageUrl&&!failed.includes(photo.imageUrl)?<Image src={photo.imageUrl} alt="" fill sizes="68px" onError={()=>setFailed(value=>[...value,photo.imageUrl!])}/>:<span aria-hidden="true">{c.name.slice(0,1)}</span>}</span><strong>{c.name}</strong></button>;})}</nav>
  {showChips&&<div className="menu-browse-chips"><button type="button" aria-pressed={activeId===undefined&&!selected.length&&maximum===null&&!portions} onClick={()=>{onBrowse?.(null);onCategories([]);onMaximum(null);onPortions(false);onResetSearch();}}><T text="All"/></button><button type="button" aria-label="Browse all item categories" aria-haspopup="dialog" onClick={()=>setOpen(true)}><svg aria-hidden="true" viewBox="0 0 24 24" width="17" height="17" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M3 6h18M3 12h18M3 18h18M8 3v6m8 0v6m-8 0v6"/></svg><T text="Filters"/></button>{offersAvailable&&<button type="button" onClick={()=>document.getElementById("menu-offers-open")?.click()}><span aria-hidden="true">◇</span><T text="Offers"/></button>}</div>}
  {open&&<MenuDiscoverySheet title="Filter menu" onClose={()=>setOpen(false)}><fieldset className="menu-filter-options"><legend><T text="Categories"/></legend>{categories.map(c=><label key={c.id}><input type="checkbox" checked={selected.includes(c.id)} onChange={e=>onCategories(e.target.checked?[...selected,c.id]:selected.filter(id=>id!==c.id))}/>{c.name}<small>{c.products.length}</small></label>)}</fieldset><label className="menu-filter-price"><T text="Maximum price"/><input type="number" min="0" value={maximum??""} placeholder="No limit" onChange={e=>onMaximum(e.target.value===""?null:Math.max(0,Number(e.target.value)))}/></label><label className="menu-filter-variants"><input type="checkbox" checked={portions} onChange={e=>onPortions(e.target.checked)}/><T text="Items with size or portion choices"/></label><button className="menu-filter-done" type="button" onClick={()=>setOpen(false)}><T text="Show items"/></button></MenuDiscoverySheet>}
 </>;
}
