"use client";
import {useEffect,useRef} from "react";
import {T} from "@/lib/language";
import type {MenuCategory} from '@/types/menu';
export default function MobileMenuFilters({categories,selected,onCategories,maximum,onMaximum,portions,onPortions}:{categories:MenuCategory[];selected:number[];onCategories:(ids:number[])=>void;maximum:number|null;onMaximum:(n:number|null)=>void;portions:boolean;onPortions:(b:boolean)=>void}){
 const picker=useRef<HTMLDetailsElement>(null);
 useEffect(()=>{const close=(e:Event)=>{if(picker.current&&!picker.current.contains(e.target as Node))picker.current.open=false;};const escape=(e:KeyboardEvent)=>{if(e.key==="Escape"&&picker.current?.open){picker.current.open=false;picker.current.querySelector('summary')?.focus();}};document.addEventListener('click',close);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('click',close);document.removeEventListener('keydown',escape);};},[]);
 const count=selected.length+Number(maximum!==null)+Number(portions);
 return <><details ref={picker} className="mobile-items-picker"><summary aria-label="Browse all item categories"><span aria-hidden="true">▤</span><T text="Items"/></summary><nav aria-label="Item categories"><button type="button" onClick={()=>{onCategories([]);onMaximum(null);onPortions(false);if(picker.current)picker.current.open=false;document.querySelector('.mobile-menu-filters')?.scrollIntoView({block:'start'});}}><T text="All items"/><span>{categories.reduce((n,c)=>n+c.products.length,0)}</span></button>{categories.map(c=><button type="button" key={c.id} onClick={()=>{onCategories([c.id]);onMaximum(null);onPortions(false);if(picker.current)picker.current.open=false;document.querySelector('.mobile-menu-filters')?.scrollIntoView({block:'start'});}}>{c.name}<span>{c.products.length}</span></button>)}</nav></details><div className="mobile-menu-filters"><details><summary><svg aria-hidden="true" viewBox="0 0 24 24" width="18" height="18" fill="none" stroke="currentColor" strokeWidth="1.8"><path d="M3 6h18M3 12h18M3 18h18"/><circle cx="8" cy="6" r="2" fill="white"/><circle cx="16" cy="12" r="2" fill="white"/><circle cx="10" cy="18" r="2" fill="white"/></svg><T text="Filters"/>{count?` (${count})`:''}</summary><div className="mobile-filter-options"><fieldset><legend><T text="Categories"/></legend>{categories.map(c=><label key={c.id}><input type="checkbox" checked={selected.includes(c.id)} onChange={()=>onCategories(selected.includes(c.id)?selected.filter(id=>id!==c.id):[...selected,c.id])}/>{c.name}</label>)}</fieldset><label><T text="Price up to"/><select value={maximum??''} onChange={e=>onMaximum(e.target.value?Number(e.target.value):null)}><option value=""><T text="Any price"/></option>{[100,200,300,500].map(p=><option key={p} value={p}>₹{p}</option>)}</select></label><label><input type="checkbox" checked={portions} onChange={e=>onPortions(e.target.checked)}/><T text="Portion choices"/></label><button type="button" onClick={()=>{onCategories([]);onMaximum(null);onPortions(false);}}><T text="Clear filters"/></button></div></details><div className="mobile-filter-chips">{categories.map(c=><button key={c.id} type="button" aria-pressed={selected.includes(c.id)} onClick={()=>onCategories(selected.includes(c.id)?selected.filter(id=>id!==c.id):[...selected,c.id])}>{c.name}</button>)}</div></div></>;
}
