"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {apiClient,ApiError} from "@/services/apiClient";
import {formatOrderCurrency as money} from "@/lib/orderTracking";
import {T} from "@/lib/language";
export type CorrectionSummary={orderNumber:string;branchName:string;serverTime:string;cancellationDeadline:string|null;canCancel:boolean;canTransfer:boolean;refundAmount:number;retainedCharges:number;refundStatus:string;explanation:string};
type Cancellation={requestKey:string;reason:string;acceptedRefundAmount:number;acceptedRetainedCharges:number};
export default function OrderCancellation({orderNumber,onChanged}:{orderNumber:string;onChanged:()=>void}){
 const [summary,setSummary]=useState<CorrectionSummary|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[open,setOpen]=useState(false),[remaining,setRemaining]=useState(0);
 const [reason,setReason]=useState("Selected the wrong pickup branch"),[retry,setRetry]=useState<Cancellation|null>(null);
 const dialog=useRef<HTMLDialogElement>(null),deadline=useRef(0),locked=useRef(false);
 const path=`/api/customer/identity/orders/${encodeURIComponent(orderNumber)}`,key=`gokul-cancel:${orderNumber}`;
 const load=useCallback(async(signal?:AbortSignal)=>{const value=await apiClient<CorrectionSummary>(`${path}/correction`,{credentials:"include",signal});if(signal?.aborted)return;if(!value||typeof value.canCancel!=="boolean"||typeof value.refundStatus!=="string"||!Number.isFinite(Number(value.refundAmount))||!Number.isFinite(Number(value.retainedCharges))||!Number.isFinite(Date.parse(value.serverTime)))throw new Error("Cancellation details are unavailable. Contact the branch or retry.");deadline.current=performance.now()+Math.max(0,Date.parse(value.cancellationDeadline??value.serverTime)-Date.parse(value.serverTime));setRemaining(Math.ceil((deadline.current-performance.now())/1000));setSummary(value);},[path]);
 useEffect(()=>{const controller=new AbortController();void Promise.resolve().then(()=>{const saved=sessionStorage.getItem(key);if(saved){const value=JSON.parse(saved) as Cancellation;if(typeof value.requestKey==="string"&&typeof value.reason==="string"&&Number.isFinite(value.acceptedRefundAmount)&&Number.isFinite(value.acceptedRetainedCharges))setRetry(value);}return load(controller.signal);}).catch(()=>{if(!controller.signal.aborted)setError("Cancellation details could not load. Retry or contact the branch.");});return()=>controller.abort();},[load,key]);
 useEffect(()=>{const timer=setInterval(()=>setRemaining(Math.max(0,Math.ceil((deadline.current-performance.now())/1000))),1000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{if(open)dialog.current?.showModal();else dialog.current?.close();},[open]);
 async function review(){setBusy(true);setError("");try{const saved=sessionStorage.getItem(key);if(saved){const value=JSON.parse(saved) as Cancellation;if(typeof value.requestKey!=="string"||typeof value.reason!=="string"||!Number.isFinite(value.acceptedRefundAmount)||!Number.isFinite(value.acceptedRetainedCharges))throw new Error("Invalid cancellation recovery. Contact the branch.");setRetry(value);setReason(value.reason);}else{setRetry(null);await load(AbortSignal.timeout(10000));}setOpen(true);}catch(e){setError(e instanceof Error?e.message:"Could not review cancellation.");}finally{setBusy(false);}}
 async function cancel(){if(locked.current||!summary)return;locked.current=true;setBusy(true);setError("");try{const input=retry??{requestKey:crypto.randomUUID(),reason,acceptedRefundAmount:summary.refundAmount,acceptedRetainedCharges:summary.retainedCharges};sessionStorage.setItem(key,JSON.stringify(input));setRetry(input);const value=await apiClient<CorrectionSummary>(`${path}/cancel`,{method:"POST",credentials:"include",body:JSON.stringify(input),signal:AbortSignal.timeout(20000)});sessionStorage.removeItem(key);setRetry(null);setSummary(value);setOpen(false);onChanged();}catch(e){if(e instanceof ApiError&&[400,409].includes(e.status)){sessionStorage.removeItem(key);setRetry(null);void load().catch(()=>{});}setError(e instanceof Error?e.message:"The result is unconfirmed. Retry this same cancellation safely.");}finally{locked.current=false;setBusy(false);}}
 const requested=summary&&summary.refundStatus!=="NOT_REQUESTED";
 return <section className="mobile-order-cancellation" aria-label="Cancellation and refund">
  <h2><T text="Booked the wrong order?"/></h2>
  {requested?<><strong>{summary.refundStatus==="REFUNDED"?"Food refund confirmed":summary.refundStatus==="NO_REFUND_DUE"?"Cancelled · no food refund due":summary.refundStatus==="REFUND_FAILED"?"Refund needs staff attention":"Food refund requested"}</strong><p>{money(summary.refundAmount)} food refund · {money(summary.retainedCharges)} additional charges retained.</p><p>Bank credit timing depends on your payment provider. Contact the branch if you need help.</p><button type="button" disabled={busy} onClick={()=>void load().catch(()=>setError("Could not refresh refund status."))}>Refresh refund status</button></>:<><p>Cancel within 10 minutes of payment confirmation, including during preparation. Only the food amount is refunded; additional charges and their taxes are retained. Collected or dispatched orders cannot be cancelled.</p>{summary?.canCancel&&remaining>0&&<p role="status">{Math.floor(remaining/60)}m {remaining%60}s left to decide</p>}<button type="button" disabled={busy||(!retry&&!!summary&&(!summary.canCancel||remaining<=0))} onClick={()=>void review()}>{busy?"Checking…":"Review cancellation"}</button></>}
  {error&&!open&&<p role="alert">{error}</p>}
  {open&&<dialog ref={dialog} className="mobile-correction-dialog" aria-labelledby="cancel-review-title" onCancel={event=>{if(busy)event.preventDefault();else setOpen(false);}} onClick={event=>{if(event.target===event.currentTarget&&!busy){const bounds=event.currentTarget.getBoundingClientRect();if(event.clientX<bounds.left||event.clientX>bounds.right||event.clientY<bounds.top||event.clientY>bounds.bottom)setOpen(false);}}}>
   <button type="button" className="correction-close" disabled={busy} onClick={()=>setOpen(false)}>Close</button><h2 id="cancel-review-title">Cancel this order?</h2><p>Order from {summary?.branchName}</p><dl><div><dt>Food refund</dt><dd>{money(retry?.acceptedRefundAmount??summary?.refundAmount??0)}</dd></div><div><dt>Charges retained</dt><dd>{money(retry?.acceptedRetainedCharges??summary?.retainedCharges??0)}</dd></div></dl><p>Convenience, payment processing, priority and delivery charges, including their taxes, are not refunded. The refund remains pending until the provider confirms it.</p>
   <label>Cancellation reason<select disabled={busy||!!retry} value={reason} onChange={event=>setReason(event.target.value)}><option>Selected the wrong pickup branch</option><option>Ordered the wrong items</option><option>Plans changed</option></select></label>{error&&<p role="alert">{error}</p>}{retry&&<p>Retry uses the same recorded request to avoid duplicate refunds.</p>}
   <div className="correction-actions"><button type="button" autoFocus disabled={busy} onClick={()=>setOpen(false)}>Keep my order</button><button type="button" disabled={busy||(!retry&&(!summary?.canCancel||remaining<=0))} onClick={()=>void cancel()}>{busy?"Requesting refund…":retry?"Retry cancellation":"Cancel & request food refund"}</button></div>
  </dialog>}
 </section>;
}
