"use client";
import {T} from "@/lib/language";

import Link from "next/link";
import {useEffect, useState, type FormEvent} from "react";
import AppShell from "@/components/layout/AppShell";
import {apiClient} from "@/services/apiClient";
import {getActiveBranches} from "@/services/branchApi";
import type {Branch} from "@/types/branch";
import type {CareerJob} from "@/types/brandCareers";
import styles from "@/components/brand/Workspace.module.css";
export default function CareersPage() {
    const [jobs,setJobs]=useState<CareerJob[]>([]),[branches,setBranches]=useState<Branch[]>([]);
    const [loading,setLoading]=useState(true),[error,setError]=useState(""),[revision,setRevision]=useState(0);
    const [job,setJob]=useState<CareerJob|null>(null),[branch,setBranch]=useState(""),[busy,setBusy]=useState(false),[receipt,setReceipt]=useState("");
    const [requestId,setRequestId]=useState("");
    useEffect(()=>{const controller=new AbortController();Promise.all([apiClient<CareerJob[]>("/api/storefront/careers",{signal:controller.signal}),getActiveBranches(controller.signal)]).then(([j,b])=>{setJobs(j);setBranches(b);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[revision]);
    async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=new FormData(e.currentTarget);setBusy(true);setError("");const id=requestId||crypto.randomUUID();setRequestId(id);
        try{const result=await apiClient<{reference:string;message:string}>("/api/storefront/careers/applications",{method:"POST",body:JSON.stringify({requestId:id,jobId:job?.id??null,branchId:Number(branch),name:form.get("name"),phone:form.get("phone"),email:form.get("email"),desiredRole:job?.title??form.get("desiredRole"),experience:Number(form.get("experience")),qualifications:form.get("qualifications"),consent:form.get("consent")==="on",website:form.get("website")})});setReceipt(`${result.message} Reference: ${result.reference}`);}catch(e){setError(e instanceof Error?e.message:"Application could not be sent. Try again.");}finally{setBusy(false);}}
    return <AppShell><div className={styles.workspace}><section className={styles.hero}><p>BE PART OF US</p><h1>Your next chapter<br/>could begin at Gokul.</h1><p>Explore our branch opportunities. If you don’t see a suitable opening, share your interests and experience with our team.</p><Link href="/about" className={styles.button}>Meet Gokul</Link></section>
    {loading?<p role="status" className={styles.panel}>Loading opportunities…</p>:<><div className={styles.header}><h2>Current openings</h2><p>Experience is a preference. Read each role’s requirements before applying.</p></div><div className={styles.jobs}>{jobs.map(j=><article key={j.id} className={styles.panel}><p className={styles.badge}>{j.branchName} · {j.department}</p><h2>{j.title}</h2><p className={styles.help}>{j.minimumExperience} years preferred</p><p className={styles.copy}>{j.requirements}</p><button className={styles.primary} onClick={()=>{setJob(j);setBranch(String(j.branchId));setReceipt("");setRequestId("");document.getElementById("application")?.scrollIntoView({behavior:"smooth"});}}>Apply for this role</button></article>)}</div>{!jobs.length&&<p className={styles.panel}>There are no published openings at the moment. You can still send general interest below.</p>}</>}
    {error&&<div className={styles.message} role="alert">{error} {loading===false&&branches.length===0&&<button onClick={()=>{setLoading(true);setError("");setRevision(v=>v+1);}}>Reload opportunities</button>}</div>}
    <section id="application" className={styles.panel}><h2>{job?`Apply: ${job.title}`:"Tell us about yourself"}</h2><p className={styles.help}>Your details are private and only accessible to authorised staff for recruitment. Submitting does not guarantee an interview or employment.</p>{receipt?<p role="status" className={styles.message}>{receipt}</p>:<form onSubmit={submit}>
    {job&&<div className={styles.actions}><span>{job.branchName}</span><button type="button" disabled={busy} onClick={()=>{setJob(null);setRequestId("");}}>Send general interest instead</button></div>}
    <div className={styles.grid}><label className={styles.field}>Full name<input name="name" required minLength={2} maxLength={100} autoComplete="name"/></label><label className={styles.field}><T text="Mobile number" /><input name="phone" required type="tel" pattern="(\+91)?[6-9][0-9]{9}" placeholder="10-digit Indian mobile" autoComplete="tel"/></label><label className={styles.field}>Email (optional)<input name="email" type="email" maxLength={254} autoComplete="email"/></label><label className={styles.field}><T text="Preferred branch" /><select required value={branch} disabled={!!job||busy} onChange={e=>{setBranch(e.target.value);setRequestId("");}}><option value="">Choose a branch</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label>{!job&&<label className={styles.field}>Preferred role<input name="desiredRole" required maxLength={120}/></label>}<label className={styles.field}>Experience in years<input name="experience" required type="number" min="0" max="60" step="0.1" defaultValue="0"/><span className={styles.help}>Include relevant experience; enter 0 if you’re starting out.</span></label></div><label className={styles.field}>Relevant qualifications and experience<textarea name="qualifications" required maxLength={2000} placeholder="Skills, training and experience relevant to your preferred role. Do not include identity documents or bank details."/></label><label className={styles.honeypot} aria-hidden="true">Website<input name="website" tabIndex={-1} autoComplete="off"/></label><label className={styles.check}><input name="consent" type="checkbox" required/>I agree that Gokul Sweets may review my application and contact me for recruitment.</label><p className={styles.help}><Link href="/about#privacy-policy">Read our privacy policy</Link></p><button className={styles.primary} disabled={busy||!branches.length||loading}>{busy?"Submitting…":"Submit application"}</button></form>}</section></div></AppShell>;
}
