/* eslint-disable @next/next/no-img-element -- Actual uploaded packaging galleries. */
"use client";
import type {OccasionSweet,OccasionBox,PackingDraft} from "@/types/occasionCatalogue";
const money=(amount:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(amount);
export default function OccasionPackingBuilder({products,boxes,groups,onChange}:{products:OccasionSweet[];boxes:OccasionBox[];groups:PackingDraft[];onChange:(value:PackingDraft[])=>void}) {
 const patch=(key:number,value:Partial<PackingDraft>)=>onChange(groups.map(group=>group.key===key?{...group,...value}:group));
 function add(kind:"MIXED"|"WEIGHT") {const box=boxes.find(box=>kind==="MIXED"||box.capacityGrams===1000);onChange([...groups,{key:Math.max(0,...groups.map(group=>group.key))+1,kind,boxId:box?.id??null,boxCount:kind==="MIXED"?1000:0,recipe:[],productId:kind==="WEIGHT"?products.find(p=>p.saleMode==="WEIGHT")?.id??null:null,totalGrams:kind==="WEIGHT"?0:null,packGrams:kind==="WEIGHT"?1000:null,includeSpoons:false}]);}
 return <section className="occasion-packing-builder space-y-4" aria-label="Choose packing groups"><div><h2 className="font-serif text-2xl">03 · Make the packing yours</h2><p className="mt-2 text-sm">Mix gift assortments and kg packs in one request. Items not assigned to a group use bulk packing. Every group adds its food quantities automatically. Bulk quantities above are additional and use bulk packing.</p></div>
 <div className="flex flex-wrap gap-3"><button type="button" disabled={!boxes.length||groups.length>=30} onClick={()=>add("MIXED")} className="occasion-packing-action">Add mixed-piece boxes</button><button type="button" disabled={!boxes.some(box=>box.capacityGrams)||groups.length>=30} onClick={()=>add("WEIGHT")} className="occasion-packing-action">Add 1 kg / 500 g / 250 g packs</button></div>{!boxes.some(box=>box.capacityGrams)&&<p className="text-sm">Weight-pack boxes are not published for this branch yet. You can request bulk kg and describe your preferred packing in the notes.</p>}
 {groups.map((group,index)=>{const box=boxes.find(box=>box.id===group.boxId),gallery=box?.imageUrls?.length?box.imageUrls:box?.imageUrl?[box.imageUrl]:[];const weight=group.kind==="WEIGHT";return <fieldset key={group.key} className="occasion-packing-card rounded-2xl border bg-[#fffaf2] p-4 sm:p-5"><legend className="px-2 font-bold">Group {index+1} · {weight?"Weight packs":"Mixed-piece boxes"}</legend><div className="flex items-start justify-between gap-3"><p className="text-sm">{weight?"Choose an item and kg for this packing group; we add it to your request automatically.":"Choose what goes inside each box. We multiply by the number of boxes."}</p><button type="button" aria-label={`Remove packing group ${index+1}`} onClick={()=>onChange(groups.filter(g=>g.key!==group.key))} className="min-h-11 shrink-0 text-sm underline">Remove group</button></div>
 <div className="mt-3 grid gap-3 sm:grid-cols-2">{weight&&<><label className="text-sm">Item<select aria-label={`Group ${index+1} item`} value={group.productId??""} onChange={event=>patch(group.key,{productId:Number(event.target.value)})} className="mt-1 w-full rounded-xl border bg-white p-3">{products.filter(p=>p.saleMode==="WEIGHT").map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="text-sm">Pack size<select aria-label={`Group ${index+1} pack size`} value={group.packGrams??1000} onChange={event=>{const size=Number(event.target.value);patch(group.key,{packGrams:size,boxId:boxes.find(box=>box.capacityGrams===size)?.id??null,boxCount:(group.totalGrams??0)/size});}} className="mt-1 w-full rounded-xl border bg-white p-3"><option value={1000}>1 kg</option><option value={500}>500 g (½ kg)</option><option value={250}>250 g (¼ kg)</option></select></label></>}
 <label className="text-sm">Packaging<select aria-label={`Group ${index+1} packaging`} required value={group.boxId??""} onChange={event=>patch(group.key,{boxId:Number(event.target.value)||null})} className="mt-1 w-full rounded-xl border bg-white p-3"><option value="">Choose a published box</option>{boxes.filter(box=>!weight||box.capacityGrams===group.packGrams).map(box=><option key={box.id} value={box.id??""}>{box.name} · {box.price==null?"price on review":`${money(box.price)} each`}</option>)}</select></label>
 {weight?<label className="text-sm">Total kg in this group<input aria-label={`Group ${index+1} total kg`} type="number" min={.25} step={.25} required value={(group.totalGrams??0)/1000||""} onChange={event=>{const grams=Math.round(Number(event.target.value)*1000);patch(group.key,{totalGrams:grams,boxCount:grams/(group.packGrams??1000)});}} className="mt-1 w-full rounded-xl border bg-white p-3" /><span className="mt-1 block text-xs">Pack count is calculated automatically; the quantity must fill whole packs.</span></label>:<label className="text-sm">Number of mixed boxes<input aria-label={`Group ${index+1} box count`} type="number" required min={1} max={10000} step={1} value={group.boxCount} onChange={event=>patch(group.key,{boxCount:Number(event.target.value)})} className="mt-1 w-full rounded-xl border bg-white p-3" /></label>}
 </div>{box&&<div className="mt-3 flex items-center gap-3">{gallery[0]&&<img src={gallery[0]} alt={`${box.name} packaging`} className="h-20 w-24 rounded-xl object-cover" />}<div className="text-sm"><strong>{box.name}</strong><p>{box.dimensions} · {box.material}</p><p>{weight?`${box.capacityGrams} g food capacity`:`Up to ${box.capacityPieces} pieces per box`} · {box.leadDays} days notice</p></div></div>}{gallery.length>1&&<details className="mt-2 text-sm"><summary className="min-h-11 cursor-pointer">See actual box photos</summary><div className="flex gap-3 overflow-x-auto">{gallery.map((url,n)=><img key={url} src={url} alt={`${box?.name} view ${n+1}`} className="h-32 w-40 rounded-xl object-cover" />)}</div></details>}
 {!weight&&<div className="mt-4 space-y-3"><label className="block text-sm">Add an item to each box<select aria-label={`Group ${index+1} add mixed item`} value="" onChange={event=>{if(event.target.value)patch(group.key,{recipe:[...group.recipe,{productId:Number(event.target.value),pieces:1}]});}} className="mt-1 w-full rounded-xl border bg-white p-3"><option value="">Choose from the occasion collection</option>{products.filter(p=>!group.recipe.some(x=>x.productId===p.id)).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><div className="grid gap-3 sm:grid-cols-2">{group.recipe.map(line=>{const p=products.find(p=>p.id===line.productId)!;return <div key={p.id} className="rounded-xl border bg-white p-3"><label className="flex items-center justify-between gap-3 text-sm"><span>{p.name}<small className="block">Pieces in each box</small></span><input aria-label={`Group ${index+1} ${p.name} pieces per box`} type="number" min={1} max={1000} step={1} value={line.pieces} onChange={event=>patch(group.key,{recipe:group.recipe.map(x=>x.productId===p.id?{...x,pieces:Number(event.target.value)}:x)})} className="w-20 rounded-lg border p-2" /></label><p className="mt-2 text-xs">{(line.pieces*group.boxCount).toLocaleString("en-IN")} pieces total</p><button type="button" aria-label={`Group ${index+1} remove ${p.name}`} onClick={()=>patch(group.key,{recipe:group.recipe.filter(x=>x.productId!==p.id)})} className="mt-1 min-h-11 text-xs underline">Remove item from box</button></div>;})}</div></div>}
 <label className="mt-4 flex gap-2 text-sm"><input type="checkbox" checked={group.includeSpoons} onChange={event=>patch(group.key,{includeSpoons:event.target.checked})} />One spoon per box · branch prices it separately</label><p className="mt-3 text-sm font-semibold">{Number.isInteger(group.boxCount)?group.boxCount.toLocaleString("en-IN"):"Choose a quantity that fills whole"} {weight?"packs":"boxes"}{box?.price!=null&&Number.isInteger(group.boxCount)?` · packaging estimate ${money(box.price*group.boxCount)}`:""}</p><p className="mt-1 text-xs">The branch checks actual fit and supplies all agreed quantities before invoicing.</p></fieldset>;})}</section>;
}
