package com.gokulsweets.restaurant.staff;

public enum PermissionName {
    ORDER_VIEW,
    ORDER_START_PREPARATION,
    ORDER_MARK_READY,
    ORDER_MARK_PICKED_UP,
    ORDER_CANCEL,
    DISCOUNT_APPLY,
    DISCOUNT_OVERRIDE_LIMIT,
    REFUND_CREATE,
    REPORT_VIEW,
    MENU_MANAGE,
    INVENTORY_VIEW,
    INVENTORY_MANAGE,
    STAFF_MANAGE,
    CUSTOMER_VIEW,
    APPROVAL_VIEW,
    APPROVAL_MANAGE,
    PAYROLL_VIEW,
    PAYROLL_MANAGE,
    REBATE_VIEW,
    REBATE_MANAGE,
    BRANCH_MANAGE
}
