CREATE TABLE brand_story (
 id INTEGER PRIMARY KEY CHECK(id=1), title VARCHAR(120) NOT NULL DEFAULT 'Made for moments worth sharing.', subtitle VARCHAR(400) NOT NULL DEFAULT 'Discover the people and care behind Gokul Sweets.', story_title VARCHAR(120) NOT NULL DEFAULT 'Our story', story_body VARCHAR(6000) NOT NULL DEFAULT 'We prepare sweets, savouries and food for moments shared with family and friends.', image_url VARCHAR(2048), published BOOLEAN NOT NULL DEFAULT FALSE, version BIGINT NOT NULL DEFAULT 0
);
INSERT INTO brand_story(id) VALUES(1);
CREATE TABLE brand_people (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, section VARCHAR(12) NOT NULL CHECK(section IN ('FOUNDER','TEAM','DEVELOPER')), name VARCHAR(100) NOT NULL, role VARCHAR(120) NOT NULL, bio VARCHAR(1500) NOT NULL DEFAULT '', photo_url VARCHAR(2048), display_order INTEGER NOT NULL DEFAULT 0, published BOOLEAN NOT NULL DEFAULT FALSE, version BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX brand_people_public_order ON brand_people(published,section,display_order,id);
CREATE TABLE career_jobs (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, branch_id BIGINT NOT NULL REFERENCES branches(id), title VARCHAR(120) NOT NULL, department VARCHAR(80) NOT NULL, requirements VARCHAR(3000) NOT NULL, minimum_experience NUMERIC(4,1) NOT NULL DEFAULT 0 CHECK(minimum_experience BETWEEN 0 AND 60), active BOOLEAN NOT NULL DEFAULT FALSE, version BIGINT NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX career_jobs_branch_active ON career_jobs(branch_id,active,id DESC);
CREATE TABLE career_applications (
 id UUID PRIMARY KEY, job_id BIGINT REFERENCES career_jobs(id), branch_id BIGINT NOT NULL REFERENCES branches(id), name VARCHAR(100) NOT NULL, phone VARCHAR(16) NOT NULL, email VARCHAR(254), desired_role VARCHAR(120) NOT NULL, experience NUMERIC(4,1) NOT NULL CHECK(experience BETWEEN 0 AND 60), qualifications VARCHAR(2000) NOT NULL, status VARCHAR(16) NOT NULL DEFAULT 'NEW' CHECK(status IN ('NEW','REVIEWING','SHORTLISTED','INTERVIEW','HIRED','REJECTED')), staff_notes VARCHAR(3000) NOT NULL DEFAULT '', consent_version VARCHAR(20) NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, version BIGINT NOT NULL DEFAULT 0
);
CREATE INDEX career_applications_queue ON career_applications(branch_id,status,created_at DESC,id);
CREATE INDEX career_applications_role_experience ON career_applications(job_id,experience,created_at DESC,id);
CREATE UNIQUE INDEX career_applications_active_contact ON career_applications(branch_id,COALESCE(job_id,0),phone) WHERE status NOT IN ('HIRED','REJECTED');
CREATE TABLE career_application_throttle (client_key CHAR(64) PRIMARY KEY, window_start TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP, requests INTEGER NOT NULL DEFAULT 0);
CREATE TABLE brand_career_audit (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,staff_id BIGINT NOT NULL REFERENCES staff_users(id),action VARCHAR(40) NOT NULL,entity_id VARCHAR(50) NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
INSERT INTO permissions(name,description) VALUES ('ABOUT_MANAGE','Manage public brand story and people'),('CAREERS_MANAGE','Manage job openings and confidential applications') ON CONFLICT(name) DO NOTHING;
INSERT INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.name='OWNER_ADMIN' AND p.name IN ('ABOUT_MANAGE','CAREERS_MANAGE') ON CONFLICT DO NOTHING;
CREATE INDEX career_applications_search ON career_applications USING GIN(to_tsvector('simple',name||' '||desired_role||' '||qualifications));
