CREATE TABLE tax_collection_settings (
    id integer PRIMARY KEY CHECK (id = 1),
    enabled boolean NOT NULL DEFAULT true,
    updated_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint REFERENCES staff_users(id)
);
INSERT INTO tax_collection_settings (id, enabled) VALUES (1, true);
CREATE TABLE tax_collection_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enabled boolean NOT NULL,
    changed_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    changed_by bigint NOT NULL REFERENCES staff_users(id)
);
