-- SCRUM-38. Exact verified subject, never inferred from historical phone/order data.
ALTER TABLE orders ADD COLUMN loyalty_enrolled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE orders ADD COLUMN loyalty_discount NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (loyalty_discount >= 0);
ALTER TABLE orders ADD COLUMN loyalty_reward_code VARCHAR(40);
ALTER TABLE orders ADD COLUMN loyalty_coins INTEGER NOT NULL DEFAULT 0 CHECK (loyalty_coins >= 0);
CREATE TABLE loyalty_accounts (
 environment VARCHAR(8) NOT NULL CHECK(environment IN ('DEV','PROD')),
 subject_id UUID NOT NULL, last_qualifying_activity TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY(environment,subject_id)
);
CREATE TABLE loyalty_rewards (
 code VARCHAR(40) PRIMARY KEY, name VARCHAR(100) NOT NULL,
 coins INTEGER NOT NULL CHECK(coins>0), discount NUMERIC(12,2) NOT NULL CHECK(discount>0),
 minimum_subtotal NUMERIC(12,2) NOT NULL CHECK(minimum_subtotal>0), active BOOLEAN NOT NULL DEFAULT TRUE
);
INSERT INTO loyalty_rewards VALUES
 ('SWEET_5','₹5 sweet saving',30,5,149,TRUE), ('SWEET_15','₹15 sweet saving',75,15,249,TRUE),
 ('SWEET_35','₹35 sweet saving',150,35,399,TRUE), ('SWEET_75','₹75 sweet saving',300,75,699,TRUE);
CREATE TABLE loyalty_ledger (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 environment VARCHAR(8) NOT NULL, subject_id UUID NOT NULL,
 event_key VARCHAR(160) NOT NULL, kind VARCHAR(30) NOT NULL, coins INTEGER NOT NULL,
 order_id BIGINT REFERENCES orders(id), source_credit_id BIGINT REFERENCES loyalty_ledger(id), reason VARCHAR(300) NOT NULL,
 expires_at TIMESTAMPTZ, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(environment,subject_id,event_key),
 FOREIGN KEY(environment,subject_id) REFERENCES loyalty_accounts(environment,subject_id)
);
CREATE INDEX loyalty_ledger_owner ON loyalty_ledger(environment,subject_id,id);
CREATE INDEX loyalty_ledger_order_kind ON loyalty_ledger(order_id,kind) WHERE order_id IS NOT NULL;
-- Mutable projections; source of truth is the append-only ledger.
CREATE TABLE loyalty_lots (
 ledger_id BIGINT PRIMARY KEY REFERENCES loyalty_ledger(id), remaining INTEGER NOT NULL CHECK(remaining>=0)
);
CREATE TABLE loyalty_holds (
 order_id BIGINT REFERENCES orders(id), generation INTEGER NOT NULL, environment VARCHAR(8) NOT NULL, subject_id UUID NOT NULL,
 reward_code VARCHAR(40) NOT NULL, coins INTEGER NOT NULL CHECK(coins>0), discount NUMERIC(12,2) NOT NULL,
 state VARCHAR(20) NOT NULL CHECK(state IN ('RESERVED','CONSUMED','RELEASED')), PRIMARY KEY(order_id,generation),
 FOREIGN KEY(environment,subject_id) REFERENCES loyalty_accounts(environment,subject_id)
);
CREATE TABLE loyalty_hold_lots (
 order_id BIGINT NOT NULL, generation INTEGER NOT NULL, ledger_id BIGINT REFERENCES loyalty_ledger(id),
 coins INTEGER NOT NULL CHECK(coins>0), PRIMARY KEY(order_id,generation,ledger_id), FOREIGN KEY(order_id,generation) REFERENCES loyalty_holds(order_id,generation)
);
CREATE OR REPLACE FUNCTION prevent_loyalty_ledger_mutation() RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'Loyalty ledger is append-only; use a compensating event'; END $$;
CREATE TRIGGER loyalty_ledger_immutable BEFORE UPDATE OR DELETE ON loyalty_ledger
 FOR EACH ROW EXECUTE FUNCTION prevent_loyalty_ledger_mutation();

CREATE TABLE loyalty_adjustment_audit (
 ledger_id BIGINT PRIMARY KEY REFERENCES loyalty_ledger(id), staff_id BIGINT NOT NULL REFERENCES staff_users(id),
 old_balance INTEGER NOT NULL, new_balance INTEGER NOT NULL, reason VARCHAR(300) NOT NULL
);
ALTER TABLE orders ADD COLUMN loyalty_eligible_subtotal NUMERIC(12,2) NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN loyalty_test_order BOOLEAN NOT NULL DEFAULT FALSE;
CREATE TABLE loyalty_excluded_products(product_id BIGINT PRIMARY KEY REFERENCES products(id));
CREATE TABLE loyalty_excluded_rebates(code VARCHAR(100) PRIMARY KEY);
CREATE TABLE loyalty_qualifying_orders (
 order_id BIGINT PRIMARY KEY REFERENCES orders(id), environment VARCHAR(8) NOT NULL, subject_id UUID NOT NULL,
 eligible_subtotal NUMERIC(12,2) NOT NULL, completed_at TIMESTAMPTZ NOT NULL, reversed BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE loyalty_admin_audit (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, staff_id BIGINT NOT NULL REFERENCES staff_users(id),
 kind VARCHAR(30) NOT NULL, target VARCHAR(100) NOT NULL, reason VARCHAR(300) NOT NULL,
 before_value JSONB NOT NULL, after_value JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE orders ADD COLUMN rebate_manual_selection BOOLEAN NOT NULL DEFAULT FALSE;
-- Accepted quotes and pending checkouts bind the earning policy and catalogue revision.
ALTER TABLE loyalty_rewards ADD COLUMN version BIGINT NOT NULL DEFAULT 1;
ALTER TABLE orders ADD COLUMN loyalty_earning_rupees_per_coin NUMERIC(12,2) NOT NULL DEFAULT 10 CHECK(loyalty_earning_rupees_per_coin>0);
ALTER TABLE orders ADD COLUMN loyalty_qualifying_minimum NUMERIC(12,2) NOT NULL DEFAULT 149;
ALTER TABLE orders ADD COLUMN loyalty_welcome_coins INTEGER NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN loyalty_expiry_days INTEGER NOT NULL DEFAULT 180 CHECK(loyalty_expiry_days BETWEEN 1 AND 180);
ALTER TABLE loyalty_ledger ADD COLUMN expiry_days INTEGER NOT NULL DEFAULT 180 CHECK(expiry_days BETWEEN 1 AND 180);
