-- Existing badges remain recognition-only until the owner explicitly configures a bonus.
CREATE TABLE customer_badges (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 code VARCHAR(40) NOT NULL UNIQUE,
 name VARCHAR(80) NOT NULL,
 description VARCHAR(240) NOT NULL DEFAULT '',
 required_orders INTEGER NOT NULL CHECK(required_orders BETWEEN 1 AND 100000),
 minimum_subtotal NUMERIC(12,2) NOT NULL CHECK(minimum_subtotal BETWEEN 0 AND 1000000),
 bonus_percent NUMERIC(5,2) NOT NULL DEFAULT 0 CHECK(bonus_percent BETWEEN 0 AND 100),
 appearance VARCHAR(12) NOT NULL DEFAULT 'GOLD' CHECK(appearance IN ('GOLD','SILVER','MAROON')),
 active BOOLEAN NOT NULL DEFAULT TRUE,
 version INTEGER NOT NULL DEFAULT 1,
 updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO customer_badges(code,name,description,required_orders,minimum_subtotal) VALUES
 ('FIRST_VISIT','First visit','Your first completed paid order',1,0),
 ('REGULAR','Regular','Five completed paid orders',5,0),
 ('GOKUL_FAVOURITE','Gokul favourite','Twenty completed paid orders',20,0);
CREATE TABLE customer_badge_awards (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 environment VARCHAR(20) NOT NULL,
 subject_id UUID NOT NULL,
 badge_id BIGINT NOT NULL REFERENCES customer_badges(id),
 name VARCHAR(80) NOT NULL,
 description VARCHAR(240) NOT NULL,
 bonus_percent NUMERIC(5,2) NOT NULL,
 appearance VARCHAR(12) NOT NULL,
 earned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
 celebrated_at TIMESTAMPTZ,
 claim_id UUID,
 claim_until TIMESTAMPTZ,
 UNIQUE(environment,subject_id,badge_id)
);
CREATE INDEX customer_badge_awards_subject ON customer_badge_awards(environment,subject_id,id);
CREATE TABLE customer_badge_audit (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 badge_id BIGINT NOT NULL REFERENCES customer_badges(id),
 staff_id BIGINT NOT NULL,
 reason VARCHAR(300) NOT NULL,
 definition JSONB NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
-- Do not replay old achievements as new celebrations when this migration is deployed.
INSERT INTO customer_badge_awards(environment,subject_id,badge_id,name,description,bonus_percent,appearance,celebrated_at)
SELECT own.environment,own.verified_subject_id,b.id,b.name,b.description,b.bonus_percent,b.appearance,CURRENT_TIMESTAMP
FROM verified_order_ownership own JOIN orders o ON o.id=own.order_id CROSS JOIN customer_badges b
WHERE o.order_status IN ('PICKED_UP','DELIVERED') AND NOT o.loyalty_test_order
 AND EXISTS(SELECT 1 FROM payments p WHERE p.order_id=o.id AND p.payment_status='PAID')
 AND NOT EXISTS(SELECT 1 FROM payments p WHERE p.order_id=o.id AND p.payment_status IN ('REFUND_PENDING','REFUNDED','REFUND_FAILED'))
GROUP BY own.environment,own.verified_subject_id,b.id
HAVING COUNT(*)>=b.required_orders;
ALTER TABLE orders ADD COLUMN loyalty_badge_bonus_percent NUMERIC(5,2) NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN loyalty_badge_name VARCHAR(80);
ALTER TABLE loyalty_ledger ADD COLUMN badge_bonus_coins INTEGER NOT NULL DEFAULT 0;
ALTER TABLE loyalty_ledger ADD COLUMN badge_name VARCHAR(80);
