CREATE TABLE homepage_campaigns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(20) NOT NULL DEFAULT 'HERO' CHECK (type IN ('HERO', 'FEATURE')),
    title VARCHAR(120) NOT NULL,
    subtitle VARCHAR(240),
    media_url VARCHAR(1000),
    media_type VARCHAR(40),
    fallback_media_url VARCHAR(1000),
    cta_label VARCHAR(60),
    cta_target VARCHAR(240),
    start_at TIMESTAMP WITH TIME ZONE,
    end_at TIMESTAMP WITH TIME ZONE,
    active BOOLEAN NOT NULL DEFAULT FALSE,
    display_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_campaign_window CHECK (start_at IS NULL OR end_at IS NULL OR end_at > start_at)
);

CREATE INDEX idx_homepage_campaign_schedule ON homepage_campaigns (active, display_order, start_at, end_at);
