ALTER TABLE homepage_campaigns ADD COLUMN alt_text VARCHAR(180);
ALTER TABLE homepage_campaigns ADD COLUMN branch_id BIGINT REFERENCES branches(id);
ALTER TABLE homepage_campaigns ADD COLUMN mobile_media_url VARCHAR(1000);
ALTER TABLE homepage_campaigns ADD COLUMN mobile_request_id UUID;
ALTER TABLE homepage_campaigns ADD COLUMN published_revision BIGINT;

-- Publication snapshots make a multi-step draft upload invisible until publish.
-- Historical R2 URLs are kept so a previous publication can be restored.
CREATE TABLE campaign_publications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_id BIGINT NOT NULL REFERENCES homepage_campaigns(id),
    type VARCHAR(20) NOT NULL,
    title VARCHAR(120) NOT NULL,
    subtitle VARCHAR(240),
    alt_text VARCHAR(180),
    branch_id BIGINT REFERENCES branches(id),
    media_url VARCHAR(1000) NOT NULL,
    media_type VARCHAR(40) NOT NULL,
    mobile_media_url VARCHAR(1000),
    fallback_media_url VARCHAR(1000),
    cta_label VARCHAR(60),
    cta_target VARCHAR(240),
    start_at TIMESTAMP WITH TIME ZONE,
    end_at TIMESTAMP WITH TIME ZONE,
    display_order INTEGER NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_campaign_publications_campaign ON campaign_publications(campaign_id, id DESC);
CREATE TABLE campaign_mobile_requests (
    campaign_id BIGINT NOT NULL REFERENCES homepage_campaigns(id),
    request_id UUID NOT NULL,
    request_hash VARCHAR(64) NOT NULL,
    PRIMARY KEY(campaign_id, request_id)
);

-- Preserve campaigns published before the flag exists when the new flag is enabled.
INSERT INTO campaign_publications (campaign_id,type,title,subtitle,alt_text,media_url,media_type,
    fallback_media_url,cta_label,cta_target,start_at,end_at,display_order,published_at)
SELECT id,type,title,subtitle,title,media_url,COALESCE(media_type,'image/jpeg'),
    fallback_media_url,cta_label,cta_target,start_at,end_at,display_order,updated_at
FROM homepage_campaigns WHERE active = TRUE AND media_url IS NOT NULL;
UPDATE homepage_campaigns c SET published_revision = p.id, alt_text = c.title
FROM campaign_publications p WHERE p.campaign_id = c.id;
