-- SCRUM-49: store optional consent decisions only for a verified customer subject.
-- No guest phone or unverified customer contact may be used as a subject.
CREATE TABLE customer_consent_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment VARCHAR(8) NOT NULL CHECK (environment IN ('DEV', 'PROD')),
    verified_subject_id UUID NOT NULL,
    purpose VARCHAR(32) NOT NULL CHECK (purpose IN ('MARKETING', 'OCCASION_REMINDERS', 'COARSE_AREA_ANALYTICS')),
    policy_version VARCHAR(40) NOT NULL,
    granted BOOLEAN NOT NULL,
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actor VARCHAR(40) NOT NULL CHECK (actor IN ('CUSTOMER', 'SYSTEM_WITHDRAWAL')),
    CONSTRAINT customer_consent_version_not_blank CHECK (length(trim(policy_version)) > 0)
);

CREATE INDEX idx_customer_consent_events_subject_purpose
    ON customer_consent_events (environment, verified_subject_id, purpose, id DESC);

COMMENT ON TABLE customer_consent_events IS
    'Append-only optional consent history; no coordinates, phone number, or order identity. Customer APIs require verified identity before use.';
