-- SCRUM-36: dormant session store; no public issuance endpoint exists yet.
CREATE TABLE verified_customer_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment VARCHAR(8) NOT NULL CHECK (environment IN ('DEV', 'PROD')),
    verified_subject_id UUID NOT NULL,
    token_digest BYTEA NOT NULL UNIQUE,
    issued_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT verified_customer_sessions_expiry CHECK (expires_at > issued_at)
);

CREATE INDEX idx_verified_customer_sessions_subject
    ON verified_customer_sessions(environment, verified_subject_id, expires_at DESC);
