-- SCRUM-36: retain a restricted chain for separately verified account recovery.
-- Possession of the current phone never grants access to an older subject.
CREATE TABLE verified_subject_rotations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment VARCHAR(8) NOT NULL CHECK (environment IN ('DEV', 'PROD')),
    prior_subject_id UUID NOT NULL,
    new_subject_id UUID NOT NULL,
    rotated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    reason VARCHAR(32) NOT NULL CHECK (reason = 'PHONE_REVERIFICATION'),
    CONSTRAINT verified_subject_rotations_distinct CHECK (prior_subject_id <> new_subject_id),
    CONSTRAINT verified_subject_rotations_new_unique UNIQUE (environment, new_subject_id)
);

CREATE INDEX idx_verified_subject_rotations_prior
    ON verified_subject_rotations (environment, prior_subject_id);
