-- Owner-selected policy: a fresh verified OTP transfers prior verified orders
-- for that phone, even when the previous browser session is unavailable.
ALTER TABLE verified_subject_rotations
    ADD COLUMN transferred_order_count INTEGER NOT NULL DEFAULT 0
    CHECK (transferred_order_count >= 0);

CREATE TABLE verified_order_transfer_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    environment VARCHAR(8) NOT NULL CHECK (environment IN ('DEV', 'PROD')),
    prior_subject_id UUID NOT NULL,
    new_subject_id UUID NOT NULL,
    transferred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT verified_order_transfer_distinct CHECK (prior_subject_id <> new_subject_id),
    CONSTRAINT verified_order_transfer_once UNIQUE (environment, order_id, new_subject_id)
);
CREATE INDEX idx_verified_order_transfer_order
    ON verified_order_transfer_audit(environment, order_id, transferred_at DESC);
