-- Verified customer requests are review tickets, never automatic order deletion.
CREATE TABLE customer_privacy_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment VARCHAR(8) NOT NULL CHECK (environment IN ('DEV', 'PROD')),
    verified_subject_id UUID NOT NULL,
    request_kind VARCHAR(16) NOT NULL CHECK (request_kind IN ('EXPORT', 'DELETION_REVIEW')),
    received_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT customer_privacy_request_once UNIQUE (environment, verified_subject_id, request_kind)
);

COMMENT ON TABLE customer_privacy_requests IS
    'Manual privacy request intake only. No order deletion or data export runs automatically.';
