INSERT INTO permissions (name, description) VALUES
    ('PRIVACY_REQUEST_VIEW', 'Review verified customer privacy request metadata')
ON CONFLICT (name) DO NOTHING;

-- Privacy requests are restricted to the owner role, independently of CUSTOMER_VIEW.
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
WHERE r.name = 'OWNER_ADMIN' AND p.name = 'PRIVACY_REQUEST_VIEW'
ON CONFLICT DO NOTHING;

CREATE TABLE customer_privacy_queue_access_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    staff_user_id BIGINT NOT NULL REFERENCES staff_users(id),
    environment VARCHAR(8) NOT NULL CHECK (environment IN ('DEV', 'PROD')),
    viewed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    returned_count INTEGER NOT NULL CHECK (returned_count >= 0),
    page_number INTEGER NOT NULL CHECK (page_number >= 0)
);

CREATE INDEX idx_customer_privacy_queue_access_staff
    ON customer_privacy_queue_access_audit (staff_user_id, viewed_at DESC);
