ALTER TABLE customer_privacy_requests
    ADD COLUMN review_state VARCHAR(24) NOT NULL DEFAULT 'RECEIVED'
    CHECK (review_state IN ('RECEIVED', 'IN_REVIEW', 'NEEDS_REVERIFICATION'));

CREATE TABLE customer_privacy_triage_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL REFERENCES customer_privacy_requests(id),
    staff_user_id BIGINT NOT NULL REFERENCES staff_users(id),
    from_state VARCHAR(24) NOT NULL,
    to_state VARCHAR(24) NOT NULL CHECK (to_state IN ('IN_REVIEW', 'NEEDS_REVERIFICATION')),
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT customer_privacy_triage_changes_state CHECK (from_state <> to_state)
);

CREATE INDEX idx_customer_privacy_triage_request
    ON customer_privacy_triage_events (request_id, recorded_at DESC);
