-- SCRUM-37: saved choices belong to an exact verified subject in one environment.
-- Reverification deliberately does not transfer these details by phone number.
CREATE TABLE verified_customer_account (
    environment VARCHAR(8) NOT NULL CHECK (environment IN ('DEV', 'PROD')),
    subject_id UUID NOT NULL,
    dietary_notes VARCHAR(300),
    preferred_branch_id BIGINT REFERENCES branches(id) ON DELETE SET NULL,
    PRIMARY KEY (environment, subject_id)
);

CREATE TABLE verified_customer_favourites (
    environment VARCHAR(8) NOT NULL CHECK (environment IN ('DEV', 'PROD')),
    subject_id UUID NOT NULL,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (environment, subject_id, product_id)
);

CREATE TABLE verified_customer_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment VARCHAR(8) NOT NULL CHECK (environment IN ('DEV', 'PROD')),
    subject_id UUID NOT NULL,
    label VARCHAR(40) NOT NULL,
    address_line VARCHAR(180) NOT NULL,
    locality VARCHAR(100) NOT NULL,
    postal_code VARCHAR(6) NOT NULL CHECK (postal_code ~ '^[0-9]{6}$'),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_verified_customer_addresses_owner
    ON verified_customer_addresses(environment, subject_id, id);
