CREATE TABLE inventory_allocation_plan_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    allocation_id BIGINT NOT NULL REFERENCES inventory_daily_allocations(id),
    branch_product_id BIGINT NOT NULL REFERENCES branch_products(id),
    service_date DATE NOT NULL,
    performed_by VARCHAR(150) NOT NULL,
    before_state TEXT NOT NULL,
    after_state TEXT NOT NULL,
    changed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_inventory_allocation_plan_audit_product_date
    ON inventory_allocation_plan_audit(branch_product_id, service_date, changed_at DESC);
