ALTER TABLE homepage_campaigns ADD COLUMN main_x INTEGER NOT NULL DEFAULT 50 CHECK (main_x BETWEEN 0 AND 100);
ALTER TABLE homepage_campaigns ADD COLUMN main_y INTEGER NOT NULL DEFAULT 50 CHECK (main_y BETWEEN 0 AND 100);
ALTER TABLE homepage_campaigns ADD COLUMN main_zoom INTEGER NOT NULL DEFAULT 100 CHECK (main_zoom BETWEEN 100 AND 300);
ALTER TABLE homepage_campaigns ADD COLUMN main_fit VARCHAR(8) NOT NULL DEFAULT 'COVER' CHECK (main_fit IN ('COVER', 'CONTAIN'));
ALTER TABLE homepage_campaigns ADD COLUMN mobile_x INTEGER NOT NULL DEFAULT 50 CHECK (mobile_x BETWEEN 0 AND 100);
ALTER TABLE homepage_campaigns ADD COLUMN mobile_y INTEGER NOT NULL DEFAULT 50 CHECK (mobile_y BETWEEN 0 AND 100);
ALTER TABLE homepage_campaigns ADD COLUMN mobile_zoom INTEGER NOT NULL DEFAULT 100 CHECK (mobile_zoom BETWEEN 100 AND 300);
ALTER TABLE homepage_campaigns ADD COLUMN mobile_fit VARCHAR(8) NOT NULL DEFAULT 'COVER' CHECK (mobile_fit IN ('COVER', 'CONTAIN'));

ALTER TABLE campaign_publications ADD COLUMN main_x INTEGER NOT NULL DEFAULT 50 CHECK (main_x BETWEEN 0 AND 100);
ALTER TABLE campaign_publications ADD COLUMN main_y INTEGER NOT NULL DEFAULT 50 CHECK (main_y BETWEEN 0 AND 100);
ALTER TABLE campaign_publications ADD COLUMN main_zoom INTEGER NOT NULL DEFAULT 100 CHECK (main_zoom BETWEEN 100 AND 300);
ALTER TABLE campaign_publications ADD COLUMN main_fit VARCHAR(8) NOT NULL DEFAULT 'COVER' CHECK (main_fit IN ('COVER', 'CONTAIN'));
ALTER TABLE campaign_publications ADD COLUMN mobile_x INTEGER NOT NULL DEFAULT 50 CHECK (mobile_x BETWEEN 0 AND 100);
ALTER TABLE campaign_publications ADD COLUMN mobile_y INTEGER NOT NULL DEFAULT 50 CHECK (mobile_y BETWEEN 0 AND 100);
ALTER TABLE campaign_publications ADD COLUMN mobile_zoom INTEGER NOT NULL DEFAULT 100 CHECK (mobile_zoom BETWEEN 100 AND 300);
ALTER TABLE campaign_publications ADD COLUMN mobile_fit VARCHAR(8) NOT NULL DEFAULT 'COVER' CHECK (mobile_fit IN ('COVER', 'CONTAIN'));
