CREATE TABLE occasion_enquiries (
    id UUID PRIMARY KEY,
    environment VARCHAR(8) NOT NULL CHECK (environment IN ('DEV', 'PROD')),
    subject_id UUID NOT NULL,
    branch_id BIGINT NOT NULL REFERENCES branches(id),
    occasion_type VARCHAR(80) NOT NULL,
    service_date DATE NOT NULL,
    guest_count INTEGER NOT NULL CHECK (guest_count BETWEEN 1 AND 10000),
    fulfilment VARCHAR(16) NOT NULL CHECK (fulfilment IN ('PICKUP', 'DELIVERY_REQUEST')),
    delivery_address VARCHAR(500),
    notes VARCHAR(1000),
    status VARCHAR(24) NOT NULL CHECK (status IN
        ('REQUESTED', 'QUOTED', 'HELD', 'PAYMENT_PENDING', 'PAID', 'CONFIRMED', 'DECLINED', 'EXPIRED')),
    quoted_amount NUMERIC(12,2) CHECK (quoted_amount >= 0),
    deposit_amount NUMERIC(12,2) CHECK (deposit_amount >= 0),
    quote_terms VARCHAR(500),
    paid_amount NUMERIC(12,2) NOT NULL DEFAULT 0 CHECK (paid_amount >= 0),
    quote_expires_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK ((fulfilment = 'PICKUP' AND delivery_address IS NULL) OR
           (fulfilment = 'DELIVERY_REQUEST' AND delivery_address IS NOT NULL)),
    CHECK (deposit_amount IS NULL OR quoted_amount IS NOT NULL AND deposit_amount <= quoted_amount)
);

CREATE TABLE occasion_enquiry_items (
    enquiry_id UUID NOT NULL REFERENCES occasion_enquiries(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id),
    requested_quantity NUMERIC(12,3) NOT NULL CHECK (requested_quantity > 0),
    unit VARCHAR(12) NOT NULL CHECK (unit IN ('PIECE', 'GRAM')),
    PRIMARY KEY (enquiry_id, product_id)
);

CREATE TABLE occasion_enquiry_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enquiry_id UUID NOT NULL REFERENCES occasion_enquiries(id) ON DELETE CASCADE,
    actor VARCHAR(150) NOT NULL,
    from_status VARCHAR(24),
    to_status VARCHAR(24) NOT NULL,
    detail VARCHAR(500),
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_occasion_enquiries_staff ON occasion_enquiries(environment, branch_id, created_at DESC);
CREATE INDEX idx_occasion_enquiries_customer ON occasion_enquiries(environment, subject_id, created_at DESC);
