-- Durable in-app delivery is committed with the source transaction. No external sender.
CREATE TABLE customer_notification_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment VARCHAR(8) NOT NULL CHECK (environment IN ('DEV', 'PROD')),
    subject_id UUID NOT NULL,
    event_key VARCHAR(180) NOT NULL,
    kind VARCHAR(40) NOT NULL,
    target_type VARCHAR(12) NOT NULL CHECK (target_type IN ('ORDER', 'OCCASION')),
    target_id VARCHAR(80) NOT NULL,
    title VARCHAR(160) NOT NULL,
    message VARCHAR(500) NOT NULL,
    delivery_state VARCHAR(16) NOT NULL DEFAULT 'AVAILABLE' CHECK (delivery_state = 'AVAILABLE'),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMPTZ,
    UNIQUE (environment, subject_id, event_key)
);
CREATE INDEX idx_customer_notification_inbox ON customer_notification_events(environment, subject_id, id DESC);
CREATE INDEX idx_customer_notification_unread ON customer_notification_events(environment, subject_id) WHERE read_at IS NULL;
CREATE TABLE customer_notification_preferences (
    environment VARCHAR(8) NOT NULL CHECK (environment IN ('DEV', 'PROD')),
    subject_id UUID NOT NULL,
    offer_inbox_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (environment, subject_id)
);
