ALTER TABLE customer_notification_preferences
    ADD COLUMN sound_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN quiet_hours_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN quiet_start_minute INTEGER NOT NULL DEFAULT 1320 CHECK (quiet_start_minute BETWEEN 0 AND 1439),
    ADD COLUMN quiet_end_minute INTEGER NOT NULL DEFAULT 480 CHECK (quiet_end_minute BETWEEN 0 AND 1439);

CREATE TABLE customer_push_subscriptions (
    id UUID PRIMARY KEY,
    environment VARCHAR(8) NOT NULL CHECK (environment IN ('DEV','PROD')),
    subject_id UUID NOT NULL,
    session_id BIGINT NOT NULL REFERENCES verified_customer_sessions(id),
    endpoint TEXT NOT NULL,
    endpoint_hash CHAR(64) NOT NULL,
    public_key VARCHAR(120) NOT NULL,
    auth_secret VARCHAR(40) NOT NULL,
    subscribed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_at TIMESTAMPTZ,
    UNIQUE (environment, endpoint_hash)
);
CREATE INDEX idx_customer_push_owner ON customer_push_subscriptions(environment, subject_id) WHERE revoked_at IS NULL;

CREATE TABLE customer_push_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES customer_notification_events(id),
    subscription_id UUID NOT NULL REFERENCES customer_push_subscriptions(id),
    state VARCHAR(20) NOT NULL DEFAULT 'QUEUED' CHECK (state IN
        ('QUEUED','SENDING','ACCEPTED','REVOKED','SKIPPED','FAILED')),
    attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts BETWEEN 0 AND 3),
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lease_token UUID,
    lease_until TIMESTAMPTZ,
    accepted_at TIMESTAMPTZ,
    last_http_status INTEGER,
    UNIQUE (event_id, subscription_id)
);
CREATE INDEX idx_customer_push_queue ON customer_push_deliveries(next_attempt_at, id) WHERE state = 'QUEUED';
