CREATE TABLE staff_order_alerts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    environment VARCHAR(8) NOT NULL CHECK (environment IN ('DEV','PROD')),
    event_key VARCHAR(180) NOT NULL,
    order_id BIGINT NOT NULL REFERENCES orders(id),
    branch_id BIGINT NOT NULL REFERENCES branches(id),
    kind VARCHAR(30) NOT NULL CHECK (kind IN ('NEW_ORDER','PREPARATION_SOON','PREPARATION_DUE','PREPARATION_OVERDUE','READY_OVERDUE')),
    required_permission VARCHAR(80) NOT NULL,
    title VARCHAR(160) NOT NULL,
    message VARCHAR(500) NOT NULL,
    scheduled_at TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(environment, event_key)
);
CREATE INDEX idx_staff_alert_branch ON staff_order_alerts(environment, branch_id, id DESC);
CREATE TABLE staff_order_alert_reads (
    event_id BIGINT NOT NULL REFERENCES staff_order_alerts(id),
    staff_id BIGINT NOT NULL REFERENCES staff_users(id),
    read_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(event_id, staff_id)
);
CREATE TABLE staff_push_subscriptions (
    id UUID PRIMARY KEY,
    environment VARCHAR(8) NOT NULL CHECK (environment IN ('DEV','PROD')),
    staff_id BIGINT NOT NULL REFERENCES staff_users(id),
    session_hash CHAR(64) NOT NULL REFERENCES staff_sessions(token_hash),
    endpoint TEXT NOT NULL,
    endpoint_hash VARCHAR(64) NOT NULL,
    public_key VARCHAR(120) NOT NULL,
    auth_secret VARCHAR(40) NOT NULL,
    subscribed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    revoked_at TIMESTAMPTZ,
    UNIQUE(environment, endpoint_hash)
);
CREATE TABLE staff_alert_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES staff_order_alerts(id),
    staff_id BIGINT NOT NULL REFERENCES staff_users(id),
    channel VARCHAR(8) NOT NULL CHECK(channel IN ('PUSH','EMAIL')),
    subscription_id UUID REFERENCES staff_push_subscriptions(id),
    state VARCHAR(16) NOT NULL DEFAULT 'QUEUED' CHECK(state IN ('QUEUED','SENDING','ACCEPTED','SKIPPED','REVOKED','FAILED')),
    attempts INTEGER NOT NULL DEFAULT 0 CHECK(attempts BETWEEN 0 AND 3),
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lease_token UUID,
    lease_until TIMESTAMPTZ,
    accepted_at TIMESTAMPTZ,
    last_http_status INTEGER,
    CHECK((channel = 'PUSH' AND subscription_id IS NOT NULL) OR (channel = 'EMAIL' AND subscription_id IS NULL))
);
CREATE UNIQUE INDEX uq_staff_push_delivery ON staff_alert_deliveries(event_id, subscription_id) WHERE channel = 'PUSH';
CREATE UNIQUE INDEX uq_staff_email_delivery ON staff_alert_deliveries(event_id, staff_id) WHERE channel = 'EMAIL';
CREATE INDEX idx_staff_delivery_queue ON staff_alert_deliveries(next_attempt_at, id) WHERE state = 'QUEUED';
