ALTER TABLE branch_products ADD COLUMN occasion_only BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE branch_products ADD COLUMN occasion_published BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE branch_products ADD COLUMN occasion_lead_days INTEGER NOT NULL DEFAULT 0 CHECK (occasion_lead_days BETWEEN 0 AND 365);
ALTER TABLE branch_products ADD COLUMN occasion_piece_grams NUMERIC(9,3) CHECK (occasion_piece_grams > 0);
ALTER TABLE occasion_enquiry_items ADD COLUMN approved_quantity NUMERIC(12,3) CHECK (approved_quantity > 0);
ALTER TABLE occasion_enquiry_items ADD COLUMN approved_unit VARCHAR(8) CHECK (approved_unit IN ('GRAM','PIECE'));
ALTER TABLE occasion_enquiries ADD COLUMN packaging_snapshot JSONB;
CREATE TABLE occasion_packaging (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 branch_id BIGINT NOT NULL REFERENCES branches(id),
 name VARCHAR(100) NOT NULL, image_url VARCHAR(1000),
 dimensions VARCHAR(100) NOT NULL, material VARCHAR(100) NOT NULL,
 compartments INTEGER NOT NULL CHECK (compartments BETWEEN 1 AND 100),
 capacity_pieces INTEGER NOT NULL CHECK (capacity_pieces BETWEEN 1 AND 1000),
 price NUMERIC(12,2) CHECK (price >= 0), branding VARCHAR(300) NOT NULL DEFAULT '',
 lead_days INTEGER NOT NULL DEFAULT 0 CHECK (lead_days BETWEEN 0 AND 365),
 published BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX occasion_packaging_branch ON occasion_packaging(branch_id, published);
CREATE INDEX customer_notifications_target ON customer_notification_events(environment, subject_id, target_type, target_id, id DESC);
CREATE INDEX staff_alerts_order ON staff_order_alerts(environment, order_id, id DESC);
