"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import {useAdminAuth} from "@/contexts/AdminAuthContext";
import {apiClient} from "@/services/apiClient";
import {adminFetch} from "@/services/adminApi";
import {getAdminBranchMenu} from "@/services/adminMenuApi";
import {preferredAdminBranchId,rememberAdminBranchId} from "@/lib/adminBranchSelection";
import type {AdminBranchProduct} from "@/types/adminMenu";
import type {PortionGroup} from "@/lib/mobileMenu";
type Snapshot={version:number;groups:PortionGroup[]};
const money=(value:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(value);
export default function ProductGroupsPage(){
 const {profile,authorization,hasPermission}=useAdminAuth();
 const [branches,setBranches]=useState<{id:number;name:string}[]>([]),[branchId,setBranchId]=useState<number|null>(null);
 const [snapshot,setSnapshot]=useState<Snapshot|null>(null),[products,setProducts]=useState<AdminBranchProduct[]>([]);
 const [error,setError]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[revision,setRevision]=useState(0);
 const [searches,setSearches]=useState<Record<string,string>>({});
 const allowed=hasPermission("MENU_MANAGE");
 useEffect(()=>{if(!profile||!allowed)return;const controller=new AbortController();void apiClient<{id:number;name:string;active:boolean}[]>("/api/branches",{signal:controller.signal}).then(all=>{if(controller.signal.aborted)return;const values=all.filter(b=>b.active&&(profile.roleName==="OWNER_ADMIN"||profile.branchIds.includes(b.id)));setBranches(values);setBranchId(preferredAdminBranchId(profile.staffId,values));}).catch(()=>{if(!controller.signal.aborted)setError("Unable to load branches.");});return()=>controller.abort();},[profile,allowed]);
 useEffect(()=>{if(!branchId||!authorization||!allowed)return;const controller=new AbortController();
  void (async()=>{try{const [response,menu]=await Promise.all([adminFetch(`/api/admin/branches/${branchId}/menu/portion-groups`,authorization,{signal:controller.signal}),getAdminBranchMenu(branchId,authorization,controller.signal)]);if(!response.ok)throw new Error("Unable to load product groups for this branch.");const value:Snapshot=await response.json();if(!controller.signal.aborted){setSnapshot(value);setProducts(menu);}}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:"Unable to load groups.");}})();return()=>controller.abort();
 },[branchId,authorization,allowed,revision]);
 function update(index:number,group:PortionGroup){setSnapshot(value=>value?{...value,groups:value.groups.map((g,i)=>i===index?group:g)}:null);setNotice("");}
 async function save(){if(!snapshot||!branchId||!authorization||busy)return;
  for(const g of snapshot.groups){if(!g.title.trim()||g.choices.length<2||g.choices.some(c=>!c.label.trim())){setError("Give every group a name, at least two products, and a clear label for each option.");return;}}
  setBusy(true);setError("");setNotice("");try{const response=await adminFetch(`/api/admin/branches/${branchId}/menu/portion-groups`,authorization,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(snapshot)});if(!response.ok){const value=await response.json().catch(()=>({}));throw new Error(response.status===409?"Another staff member changed these groups. Reload before saving.":value.message??"Use 2–6 distinct products sold by count, from the same category and branch.");}setSnapshot(await response.json());setNotice("Product groups saved. Customers see one mobile card; prices and stock remain separate for each option.");}catch(e){setError(e instanceof Error?e.message:"Unable to save groups.");}finally{setBusy(false);}}
 if(!profile)return <p className="p-6">Sign in to manage product groups.</p>;
 if(!allowed)return <p className="p-6">Menu management permission is required.</p>;
 const used=new Set(snapshot?.groups.flatMap(g=>g.choices.map(c=>c.productId))??[]);
 return <main className="mx-auto w-full min-w-0 max-w-6xl p-5 text-slate-800"><Link href="/admin/menu" className="text-sm underline">← Menu management</Link>
  <div className="my-6 flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-bold">Product groups</h1><p className="mt-2 text-slate-600">Show pack sizes, flavours, or Half / Full portions in one mobile menu card.</p></div><button type="button" disabled={!snapshot||busy||snapshot.groups.length>=40} onClick={()=>setSnapshot(value=>value?{...value,groups:[...value.groups,{key:crypto.randomUUID(),title:"",choices:[]}]}:null)} className="rounded-xl bg-[#8f1838] px-5 py-3 font-semibold text-white disabled:opacity-50">+ Create group</button></div>
  <div className="mb-6 flex flex-wrap items-center justify-between gap-4 rounded-xl border bg-white p-4"><label>Branch <select className="ml-3 rounded-lg border p-2" value={branchId??""} disabled={busy} onChange={e=>{const id=Number(e.target.value);setSnapshot(null);setProducts([]);setSearches({});setError("");setNotice("");setBranchId(id);rememberAdminBranchId(profile.staffId,id);}}>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><button type="button" className="underline" disabled={busy} onClick={()=>{setSnapshot(null);setError("");setNotice("");setRevision(v=>v+1);}}>Reload saved groups</button></div>
  <p className="mb-5 rounded-xl bg-blue-50 p-4 text-sm">Each option keeps its own price, stock, tax, service hours, and branch availability. Grouping does not merge inventory. Use products sold by count for sealed packs; loose-weight sweets retain their weight picker.</p>
  {error&&<p role="alert" className="mb-4 rounded-xl bg-red-50 p-4 text-red-800">{error}</p>}{notice&&<p role="status" className="mb-4 rounded-xl bg-green-50 p-4 text-green-900">{notice}</p>}
  {!snapshot&&!error&&<p role="status">Loading product groups…</p>}
  {snapshot&&<><fieldset disabled={busy}>{!snapshot.groups.length&&<div className="rounded-2xl border border-dashed p-10 text-center"><h2 className="text-xl font-semibold">Start with one product family</h2><p className="mt-2 text-slate-600">For example: Dahi 200 g, 400 g, 1 kg and 5 kg. Create a group, select those existing products, and label their sizes.</p></div>}
   {snapshot.groups.map((group,index)=>{
    const linked=group.choices.flatMap(c=>products.filter(p=>p.productId===c.productId));
    const category=linked[0]?.categoryId;
    const query=(searches[group.key]??"").trim().toLowerCase();
    const candidates=products.filter(p=>!used.has(p.productId)&&(category===undefined||p.categoryId===category)&&(!query||`${p.productName} ${p.productCode}`.toLowerCase().includes(query)));
    function move(from:number,to:number){const choices=[...group.choices];[choices[from],choices[to]]=[choices[to],choices[from]];update(index,{...group,choices});}
    return <section key={group.key} className="my-5 rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-bold">{group.title||"New product group"}</h2><button type="button" className="text-sm text-red-800 underline" onClick={()=>setSnapshot({...snapshot,groups:snapshot.groups.filter((_,i)=>i!==index)})}>Ungroup products</button></div>
     <div className="mt-5 grid min-w-0 grid-cols-[minmax(0,1fr)] gap-5 lg:grid-cols-[minmax(0,1fr)_240px]"><div className="min-w-0"><label className="block text-sm font-semibold">Customer-facing name<input className="mt-2 w-full rounded-lg border p-3 font-normal" maxLength={100} placeholder="e.g. Dahi" value={group.title} onChange={e=>update(index,{...group,title:e.target.value})}/></label><p className="my-3 text-sm text-slate-500">{linked[0]?`Category: ${linked[0].categoryName}`:"Select products from the same category."}</p>
      <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="bg-slate-50"><th className="p-3">Existing product</th><th className="p-3">Option label</th><th className="p-3">Order</th><th className="p-3"><span className="sr-only">Remove</span></th></tr></thead><tbody>{group.choices.map((choice,i)=>{const product=products.find(p=>p.productId===choice.productId);return <tr key={choice.productId} className="border-t"><td className="p-3">{product?.productName??"Product no longer in branch menu"}<small className="block text-slate-500">{product?money(product.effectivePrice):"Review this option"}</small></td><td className="p-3"><input aria-label={`Option label for ${product?.productName??choice.productId}`} className="w-full min-w-24 rounded-lg border p-2" maxLength={30} value={choice.label} onChange={e=>update(index,{...group,choices:group.choices.map((c,j)=>j===i?{...c,label:e.target.value}:c)})}/></td><td className="whitespace-nowrap p-2"><button type="button" aria-label={`Move ${product?.productName} up`} disabled={i===0} onClick={()=>move(i,i-1)} className="min-h-10 min-w-10 rounded border disabled:opacity-30">↑</button> <button type="button" aria-label={`Move ${product?.productName} down`} disabled={i===group.choices.length-1} onClick={()=>move(i,i+1)} className="min-h-10 min-w-10 rounded border disabled:opacity-30">↓</button></td><td><button type="button" aria-label={`Ungroup ${product?.productName}`} className="min-h-10 min-w-10 text-red-800" onClick={()=>update(index,{...group,choices:group.choices.filter((_,j)=>j!==i)})}>×</button></td></tr>;})}</tbody></table></div>
      <label className="mt-5 block text-sm font-semibold">Add existing products<input type="search" className="mt-2 w-full rounded-lg border p-3 font-normal" placeholder="Search by name or product code" value={searches[group.key]??""} onChange={e=>setSearches({...searches,[group.key]:e.target.value})}/></label>
      <div className="mt-2 max-h-52 overflow-y-auto rounded-lg border">{candidates.slice(0,30).map(p=><button type="button" key={p.productId} disabled={group.choices.length>=6} onClick={()=>update(index,{...group,choices:[...group.choices,{productId:p.productId,label:p.productName.slice(0,30)}]})} className="flex w-full items-center justify-between gap-3 border-b p-3 text-left text-sm hover:bg-green-50 disabled:opacity-40"><span>{p.productName}<small className="block text-slate-500">{p.categoryName} · {money(p.effectivePrice)}</small></span><span className="font-semibold text-green-800">+ Add</span></button>)}{!candidates.length&&<p className="p-3 text-sm text-slate-500">No matching ungrouped products in this category.</p>}</div><p className="mt-2 text-xs text-slate-500">2–6 options per group. Edit labels to “200 g pack”, “Half plate”, or your actual selling size.</p>
     </div><aside className="h-fit rounded-xl bg-[#f7f2fa] p-4"><h3 className="text-sm font-semibold">Menu preview</h3><div className="mt-3 rounded-xl border bg-white p-4"><strong>{group.title||"Product name"}</strong><p className="my-2 text-sm">{linked.length?`From ${money(Math.min(...linked.map(p=>p.effectivePrice)))}`:"Select products below"}</p><p className="text-xs text-slate-500">{group.choices.map(c=>c.label).filter(Boolean).join(" · ")||"Your options appear here"}</p><span className="mt-4 block rounded-lg border border-green-700 p-2 text-center text-sm font-bold text-green-700">Choose options</span></div><p className="mt-3 text-xs text-slate-500">Removing a group or option only changes the presentation. Existing products remain in the catalogue.</p></aside></div>
    </section>;
   })}</fieldset><div className="sticky bottom-0 mt-6 flex flex-wrap items-center gap-4 rounded-xl border bg-white p-4 shadow-sm"><button type="button" disabled={busy} onClick={()=>void save()} className="rounded-xl bg-[#8f1838] px-6 py-3 font-semibold text-white disabled:opacity-50">{busy?"Saving…":"Save product groups"}</button><Link href="/admin/menu/live" className="text-sm underline">Edit prices and availability</Link></div></>}
 </main>;
}
