"use client";
import {T} from "@/lib/language";

import {useEffect,useState,type FormEvent} from "react";
import {useAdminAuth} from "@/contexts/AdminAuthContext";
import {brandAdmin} from "@/services/brandCareersApi";
import {getActiveBranches} from "@/services/branchApi";
import type {Branch} from "@/types/branch";
import type {CareerJob,Applicant,ApplicantPage,ApplicantStatus} from "@/types/brandCareers";
import s from "@/components/brand/Workspace.module.css";
const statuses:ApplicantStatus[]=["NEW","REVIEWING","SHORTLISTED","INTERVIEW","HIRED","REJECTED"];
function JobEditor({job,branches,onSaved,onClose}:{job?:CareerJob;branches:Branch[];onSaved:()=>void;onClose:()=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState("");
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await brandAdmin(job?`/api/admin/careers/jobs/${job.id}`:"/api/admin/careers/jobs",job?"PUT":"POST",{branchId:job?.branchId??Number(f.get("branchId")),title:f.get("title"),department:f.get("department"),requirements:f.get("requirements"),minimumExperience:Number(f.get("minimumExperience")),active:f.get("active")==="on"},job?.version);onSaved();onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className={s.panel}><h2>{job?`Edit ${job.title}`:"Create opening"}</h2><form onSubmit={save}><fieldset disabled={busy}><div className={s.grid}><label className={s.field}><T text="Branch" /><select name="branchId" defaultValue={job?.branchId??""} required disabled={!!job}><option value="">Choose branch</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><span className={s.help}>Create a separate opening for each branch.</span></label><label className={s.field}>Role title<input name="title" maxLength={120} required defaultValue={job?.title}/></label><label className={s.field}>Department<input name="department" maxLength={80} required defaultValue={job?.department}/></label><label className={s.field}>Preferred experience (years)<input name="minimumExperience" type="number" min="0" max="60" step="0.1" required defaultValue={job?.minimumExperience??0}/></label></div><label className={s.field}>Requirements<textarea name="requirements" maxLength={3000} required defaultValue={job?.requirements}/><span className={s.help}>Describe duties, skills, qualifications and experience preferences clearly.</span></label><label className={s.check}><input name="active" type="checkbox" defaultChecked={job?.active}/>Active — publish and accept applications</label><p className={s.help}>Closing removes the opening from public listings and rejects new applications. Existing applications stay available.</p><div className={s.actions}><button className={s.primary}>{busy?"Saving…":"Save opening"}</button><button type="button" onClick={onClose}>Close editor</button></div></fieldset></form>{error&&<p role="alert" className={s.message}>{error}</p>}</section>;
}
function ApplicantDetails({applicant,onSaved,onClose}:{applicant:Applicant;onSaved:()=>void;onClose:()=>void}){
 const [status,setStatus]=useState(applicant.status),[notes,setNotes]=useState(applicant.staffNotes),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function save(e:FormEvent){e.preventDefault();setBusy(true);try{await brandAdmin(`/api/admin/careers/applications/${applicant.id}`,"PUT",{status,staffNotes:notes},applicant.version);onSaved();onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className={`${s.panel} ${s.details}`} aria-label="Applicant details"><div className={s.actions}><h2>{applicant.name}</h2><button onClick={onClose} disabled={busy}>Close details</button></div><p className={s.help}>{applicant.branchName} · {applicant.jobTitle} · {applicant.experience} years</p><p><a href={`tel:${applicant.phone}`}>{applicant.phone}</a>{applicant.email&&<> · <a href={`mailto:${applicant.email}`}>{applicant.email}</a></>}</p><p className={s.help}>Preferred role: {applicant.desiredRole}</p><h3>Qualifications & experience</h3><p className={s.copy}>{applicant.qualifications}</p><form onSubmit={save}><label className={s.field}>Application status<select value={status} disabled={busy} onChange={e=>setStatus(e.target.value as ApplicantStatus)}>{statuses.map(st=><option key={st}>{st}</option>)}</select></label><label className={s.field}>Private staff notes<textarea value={notes} maxLength={3000} disabled={busy} onChange={e=>setNotes(e.target.value)}/><span className={s.help}>Visible only to authorised recruitment staff. Record relevant hiring observations.</span></label><button className={s.primary} disabled={busy}>{busy?"Saving…":"Save review"}</button></form>{error&&<p role="alert" className={s.message}>{error}</p>}</section>;
}
export default function Recruitment(){
 const {profile,hasPermission}=useAdminAuth();const allowed=hasPermission("CAREERS_MANAGE");
 const [tab,setTab]=useState("applications"),[jobs,setJobs]=useState<CareerJob[]>([]),[branches,setBranches]=useState<Branch[]>([]),[result,setResult]=useState<ApplicantPage|null>(null);
 const [filters,setFilters]=useState({branchId:"",jobId:"",status:"",search:"",minExperience:"",maxExperience:""}),[applied,setApplied]=useState(filters),[page,setPage]=useState(0),[revision,setRevision]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const [selected,setSelected]=useState<Applicant|null>(null),[editing,setEditing]=useState<CareerJob|null|undefined>(undefined);
 useEffect(()=>{if(!allowed)return;const c=new AbortController();Promise.all([brandAdmin<CareerJob[]>("/api/admin/careers/jobs","GET",undefined,undefined,c.signal),getActiveBranches(c.signal)]).then(([j,b])=>{setJobs(j);setBranches(b.filter(branch=>profile?.roleName==="OWNER_ADMIN"||profile?.branchIds.includes(branch.id)));}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[allowed,profile,revision]);
 useEffect(()=>{if(!allowed)return;const c=new AbortController();const params=new URLSearchParams({page:String(page),size:"25"});Object.entries(applied).forEach(([k,v])=>{if(v)params.set(k,v);});brandAdmin<ApplicantPage>(`/api/admin/careers/applications?${params}`,"GET",undefined,undefined,c.signal).then(setResult).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[allowed,applied,page,revision]);
 function reload(){setError("");setLoading(true);setSelected(null);setRevision(v=>v+1);}
 if(!allowed)return <p>Recruitment management permission is required.</p>;
 return <div className={s.workspace}><header className={s.header}><h1>Recruitment workspace</h1><p>Private applications and branch openings. Access and changes are audited.</p><div className={s.actions}><button onClick={()=>setTab("applications")} aria-pressed={tab==="applications"}>Applicants</button><button onClick={()=>setTab("jobs")} aria-pressed={tab==="jobs"}>Job openings</button><button onClick={reload}>Reload</button></div></header>{error&&<p role="alert" className={s.message}>{error}</p>}
 {tab==="jobs"?<><button className={s.primary} onClick={()=>setEditing(null)}>Create opening</button>{editing!==undefined&&<JobEditor key={editing?.id??"new"} job={editing??undefined} branches={branches} onSaved={reload} onClose={()=>setEditing(undefined)}/>}<div className={s.jobs}>{jobs.map(j=><article key={j.id} className={s.panel}><p className={s.badge}>{j.branchName} · {j.active?"Active":"Closed"}</p><h2>{j.title}</h2><p>{j.department} · {j.minimumExperience} years preferred</p><p className={s.copy}>{j.requirements}</p><button onClick={()=>setEditing(j)}>Manage opening</button></article>)}</div>{!jobs.length&&<p className={s.panel}>No openings yet. Create a branch role to begin.</p>}</>:<>
 <form className={s.panel} onSubmit={e=>{e.preventDefault();setPage(0);setLoading(true);setSelected(null);setError("");setApplied({...filters});}}><div className={s.filters}><label className={s.field}><T text="Branch" /><select value={filters.branchId} onChange={e=>setFilters({...filters,branchId:e.target.value,jobId:""})}><option value="">All accessible branches</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label className={s.field}>Opening<select value={filters.jobId} onChange={e=>setFilters({...filters,jobId:e.target.value})}><option value="">All roles</option>{jobs.filter(j=>!filters.branchId||j.branchId===Number(filters.branchId)).map(j=><option key={j.id} value={j.id}>{j.title} · {j.branchName}</option>)}</select></label><label className={s.field}>Status<select value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value})}><option value="">All statuses</option>{statuses.map(st=><option key={st}>{st}</option>)}</select></label><label className={s.field}>Search name, role or qualifications<input maxLength={100} value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/></label><label className={s.field}>Minimum years<input type="number" min="0" max="60" step="0.1" value={filters.minExperience} onChange={e=>setFilters({...filters,minExperience:e.target.value})}/></label><label className={s.field}>Maximum years<input type="number" min="0" max="60" step="0.1" value={filters.maxExperience} onChange={e=>setFilters({...filters,maxExperience:e.target.value})}/></label></div><button className={s.primary}>Apply filters</button></form>
 {selected&&<ApplicantDetails key={`${selected.id}-${selected.version}`} applicant={selected} onSaved={reload} onClose={()=>setSelected(null)}/>}
 {loading?<p role="status" className={s.panel}>Loading applicants…</p>:result&&<><p>{result.total} matching applications</p><div className={s.counts}>{statuses.map(st=><span key={st}>{st}: {result.counts[st]??0}</span>)}</div><p className={s.help}>Status counts reflect branch, opening, search and experience filters.</p><div className={`${s.panel} ${s.table}`}><table><thead><tr><th>Applicant</th><th>Role / branch</th><th>Experience</th><th>Status</th><th><T text="Review" /></th></tr></thead><tbody>{result.items.map(a=><tr key={a.id}><td>{a.name}<p className={s.help}>{new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeZone:"Asia/Kolkata"}).format(new Date(a.createdAt))}</p></td><td>{a.jobTitle}<p className={s.help}>{a.branchName}</p></td><td>{a.experience} years</td><td>{a.status}</td><td><button onClick={()=>{setError("");void brandAdmin<Applicant>(`/api/admin/careers/applications/${a.id}`).then(setSelected).catch(e=>setError(e.message));}}>View details</button></td></tr>)}</tbody></table>{!result.items.length&&<p className={s.help}>No applicants match these filters.</p>}</div><div className={s.actions}><button disabled={page===0} onClick={()=>{setLoading(true);setSelected(null);setPage(p=>p-1);}}><T text="Previous" /></button><span><T text="Page" />{" "}{page+1}</span><button disabled={(page+1)*25>=result.total} onClick={()=>{setLoading(true);setSelected(null);setPage(p=>p+1);}}><T text="Next" /></button></div></>}
 </>}</div>;
}
