"use client";
import Image from "next/image";
import {useCallback,useEffect,useState,type FormEvent} from "react";
import {useAdminAuth} from "@/contexts/AdminAuthContext";
import {brandAdmin} from "@/services/brandCareersApi";
import type {BrandContent,BrandPerson,BrandStory,PersonSection} from "@/types/brandCareers";
import s from "@/components/brand/Workspace.module.css";
function PhotoEditor({url,path,version,onSaved,disabled}:{url:string|null;path:string;version:number;onSaved:()=>void;disabled:boolean}) {
    const [file,setFile]=useState<File|null>(null),[preview,setPreview]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
    useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview);},[preview]);
    async function save(remove=false){setBusy(true);setError("");try{const form=new FormData();if(file)form.append("file",file);await brandAdmin(path,remove?"DELETE":"POST",remove?undefined:form,version);setFile(null);setPreview(null);onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
    return <div>{(preview||url)&&<Image unoptimized width={180} height={180} src={preview||url!} alt="Photo preview" className={s.photo}/>}<label className={s.field}>Photo upload<input type="file" accept="image/jpeg,image/png,image/webp" disabled={disabled||busy} onChange={e=>{const chosen=e.target.files?.[0]??null;setFile(chosen);setPreview(chosen?URL.createObjectURL(chosen):null);}}/><span className={s.help}>Use an authorised, real photo. Selecting a file previews it; upload saves the replacement. Published profiles show the saved photo.</span></label><div className={s.actions}><button type="button" disabled={!file||disabled||busy} onClick={()=>void save()}>Upload photo</button>{url&&<button type="button" disabled={disabled||busy} onClick={()=>void save(true)}>Remove saved photo</button>}</div>{error&&<p role="alert" className={s.message}>{error}</p>}</div>;
}
function PersonEditor({person,onSaved}:{person?:BrandPerson;onSaved:()=>void}){
    const [section,setSection]=useState<PersonSection>(person?.section??"TEAM"),[busy,setBusy]=useState(false),[error,setError]=useState("");
    async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await brandAdmin(person?`/api/admin/about/people/${person.id}`:"/api/admin/about/people",person?"PUT":"POST",{section,name:f.get("name"),role:f.get("role"),bio:f.get("bio"),displayOrder:Number(f.get("displayOrder")),published:f.get("published")==="on"},person?.version);onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
    return <article className={s.panel}><h2>{person?.name??"Add a profile"}</h2><form onSubmit={save}><fieldset disabled={busy}><div className={s.grid}><label className={s.field}>Section<select value={section} onChange={e=>setSection(e.target.value as PersonSection)}><option value="FOUNDER">Founders</option><option value="TEAM">Coworkers / team</option><option value="DEVELOPER">Developers</option></select></label><label className={s.field}>Display order<input name="displayOrder" type="number" min="0" max="10000" defaultValue={person?.displayOrder??0}/><span className={s.help}>Smaller numbers appear first within this section.</span></label><label className={s.field}>Name<input name="name" required maxLength={100} defaultValue={person?.name}/></label><label className={s.field}>Role<input name="role" required maxLength={120} defaultValue={person?.role}/></label></div><label className={s.field}>Biography<textarea name="bio" maxLength={1500} defaultValue={person?.bio}/><span className={s.help}>Use verified details with this person’s permission. Leave unknown credentials out.</span></label><label className={s.check}><input name="published" type="checkbox" defaultChecked={person?.published}/>Publish this profile on About</label><button className={s.primary}>{busy?"Saving…":"Save profile"}</button></fieldset></form>{person&&<PhotoEditor url={person.photoUrl} path={`/api/admin/about/people/${person.id}/photo`} version={person.version} onSaved={onSaved} disabled={busy}/>} {error&&<p role="alert" className={s.message}>{error}</p>}</article>;
}
function StoryEditor({story,onSaved}:{story:BrandStory;onSaved:()=>void}){
    const [busy,setBusy]=useState(false),[error,setError]=useState("");
    async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await brandAdmin("/api/admin/about","PUT",{title:f.get("title"),subtitle:f.get("subtitle"),storyTitle:f.get("storyTitle"),storyBody:f.get("storyBody"),published:f.get("published")==="on"},story.version);onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
    return <section className={s.panel}><h2>Brand story</h2><p className={s.help}>Draft content stays private. Publish only verified text and authorised images. Saving uses the loaded version; conflicting edits must be reloaded.</p><form onSubmit={save}><fieldset disabled={busy}><label className={s.field}>Headline<input name="title" required maxLength={120} defaultValue={story.title}/></label><label className={s.field}>Introduction<textarea name="subtitle" required maxLength={400} defaultValue={story.subtitle}/></label><label className={s.field}>Story heading<input name="storyTitle" required maxLength={120} defaultValue={story.storyTitle}/></label><label className={s.field}>Story<textarea name="storyBody" required maxLength={6000} defaultValue={story.storyBody}/></label><label className={s.check}><input name="published" type="checkbox" defaultChecked={story.published}/>Publish the brand story</label><button className={s.primary}>{busy?"Saving…":"Save story"}</button></fieldset></form><PhotoEditor url={story.imageUrl} path="/api/admin/about/photo" version={story.version} onSaved={onSaved} disabled={busy}/>{error&&<p role="alert" className={s.message}>{error}</p>}</section>;
}
export default function AboutAdmin(){
    const {hasPermission}=useAdminAuth();const allowed=hasPermission("ABOUT_MANAGE");
    const [content,setContent]=useState<BrandContent|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0);
    const reload=useCallback(()=>{setLoading(true);setRevision(v=>v+1);},[]);
    useEffect(()=>{if(!allowed)return;const c=new AbortController();brandAdmin<BrandContent>("/api/admin/about","GET",undefined,undefined,c.signal).then(setContent).catch(e=>{if(!c.signal.aborted)setError(e.message);}).finally(()=>{if(!c.signal.aborted)setLoading(false);});return()=>c.abort();},[allowed,revision]);
    if(!allowed)return <p>About management permission is required.</p>;
    return <div className={s.workspace}><header className={s.header}><h1>About & people</h1><p>Manage the public story, founders, coworkers and developers.</p><button onClick={()=>{setError("");reload();}}>Reload saved content</button></header>{error&&<p role="alert" className={s.message}>{error}</p>}{loading?<p role="status">Loading content…</p>:content&&<>{content.story&&<StoryEditor key={`story-${content.story.version}`} story={content.story} onSaved={reload}/>} {content.people.map(p=><PersonEditor key={`${p.id}-${p.version}`} person={p} onSaved={reload}/>)}<PersonEditor key={`new-${revision}`} onSaved={reload}/></>}</div>;
}
