const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript'),test=require('node:test');
function load(file,mocks={},globals={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(`${__dirname}/../${file}`,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:name=>{assert.ok(name in mocks,`Unexpected import ${name}`);return mocks[name];},AbortSignal,Error,JSON,...globals});return exports;}
for(const changed of ['cart','branch','pickup','customer','pending',null])test(`add-on quote ${changed?'rejects changed '+changed:'accepts unchanged checkout'}`,async()=>{
 const state={cart:'cart A',branch:'branch A',pickup:'pickup A',customer:'customer A',pending:'order A'};let resolve;const response=new Promise(r=>resolve=r),quote={token:'original quote'};
 const {refreshCurrentCheckoutQuote}=load('lib/checkoutQuoteRefresh.ts',{'./cartStorage':{getCartSnapshot:()=>state.cart},'./branchStorage':{getStoredBranchSnapshot:()=>state.branch},'./checkoutStorage':{getCustomerSnapshot:()=>state.customer,getPickupSlotSnapshot:()=>state.pickup},'./pendingOrderStorage':{getPendingOrderSnapshot:()=>state.pending},'@/services/orderApi':{previewCheckoutQuote:()=>response}});
 const pending=refreshCurrentCheckoutQuote({},undefined,new AbortController().signal);if(changed)state[changed]='changed';resolve(quote);assert.equal(await pending,changed?null:quote);
});
class ApiError extends Error{constructor(status){super('API failure');this.status=status;}}
const {CheckoutSavingsUncertainError}=load('lib/checkoutRefresh.ts');
for(const operation of ['applyRebate','applyBestRebate','removeRebate','getAvailableRebates'])test(`${operation} supplies a request deadline`,async()=>{
 let options;const api=load('services/rebateApi.ts',{'@/lib/checkoutRefresh':{CheckoutSavingsUncertainError},'@/services/apiClient':{ApiError,apiClient:async(_,value)=>{options=value;return {};}}});await api[operation](...operation==='applyRebate'?['ORDER','SAVE']:['ORDER']);assert.ok(options.signal);assert.equal(options.signal.aborted,false);
});
for(const failure of [new ApiError(0),new ApiError(503),new Error('Connection closed')])test(`uncertain offer write requires recovery (${failure.status??'network'})`,async()=>{
 const api=load('services/rebateApi.ts',{'@/lib/checkoutRefresh':{CheckoutSavingsUncertainError},'@/services/apiClient':{ApiError,apiClient:async()=>{throw failure;}}});await assert.rejects(api.applyRebate('ORDER','SAVE'),CheckoutSavingsUncertainError);
});
test('definitive rejected offer preserves the server error',async()=>{const failure=new ApiError(409),api=load('services/rebateApi.ts',{'@/lib/checkoutRefresh':{CheckoutSavingsUncertainError},'@/services/apiClient':{ApiError,apiClient:async()=>{throw failure;}}});await assert.rejects(api.applyRebate('ORDER','SAVE'),error=>error===failure);});
test('caller cancellation stops an offer write and requires recovery',async()=>{const signal=AbortSignal.abort(),api=load('services/rebateApi.ts',{'@/lib/checkoutRefresh':{CheckoutSavingsUncertainError},'@/services/apiClient':{ApiError,apiClient:async(_,options)=>{assert.equal(options.signal,signal);throw new Error('aborted');}}});await assert.rejects(api.removeRebate('ORDER',signal),CheckoutSavingsUncertainError);});
test('reservation recovery and price review requirements survive storage reload',()=>{const {parsePendingOrder}=load('lib/pendingOrderStorage.ts');const saved={orderId:1,orderNumber:'ORDER',orderStatus:'PENDING_PAYMENT',branchId:1,pickupSlotId:1,totalAmount:80,reservationExpiresAt:'2027-01-01',createdAt:'2026-01-01',cartFingerprint:'cart',offerRecheckRequired:true,priceReviewRequired:true};assert.equal(parsePendingOrder(JSON.stringify(saved)).offerRecheckRequired,true);assert.equal(parsePendingOrder(JSON.stringify(saved)).priceReviewRequired,true);const cleared=parsePendingOrder(JSON.stringify({...saved,offerRecheckRequired:false,priceReviewRequired:false}));assert.equal(cleared.offerRecheckRequired,undefined);assert.equal(cleared.priceReviewRequired,undefined);});
