import assert from "node:assert/strict";
import {createRequire} from "node:module";
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE??"playwright");
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:390,height:844}});
let authenticated=true, submitted=null, requests=0, expireNext=false;const history=[];
const branch={id:1,code:"TEST",name:"Celebration branch",active:true,pickupAvailable:true};
const sweets=[{id:1,name:"Kaju Barfi",description:"Made fresh for your celebration",saleMode:"WEIGHT",occasionOnly:true,published:true,leadDays:3,pieceGrams:null,categoryName:"Sweets"},{id:2,name:"Peda",saleMode:"UNIT",occasionOnly:false,published:true,leadDays:1,pieceGrams:null,categoryName:"Sweets"},{id:3,name:"Laddoo",saleMode:"UNIT",occasionOnly:false,published:true,leadDays:1,pieceGrams:null,categoryName:"Sweets"}];
sweets.push({id:4,name:"Paneer",saleMode:"WEIGHT",occasionOnly:false,published:true,leadDays:2,categoryName:"Paneer"});
const box={id:8,name:"Celebration eight",dimensions:"18 × 12 × 4 cm",material:"Food-safe cardboard",compartments:3,capacityPieces:8,price:10,branding:"Ribbon and gift message",leadDays:3,published:true,imageUrl:null,imageUrls:["https://images.example.invalid/box-front.jpg","https://images.example.invalid/box-inside.jpg"]};
sweets.push({id:5,name:"Gulab Jamun",saleMode:"WEIGHT",occasionOnly:false,published:true,leadDays:1,categoryName:"Sweets",pieceGrams:20});
for(const sweet of sweets){sweet.unitPrice=100;sweet.taxPercent=5;}
const weightBoxes=[1000,500,250].map((grams,index)=>({...box,id:9+index,name:`${grams} g sweet box`,capacityGrams:grams,price:12}));
await context.addInitScript(branch=>localStorage.setItem("gokul-selected-branch",JSON.stringify(branch)),branch);
await context.route("**/api/**",async route=>{
 const request=route.request(),path=new URL(request.url()).pathname;
 let json=[];
 if(path==="/api/storefront/features")json={occasionEnquiries:true,occasionPayments:true,futuristicStorefrontV2:true,today:"2026-09-30"};
 else if(path==="/api/storefront/customer-identity")json={enabled:true};
 else if(path==="/api/customer/identity/me")json={authenticated,phone:"+919876543210",name:"Celebration customer"};
 else if(path==="/api/branches/1/occasion-catalogue")json={sweets,boxes:[box,...weightBoxes],branding:{headline:"Celebrate beautifully with Gokul",description:"A thoughtful selection for your guests",imageUrl:null,published:true}};
 else if(path==="/api/branches/1")json=branch;
 else if(path==="/api/branches")json=[branch];
 else if(path==="/api/occasion-enquiries"&&request.method()==="GET")json=history;
 else if(path==="/api/occasion-enquiries"&&request.method()==="POST") {
  if(expireNext) {authenticated=false;return route.fulfill({status:401,json:{message:"Session expired"}});}
  submitted=request.postDataJSON();requests++;json={...submitted,id:`request-${requests}`,status:"REQUESTED",nextStep:"The branch is reviewing your enquiry",paidAmount:0,branchId:1,pricedLines:[],items:submitted.items.map(item=>({...item,productName:sweets.find(p=>p.id===item.productId).name})),packingGroups:submitted.packingGroups.map((group,index)=>({...group,groupNumber:index+1,box:[box,...weightBoxes].find(box=>box.id===group.boxId),productName:sweets.find(p=>p.id===group.productId)?.name??null})),gift:submitted.gift?{box,boxCount:submitted.gift.boxCount,recipe:submitted.gift.recipe,packagingEstimate:7000,approvedPackagingTotal:null}:null};history.unshift(json);
 }
 await route.fulfill({json});
});
const page=await context.newPage(),base=process.env.BROWSER_BASE??"http://127.0.0.1:3311";
try {
 await page.goto(`${base}/occasions`);
 await page.getByLabel("Verified occasion contact").waitFor();
 assert.equal(await page.getByRole("button",{name:"Sign out",exact:true}).count(),0);
 await page.getByRole("heading",{name:"Celebrate beautifully with Gokul"}).waitFor();
 await page.getByRole("button",{name:/Date in India/}).click();
 assert.equal(await page.getByRole("button",{name:"Previous month"}).isDisabled(),true);
 await page.getByRole("button",{name:/10 October/}).click();
 await page.getByLabel("Kaju Barfi unit").selectOption("PIECE");
 await page.getByLabel("Kaju Barfi quantity").fill("1000");
 await page.evaluate(()=>document.fonts.ready);
 const [quantityBox,unitBox]=await page.evaluate(()=>["Kaju Barfi quantity","Kaju Barfi unit"].map(name=>{const element=document.querySelector(`[aria-label="${name}"]`),r=element.getBoundingClientRect();return {y:r.y,height:r.height};}));
 if(process.env.ALERT_SCREENSHOT_DIR)await page.locator(".occasion-product").first().screenshot({path:`${process.env.ALERT_SCREENSHOT_DIR}/quantity-alignment.png`});
 assert.ok(Math.abs(quantityBox.y-unitBox.y)<2);
 const categoryTops=await page.evaluate(()=>Array.from(document.querySelectorAll(".occasion-categories button")).map(button=>button.firstElementChild.getBoundingClientRect().top));
 assert.ok(Math.abs(categoryTops[0]-categoryTops[1])<2);assert.ok(Math.abs(quantityBox.height-unitBox.height)<2);
 if(process.env.ALERT_SCREENSHOT_DIR)await page.locator(".occasion-journey").screenshot({path:`${process.env.ALERT_SCREENSHOT_DIR}/occasion-mobile.png`});
 await page.getByRole("button",{name:/Paneer category/}).click();
 await page.getByLabel("Paneer quantity").fill("100");
 await page.getByRole("button",{name:/Sweets category/}).click();
 assert.equal(await page.getByLabel("Kaju Barfi quantity").inputValue(),"1000");
 await page.getByText("Review quantities & indicative costs",{exact:true}).click();
 await page.getByRole("button",{name:"Remove Paneer from occasion selection"}).click();
 await page.getByRole("button",{name:"Request a reviewed quote"}).click();
 await page.waitForURL("**/occasions/requests?enquiry=request-1");
 await page.getByText("The branch is reviewing your enquiry",{exact:true}).waitFor();
 assert.deepEqual(submitted.items,[{productId:1,quantity:1000,unit:"PIECE"}]);
 assert.equal(submitted.gift,null);
 assert.equal(await page.locator("#occasion-plan").count(),0);
 await page.getByRole("link",{name:"Plan another occasion"}).click();
 await page.getByLabel("Verified occasion contact").waitFor();
 await page.getByRole("button",{name:/Date in India/}).click();
 await page.getByRole("button",{name:/10 October/}).click();
 assert.equal(await page.getByRole("button",{name:"Add mixed-piece boxes"}).evaluate(node=>getComputedStyle(node).color),"rgb(255, 255, 255)");
 assert.equal(await page.getByRole("button",{name:"Add mixed-piece boxes"}).evaluate(node=>getComputedStyle(node).backgroundColor),"rgb(8, 127, 66)");
 await page.getByRole("button",{name:"Add mixed-piece boxes"}).click();
 await page.getByLabel("Group 1 box count").fill("700");
 for(const [id,name,qty]of [[1,"Kaju Barfi","4"],[2,"Peda","2"],[3,"Laddoo","2"]]){await page.getByLabel("Group 1 add mixed item").selectOption(String(id));await page.getByLabel(`Group 1 ${name} pieces per box`).fill(qty);}
 await page.getByText("See actual box photos",{exact:true}).click();
 assert.match(await page.getByRole("img",{name:"Celebration eight view 2"}).getAttribute("src"),/inside/);
 await page.getByText("2,800 pieces total",{exact:true}).waitFor();
 await page.getByRole("button",{name:"Request a reviewed quote"}).click();
 await page.waitForFunction(()=>document.querySelector('[id="occasion-request-2"]')!==null);
 assert.deepEqual(submitted.items,[{productId:1,quantity:2800,unit:"PIECE"},{productId:2,quantity:1400,unit:"PIECE"},{productId:3,quantity:1400,unit:"PIECE"}]);
 assert.equal(submitted.gift,null);assert.equal(submitted.packingGroups[0].boxCount,700);assert.equal(submitted.packingGroups[0].recipe.length,3);
 await page.getByRole("link",{name:"Plan another occasion"}).click();
 await page.getByLabel("Verified occasion contact").waitFor();
 await page.getByRole("button",{name:/Date in India/}).click();await page.getByRole("button",{name:/10 October/}).click();
 await page.getByRole("button",{name:/Paneer category/}).click();await page.getByLabel("Paneer quantity").fill("100");
 await page.getByRole("button",{name:"Add mixed-piece boxes"}).click();
 for(const id of [1,2,3])await page.getByLabel("Group 1 add mixed item").selectOption(String(id));
 for(const [n,size,kg]of [[2,"1000","10"],[3,"500","5"],[4,"250","5"]]){await page.getByRole("button",{name:"Add 1 kg / 500 g / 250 g packs"}).click();await page.getByLabel(`Group ${n} item`,{exact:true}).selectOption("5");await page.getByLabel(`Group ${n} pack size`).selectOption(size);await page.getByLabel(`Group ${n} total kg`).fill(kg);}
 await page.setViewportSize({width:1440,height:1000});
 assert.equal(await page.locator(".occasion-selection").evaluate(node=>getComputedStyle(node).position),"static");
 if(process.env.ALERT_SCREENSHOT_DIR)await page.screenshot({path:`${process.env.ALERT_SCREENSHOT_DIR}/packing-groups-desktop.png`,fullPage:true});
 await page.getByRole("button",{name:"Request a reviewed quote"}).click();await page.waitForURL("**/occasions/requests?enquiry=request-3");
 assert.deepEqual(submitted.items,[{productId:1,quantity:1000,unit:"PIECE"},{productId:2,quantity:1000,unit:"PIECE"},{productId:3,quantity:1000,unit:"PIECE"},{productId:4,quantity:100000,unit:"GRAM"},{productId:5,quantity:20000,unit:"GRAM"}]);
 assert.deepEqual(submitted.packingGroups.map(g=>g.boxCount),[1000,10,10,20]);
 await page.getByRole("heading",{name:"Packing plan · 4 groups"}).waitFor();
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.setViewportSize({width:1440,height:1000});
 if(process.env.ALERT_SCREENSHOT_DIR)await page.screenshot({path:`${process.env.ALERT_SCREENSHOT_DIR}/occasion-desktop.png`,fullPage:true});
 await page.getByRole("link",{name:"Plan another occasion"}).click();
 await page.getByLabel("Verified occasion contact").waitFor();
 await page.getByRole("button",{name:/Date in India/}).click();
 await page.getByRole("button",{name:/10 October/}).click();
 await page.getByLabel("Kaju Barfi quantity").fill("1250");expireNext=true;
 await page.getByRole("button",{name:"Request a reviewed quote"}).click();
 await page.getByText("Please verify your phone, then try again.",{exact:true}).waitFor();
 assert.equal(await page.getByLabel("Kaju Barfi quantity").inputValue(),"1250");
 await page.getByRole("button",{name:"Verify with SMS"}).waitFor();
 assert.equal(await page.getByLabel("Verified occasion contact").count(),0);
 authenticated=false;await page.reload();
 await page.getByLabel("Kaju Barfi quantity").waitFor();
 assert.equal(await page.getByRole("button",{name:"Request a reviewed quote"}).isDisabled(),true);
 assert.equal(await page.getByLabel("Verified occasion contact").count(),0);
 await page.goto(`${base}/branches/1`);await page.getByRole("navigation",{name:"Branch pages"}).getByRole("link",{name:"Occasions & gifting"}).waitFor();
 const tabs=await page.getByRole("navigation",{name:"Branch pages"}).innerText();
 assert.ok(tabs.indexOf("Occasions & gifting")<tabs.indexOf("Branch details"));
 console.log("PASS: compact verified identity, piece request, 700 mixed boxes, 1000 assortments plus paneer and three kg-pack splits, requested-unit payload, mobile layout, guest browsing and branch navigation.");
}catch(error){console.error(await page.locator("body").innerText());throw error;}finally{await browser.close();}
