package com.gokulsweets.restaurant.maintenance;

import org.junit.jupiter.api.*;
import org.junit.jupiter.api.condition.EnabledIfEnvironmentVariable;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.mock.env.MockEnvironment;
import org.springframework.web.server.ResponseStatusException;
import tools.jackson.databind.ObjectMapper;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.*;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicInteger;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.TransactionDefinition;
import org.springframework.transaction.TransactionStatus;
import org.springframework.transaction.TransactionSystemException;
import static org.assertj.core.api.Assertions.*;

/** Real PostgreSQL, isolated schema. Never reads or deletes application/live data. */
@EnabledIfEnvironmentVariable(named="DATABASE_URL",matches="jdbc:postgresql:.*")
class DataCleanupIntegrationTest {
    private JdbcTemplate jdbc,root;
    private DriverManagerDataSource dataSource;
    private DataCleanupService cleanup;
    private String schema;
    private final Instant now=Instant.parse("2026-10-09T00:00:00Z");
    @BeforeEach void setup() throws Exception {
        String url=System.getenv("DATABASE_URL"),username=System.getenv("DATABASE_USERNAME"),password=System.getenv("DATABASE_PASSWORD");
        root=new JdbcTemplate(new DriverManagerDataSource(url,username,password));
        schema="cleanup_test_"+UUID.randomUUID().toString().replace("-","");
        root.execute("CREATE SCHEMA "+schema);
        dataSource=new DriverManagerDataSource(url+(url.contains("?")?"&":"?")+"currentSchema="+schema,username,password);
        jdbc=new JdbcTemplate(dataSource);
        jdbc.execute("CREATE TABLE staff_users(id bigint PRIMARY KEY)");
        jdbc.execute("INSERT INTO staff_users VALUES (1)");
        jdbc.execute("CREATE TABLE orders(id bigint PRIMARY KEY,order_number text UNIQUE,order_status text,updated_at timestamp)");
        jdbc.execute("CREATE TABLE customer_notification_events(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,environment text,target_type text,target_id text,kind text,created_at timestamptz,read_at timestamptz)");
        jdbc.execute("CREATE TABLE customer_push_deliveries(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,event_id bigint REFERENCES customer_notification_events(id),state text,lease_until timestamptz)");
        jdbc.execute("CREATE TABLE staff_order_alerts(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,environment text,order_id bigint REFERENCES orders(id),kind text,created_at timestamptz,scheduled_at timestamp)");
        jdbc.execute("CREATE TABLE staff_alert_deliveries(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,event_id bigint REFERENCES staff_order_alerts(id),state text,lease_until timestamptz)");
        jdbc.execute("CREATE TABLE staff_order_alert_reads(event_id bigint REFERENCES staff_order_alerts(id),staff_id bigint REFERENCES staff_users(id),PRIMARY KEY(event_id,staff_id))");
        jdbc.execute(Files.readString(Path.of("src/main/resources/db/migration/V120__daily_data_cleanup.sql")));
        var env=new MockEnvironment().withProperty("gokul.environment-isolation.environment","DEV");
        cleanup=new DataCleanupService(jdbc,Clock.fixed(now,ZoneOffset.UTC),env,new ObjectMapper(),new DataSourceTransactionManager(dataSource));
        jdbc.update("INSERT INTO orders VALUES (1,'completed','PICKED_UP','2026-01-01'),(2,'active','PREPARING','2026-01-01'),(3,'recent','DELIVERED','2026-10-08')");
    }
    @AfterEach void tearDown() {if(root!=null && schema!=null)root.execute("DROP SCHEMA "+schema+" CASCADE");}
    private long customer(String env,String target,String kind,String read) {
        return jdbc.queryForObject("INSERT INTO customer_notification_events(environment,target_type,target_id,kind,created_at,read_at) VALUES (?,'ORDER',?,?,'2026-01-01',?::timestamptz) RETURNING id",Long.class,env,target,kind,read);
    }
    private long staff(String env,long order) {
        return jdbc.queryForObject("INSERT INTO staff_order_alerts(environment,order_id,kind,created_at,scheduled_at) VALUES (?,?,'PREPARATION_DUE','2026-01-01','2026-01-01') RETURNING id",Long.class,env,order);
    }
    private boolean exists(String table,long id) {return jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM "+table+" WHERE id=?)",Boolean.class,id);}
    @Test void deletesOnlyEligibleRoutineHistoryAndItsChildren() {
        long disposable=customer("DEV","completed","PREPARING","2026-01-01");
        jdbc.update("INSERT INTO customer_push_deliveries(event_id,state) VALUES (?,'ACCEPTED')",disposable);
        long unread=customer("DEV","completed","CONFIRMED",null);
        long refund=customer("DEV","completed","PAYMENT_REFUNDED","2026-01-01");
        long completion=customer("DEV","completed","PICKED_UP","2026-01-01");
        long active=customer("DEV","active","PREPARING","2026-01-01");
        long recent=customer("DEV","recent","PREPARING","2026-01-01");
        long otherEnv=customer("PROD","completed","PREPARING","2026-01-01");
        long readRecently=customer("DEV","completed","PREPARING","2026-10-08");
        long queued=customer("DEV","completed","PREPARING","2026-01-01");
        jdbc.update("INSERT INTO customer_push_deliveries(event_id,state) VALUES (?,'QUEUED')",queued);
        long alert=staff("DEV",1),activeAlert=staff("DEV",2),otherAlert=staff("PROD",1),leased=staff("DEV",1);
        jdbc.update("INSERT INTO staff_alert_deliveries(event_id,state) VALUES (?,'FAILED')",alert);
        jdbc.update("INSERT INTO staff_order_alert_reads VALUES (?,1)",alert);
        jdbc.update("INSERT INTO staff_alert_deliveries(event_id,state,lease_until) VALUES (?,'ACCEPTED','2026-10-10')",leased);
        assertThat(cleanup.preview().eligible()).containsEntry("customerNotifications",1L).containsEntry("staffAlerts",1L).containsEntry("staffReads",1L);
        assertThat(exists("customer_notification_events",disposable)).isTrue(); // preview is read-only
        var result=cleanup.run(1L,0L);
        assertThat(result.status()).isEqualTo("SUCCEEDED");
        assertThat(result.deleted()).containsEntry("customerNotifications",1L).containsEntry("customerDeliveries",1L).containsEntry("staffAlerts",1L).containsEntry("staffReads",1L).containsEntry("staffDeliveries",1L);
        assertThat(exists("customer_notification_events",disposable)).isFalse();
        for(long id:new long[]{unread,refund,completion,active,recent,otherEnv,readRecently,queued})assertThat(exists("customer_notification_events",id)).isTrue();
        for(long id:new long[]{activeAlert,otherAlert,leased})assertThat(exists("staff_order_alerts",id)).isTrue();
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM orders",Long.class)).isEqualTo(3L);
    }
    @Test void boundedBatchesAndManualRunWhenScheduleIsPaused() {
        cleanup.save(new DataCleanupService.Config(false,"04:30",90,0),1);
        jdbc.update("INSERT INTO customer_notification_events(environment,target_type,target_id,kind,created_at,read_at) SELECT 'DEV','ORDER','completed','PREPARING',TIMESTAMPTZ '2026-01-01',TIMESTAMPTZ '2026-01-01' FROM generate_series(1,501)");
        cleanup.scheduledRun();
        assertThat(cleanup.view().status()).isEqualTo("NEVER");
        assertThat(cleanup.preview().eligible()).containsEntry("customerNotifications",500L);
        assertThat(cleanup.run(1L,1L).deleted()).containsEntry("customerNotifications",500L);
        assertThat(cleanup.run(1L,1L).deleted()).containsEntry("customerNotifications",1L);
    }
    @Test void staleConfigurationAndConcurrentRunAreRejected() throws Exception {
        cleanup.save(new DataCleanupService.Config(true,"03:30",90,0),1);
        assertThatThrownBy(()->cleanup.run(1L,0L)).isInstanceOf(ResponseStatusException.class);
        try(var connection=dataSource.getConnection();var statement=connection.createStatement()) {
            connection.setAutoCommit(false);
            statement.execute("SELECT * FROM data_cleanup_settings WHERE environment='DEV' FOR UPDATE");
            assertThatThrownBy(()->cleanup.run(1L,1L)).isInstanceOf(ResponseStatusException.class);
            connection.rollback();
        }
        customer("DEV","completed","PREPARING","2026-01-01");
        cleanup.scheduledRun();
        assertThat(cleanup.view().deleted()).containsEntry("customerNotifications",1L);
        var first=cleanup.view().startedAt();
        cleanup.scheduledRun();
        assertThat(cleanup.view().startedAt()).isEqualTo(first);
        assertThat(cleanup.view().deleted()).containsEntry("customerNotifications",1L);
    }
    @Test void childDeletionFailureRollsBackEveryDeleteAndRecordsFailure() {
        long event=customer("DEV","completed","PREPARING","2026-01-01");
        jdbc.update("INSERT INTO customer_push_deliveries(event_id,state) VALUES (?,'ACCEPTED')",event);
        long alert=staff("DEV",1);
        jdbc.execute("CREATE FUNCTION reject_cleanup() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'test failure'; END $$");
        jdbc.execute("CREATE TRIGGER fail_delete BEFORE DELETE ON staff_order_alerts FOR EACH ROW EXECUTE FUNCTION reject_cleanup()");
        assertThatThrownBy(()->cleanup.run(1L,0L)).isInstanceOf(ResponseStatusException.class);
        assertThat(exists("customer_notification_events",event)).isTrue();
        assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM customer_push_deliveries WHERE event_id=?",Long.class,event)).isEqualTo(1L);
        assertThat(exists("staff_order_alerts",alert)).isTrue();
        assertThat(cleanup.view().status()).isEqualTo("FAILED");
        assertThat(cleanup.view().deleted()).isEmpty();
    }
    private DataCleanupService lostCommitResponse(boolean unavailable,boolean supersede) {
        return commitResponse(unavailable,supersede,true);
    }
    private DataCleanupService commitResponse(boolean unavailable,boolean supersede,boolean loseAcknowledgement) {
        var delegate=new DataSourceTransactionManager(dataSource);
        var commits=new AtomicInteger();
        var manager=new PlatformTransactionManager() {
            @Override public TransactionStatus getTransaction(TransactionDefinition definition) {
                if(unavailable && commits.get()>=2)throw new TransactionSystemException("Simulated database outage during reconciliation");
                return delegate.getTransaction(definition);
            }
            @Override public void commit(TransactionStatus status) {
                delegate.commit(status);
                if(commits.incrementAndGet()==2) {
                    if(supersede)cleanup.run(1L,0L);
                    if(loseAcknowledgement)throw new TransactionSystemException("Simulated lost commit acknowledgement");
                }
            }
            @Override public void rollback(TransactionStatus status) {delegate.rollback(status);}
        };
        return new DataCleanupService(jdbc,Clock.fixed(now,ZoneOffset.UTC),
            new MockEnvironment().withProperty("gokul.environment-isolation.environment","DEV"),new ObjectMapper(),manager);
    }
    @Test void successfulResponseKeepsItsCountsWhenAnotherRunCommitsBeforeReturn() {
        customer("DEV","completed","PREPARING","2026-01-01");
        var result=commitResponse(false,true,false).run(1L,0L);
        assertThat(result.status()).isEqualTo("SUCCEEDED");
        assertThat(result.deleted()).containsEntry("customerNotifications",1L);
        assertThat(cleanup.view().deleted()).containsEntry("customerNotifications",0L);
    }
    @Test void lostCommitAcknowledgementReturnsPersistedSuccessWithoutRepeatingDeletion() {
        long event=customer("DEV","completed","PREPARING","2026-01-01");
        var result=lostCommitResponse(false,false).run(1L,0L);
        assertThat(result.status()).isEqualTo("SUCCEEDED");
        assertThat(result.deleted()).containsEntry("customerNotifications",1L);
        assertThat(exists("customer_notification_events",event)).isFalse();
        assertThat(cleanup.view().error()).isNull();
    }
    @Test void unavailableReconciliationDoesNotClaimRollbackOrOverwriteSuccess() {
        long event=customer("DEV","completed","PREPARING","2026-01-01");
        assertThatThrownBy(()->lostCommitResponse(true,false).run(1L,0L))
            .isInstanceOf(ResponseStatusException.class).hasMessageContaining("could not be confirmed")
            .satisfies(failure->assertThat(failure.getMessage()).doesNotContain("no records were deleted"));
        assertThat(exists("customer_notification_events",event)).isFalse();
        assertThat(cleanup.view().status()).isEqualTo("SUCCEEDED");
    }
    @Test void aNewerRunIsNotMistakenForTheUncertainRun() {
        customer("DEV","completed","PREPARING","2026-01-01");
        assertThatThrownBy(()->lostCommitResponse(false,true).run(1L,0L))
            .isInstanceOf(ResponseStatusException.class).hasMessageContaining("could not be confirmed");
        assertThat(cleanup.view().status()).isEqualTo("SUCCEEDED");
        assertThat(cleanup.view().deleted()).containsEntry("customerNotifications",0L);
    }

}
