export const hindi: Record<string,string> = {
  "Pickup": "पिकअप",
  "Your details": "आपकी जानकारी",
  "Review": "जाँच करें",
  "Checkout": "ऑर्डर पूरा करें",
  "Who's picking up?": "ऑर्डर कौन ले जाएगा?",
  "Enter the name and mobile number we should use for pickup identification and order updates.": "ऑर्डर लेने और जानकारी पाने के लिए नाम और मोबाइल नंबर दें।",
  "Pickup contact": "संपर्क जानकारी",
  "We'll use these details for pickup and order updates. Sign in to fill your verified contact, or continue as a guest.": "ऑर्डर की जानकारी इस नंबर पर मिलेगी। लॉग इन करें या बिना लॉग इन आगे बढ़ें।",
  "Pickup from": "यहाँ से लें",
  "Change": "बदलें",
  "Pickup time": "पिकअप का समय",
  "Order summary": "ऑर्डर का विवरण",
  "item": "वस्तु",
  "more item": "और वस्तु",
  "← Back to Pickup Time": "← पिकअप का समय बदलें",
  "Checkout not found": "यह ऑर्डर नहीं मिला",
  "We could not find the pending order for this checkout.": "इस भुगतान का अधूरा ऑर्डर नहीं मिला।",
  "Return to Cart": "कार्ट पर वापस जाएँ",
  "Pickup reservation expired": "पिकअप का समय समाप्त हुआ",
  "Your cart and customer details are still available.": "आपका कार्ट और संपर्क जानकारी सुरक्षित हैं।",
  "You do not need to add your items or enter your details again.": "वस्तुएँ या जानकारी दोबारा भरने की जरूरत नहीं है।",
  "Releasing expired pickup reservation...": "पुराना पिकअप समय खाली किया जा रहा है…",
  "The old pickup reservation has been released.": "पुराना पिकअप समय खाली हो गया है।",
  "Pickup reserved": "पिकअप समय सुरक्षित है",
  "Time remaining": "बाकी समय",
  "Your cart has been updated": "आपका कार्ट बदल गया है",
  "Continue from Cart": "कार्ट से आगे बढ़ें",
  "Finding your best offers...": "आपके लिए ऑफर ढूँढ रहे हैं…",
  "Pickup slot reserved": "पिकअप समय सुरक्षित है",
  "Complete checkout before your reservation expires.": "बाकी समय में ऑर्डर पूरा करें।",
  "remaining": "बाकी",
  "Hurry — less than 5 minutes remain to complete checkout.": "ऑर्डर पूरा करने के लिए 5 मिनट से कम बचे हैं।",
  "Offers & savings": "ऑफर और बचत",
  "Choose an eligible offer or add more items before payment.": "भुगतान से पहले ऑफर चुनें या और वस्तुएँ जोड़ें।",
  "Your order": "आपका ऑर्डर",
  "Order amount": "ऑर्डर की राशि",
  "Offer saving": "ऑफर से बचत",
  "Offer applied": "ऑफर लागू है",
  "You saved": "आपकी बचत",
  "Unable to continue": "आगे नहीं बढ़ सके",
  "Try checking offers again": "ऑफर दोबारा देखें",
  "Available now": "अभी उपलब्ध",
  "Your eligible offers": "आपके लिए उपलब्ध ऑफर",
  "No eligible offers right now": "अभी कोई ऑफर उपलब्ध नहीं है",
  "You can still continue normally to payment.": "आप बिना ऑफर के भुगतान कर सकते हैं।",
  "Best saving": "सबसे ज्यादा बचत",
  "Applied": "लागू है",
  "Save": "बचाएँ",
  "Pay after offer": "ऑफर के बाद भुगतान",
  "Minimum order": "न्यूनतम ऑर्डर",
  "Maximum saving": "अधिकतम बचत",
  "Add": "जोड़ें",
  "more to unlock": "और जोड़ने पर मिलेंगे",
  "savings.": "की बचत।",
  "Next reward unlocks at": "अगली बचत के लिए राशि",
  "Add items to unlock offer": "ऑफर के लिए वस्तुएँ जोड़ें",
  "✓ Applied": "✓ लागू है",
  "Amount to pay": "भुगतान की राशि",
  "Offer saving applied": "ऑफर की बचत लागू है",
  "Continue to Payment": "भुगतान करें",
  "Continue to payment": "भुगतान करें",
  "You can continue without applying an offer.": "आप बिना ऑफर लगाए आगे बढ़ सकते हैं।",
  "Preparing secure payment...": "सुरक्षित भुगतान तैयार हो रहा है…",
  "We are checking the latest order and payment status with the backend.": "ऑर्डर और भुगतान की स्थिति जाँची जा रही है।",
  "Payment could not be prepared": "भुगतान तैयार नहीं हो सका",
  "Your cart has not been cleared.": "आपका कार्ट सुरक्षित है।",
  "Check My Orders": "मेरे ऑर्डर देखें",
  "Secure checkout": "सुरक्षित भुगतान",
  "Payment": "भुगतान",
  "Order": "ऑर्डर",
  "Your cart changed after this payment was prepared.": "भुगतान तैयार होने के बाद आपका कार्ट बदल गया।",
  "Existing PhonePe payment found": "पहले शुरू किया गया PhonePe भुगतान मिला",
  "Refund in progress": "पैसे वापस किए जा रहे हैं",
  "Refund completed": "पैसे वापस हो गए",
  "Refund needs attention": "पैसे वापसी के लिए मदद चाहिए",
  "Please keep this order number for support:": "मदद के लिए यह ऑर्डर नंबर रखें:",
  "Payment failed": "भुगतान नहीं हुआ",
  "Payment time expired": "भुगतान का समय समाप्त हुआ",
  "Amount": "राशि",
  "Payment status": "भुगतान की स्थिति",
  "Payment ID": "भुगतान आईडी",
  "Provider transaction": "लेनदेन नंबर",
  "Payment deadline": "भुगतान की समय सीमा",
  "Payable amount includes a convenience fee of": "भुगतान की राशि में सुविधा शुल्क शामिल है:",
  "(including": "(जिसमें शामिल है",
  "fee tax).": "शुल्क पर टैक्स)।",
  "Check payment and release the unpaid pickup reservation. Keep your items for another attempt.": "भुगतान की जाँच करके बिना भुगतान वाला ऑर्डर रद्द करें। वस्तुएँ कार्ट में रहेंगी।",
  "Close the gateway first. A payment received after cancellation enters the refund process.": "पहले भुगतान विंडो बंद करें। रद्द करने के बाद मिला भुगतान वापस करने की प्रक्रिया में जाएगा।",
  "Continue payment": "भुगतान जारी रखें",
  "View Order Details": "ऑर्डर का विवरण देखें",
  "Do not retry the old payment.": "पुराना भुगतान दोबारा न करें।",
  "Retry settings": "दोबारा लोड करें",
  "Use standard pickup selection": "सामान्य पिकअप चयन करें",
  "Loading pickup options...": "पिकअप के विकल्प लोड हो रहे हैं…",
  "Choose pickup": "पिकअप चुनें",
  "Pick the date and time that works best for you. Available capacity updates automatically.": "अपनी सुविधा के अनुसार तारीख और समय चुनें। उपलब्ध समय अपने आप अपडेट होते हैं।",
  "Currently reserved for you": "आपके लिए सुरक्षित समय",
  "Pickup date": "पिकअप की तारीख",
  "Open the list and choose the most convenient available time.": "सूची में से अपनी सुविधा का उपलब्ध समय चुनें।",
  "Unable to load pickup times": "पिकअप समय लोड नहीं हुए",
  "Try again": "दोबारा कोशिश करें",
  "No pickup times available for this date.": "इस तारीख पर पिकअप समय उपलब्ध नहीं है।",
  "Selected time": "चुना गया समय",
  "priority left": "प्राथमिकता पिकअप बाकी",
  "Priority pickup available for": "प्राथमिकता पिकअप का शुल्क",
  "extra.": "अतिरिक्त।",
  "Pickup type": "पिकअप का प्रकार",
  "Normal Pickup": "सामान्य पिकअप",
  "Included in your order.": "ऑर्डर में शामिल है।",
  "Full": "पूरा भरा है",
  "Priority Pickup": "प्राथमिकता पिकअप",
  "Uses priority pickup capacity.": "प्राथमिकता पिकअप में से समय लिया जाएगा।",
  "Back to Cart": "कार्ट पर वापस जाएँ",
  "Quantity confirmation required": "मात्रा की पुष्टि जरूरी है",
  "We cannot confirm the complete order for this pickup date": "इस तारीख पर पूरे ऑर्डर की पुष्टि नहीं हो सकती",
  "Some products need more preparation or stock than is currently available online.": "कुछ वस्तुओं के लिए अभी उपलब्ध स्टॉक या तैयारी समय कम है।",
  "You requested": "आपकी माँगी गई मात्रा",
  "Available online": "ऑनलाइन उपलब्ध",
  "Please reduce the quantity, choose another date, or contact the branch for a large-order confirmation.": "मात्रा कम करें, दूसरी तारीख चुनें या बड़े ऑर्डर के लिए दुकान से संपर्क करें।",
  "Earliest available date": "सबसे पहली उपलब्ध तारीख",
  "Choose This Pickup Date": "यह तारीख चुनें",
  "Need this quantity specially prepared?": "ज्यादा मात्रा में बनवाना है?",
  "Call": "कॉल करें",
  "Adjust Cart Quantity": "मात्रा बदलें",
  "Your cart is empty": "आपका कार्ट खाली है",
  "Add some items before reviewing your order.": "पहले कार्ट में वस्तुएँ जोड़ें।",
  "Explore Menu": "मेन्यू देखें",
  "Branch mismatch": "दुकान अलग है",
  "Please select the branch associated with your cart.": "अपने कार्ट वाली दुकान चुनें।",
  "Select Branch": "दुकान चुनें",
  "Pickup time required": "पिकअप समय चुनना जरूरी है",
  "Select a pickup date and time before reviewing your order.": "पहले पिकअप की तारीख और समय चुनें।",
  "Choose Pickup": "पिकअप चुनें",
  "Customer details required": "संपर्क जानकारी जरूरी है",
  "Enter your name and phone number before reviewing your order.": "आगे बढ़ने के लिए संपर्क जानकारी दें।",
  "Enter Details": "जानकारी दें",
  "Review & offers": "ऑर्डर और ऑफर",
  "Almost there": "बस एक कदम बाकी",
  "Review your pickup order": "अपना ऑर्डर जाँचें",
  "Check your pickup time, contact details and items. Then check eligible offers or enter an exclusive code without leaving this page.": "पिकअप समय, संपर्क और वस्तुएँ जाँचें। इसी पेज पर ऑफर देखें या ऑफर कोड डालें।",
  "Pickup details": "पिकअप की जानकारी",
  "Normal capacity is full for this pickup time.": "इस समय सामान्य पिकअप पूरा भरा है।",
  "Priority charge:": "प्राथमिकता शुल्क:",
  "Change time": "समय बदलें",
  "Edit": "बदलें",
  "Priority pickup": "प्राथमिकता पिकअप",
  "No surprises at payment": "भुगतान से पहले पूरी राशि देखें",
  "See item prices, GST, any pickup charge and your savings together before you pay.": "वस्तुओं की कीमत, GST, पिकअप शुल्क और बचत भुगतान से पहले देखें।",
  "You're offline. Your cart is saved. Reconnect and check your final price again before continuing.": "इंटरनेट नहीं है। कार्ट सुरक्षित है। इंटरनेट आने पर पूरी राशि दोबारा जाँचें।",
  "Your price, before offers": "ऑफर से पहले राशि",
  "This price needs refreshing. Your cart and pickup details are saved.": "राशि दोबारा जाँचनी है। कार्ट और पिकअप सुरक्षित हैं।",
  "Items subtotal": "वस्तुओं की राशि",
  "GST": "GST",
  "Convenience fee (tax included)": "सुविधा शुल्क (टैक्स सहित)",
  "Final price": "अंतिम राशि",
  "Payable": "भुगतान की राशि",
  "Confirmed final amount": "पुष्ट अंतिम राशि",
  "I have reviewed the updated total and offers.": "मैंने नई राशि और ऑफर देख लिए हैं।",
  "Review updated total": "नई राशि जाँचें",
  "Review & reserve": "राशि देखकर आगे बढ़ें",
  "Check price & offers": "राशि और ऑफर जाँचें",
  "Checking your total…": "आपकी राशि जाँची जा रही है…",
  "Opening checkout…": "ऑर्डर का पेज खुल रहा है…",
  "Check your final price": "पूरी राशि जाँचें",
  "Review your total, then explore any available offers before paying.": "राशि जाँचें और भुगतान से पहले ऑफर देखें।",
  "← Back to Cart": "← कार्ट पर वापस जाएँ",
  "Adjust your pickup here": "पिकअप और मात्रा बदलें",
  "Your current reservation stays unchanged if the check fails. No payment is started here.": "जाँच नहीं होने पर पुराना पिकअप सुरक्षित रहेगा। यहाँ भुगतान शुरू नहीं होगा।",
  "Grams · minimum": "ग्राम · न्यूनतम",
  ", step": ", बढ़ोतरी",
  "Remove": "हटाएँ",
  "Choose an available time": "उपलब्ध समय चुनें",
  "Refresh available times": "उपलब्ध समय दोबारा देखें",
  "Keep current pickup": "पुराना पिकअप रखें",
  "Gokul Sweets": "गोकुल स्वीट्स",
  "FRESH FOR YOUR MOMENTS": "आपके हर पल में ताजगी",
  "PICKUP FROM": "यहाँ से लें",
  "Complete checkout before the timer ends.": "बाकी समय में ऑर्डर पूरा करें।",
  "Choose a new pickup time before continuing. Your cart is still available.": "आगे बढ़ने के लिए नया पिकअप समय चुनें। कार्ट सुरक्षित है।",
  "Your cart has changed": "कार्ट बदल गया है",
  "Review changes here": "बदलाव यहाँ देखें",
  "Save on this order": "इस ऑर्डर पर बचत करें",
  "See offers available for this order": "इस ऑर्डर के ऑफर देखें",
  "We'll check the server using your final cart value, branch, pickup type and eligibility.": "आपकी वस्तुओं, दुकान और पिकअप के अनुसार ऑफर जाँचे जाएँगे।",
  "Find available offers": "ऑफर देखें",
  "No public offers available": "अभी कोई सार्वजनिक ऑफर नहीं है",
  "Have a creator, partner or promotional code? You can still enter it below.": "ऑफर कोड है? नीचे डालें।",
  "Applied ✓": "लागू है ✓",
  "more to unlock the next saving level.": "और जोड़ने पर अगली बचत मिलेगी।",
  "Have a creator or exclusive code?": "आपके पास ऑफर कोड है?",
  "Enter a code shared by an influencer, partner, event or private campaign.": "आपको मिला ऑफर कोड यहाँ डालें।",
  "Offer applied ✓": "ऑफर लागू है ✓",
  "Adjust quantities or pickup": "मात्रा या पिकअप बदलें",
  "Recheck current cart and total": "कार्ट और राशि दोबारा जाँचें",
  "Your name": "आपका नाम",
  "Mobile number": "मोबाइल नंबर",
  "Continue to Review": "ऑर्डर जाँचें",
  "Before you leave payment": "भुगतान से वापस जाने से पहले",
  "Keep this order to pay later, or check payment and cancel the unpaid reservation now. Your cart stays saved. A confirmed payment will preserve the order.": "बाद में भुगतान के लिए ऑर्डर रखें या भुगतान जाँचकर अभी रद्द करें। कार्ट सुरक्षित रहेगा। भुगतान हो चुका है तो ऑर्डर रद्द नहीं होगा।",
  "Stay & retry payment": "रुकें और भुगतान करें",
  "Leave & keep order for later": "वापस जाएँ और ऑर्डर रखें",
  "Cancel order & keep cart": "ऑर्डर रद्द करें, कार्ट रखें",
  "Cancel this order": "यह ऑर्डर रद्द करें",
  "Check Payment Status": "भुगतान की स्थिति देखें",
  "A little extra for your pickup": "ऑर्डर में कुछ और जोड़ें",
  "Pairs well with your order": "आपके ऑर्डर के साथ अच्छा रहेगा",
  "No thanks": "नहीं, धन्यवाद",
  "· including item tax": "· वस्तु का टैक्स शामिल है",
  "Reaches this offer's spend threshold": "इस ऑफर के लिए जरूरी राशि पूरी होती है",
  "Optional additions at the menu price. Price and pickup availability are checked again before payment.": "मेन्यू की कीमत पर अपनी पसंद से जोड़ें। भुगतान से पहले राशि और पिकअप दोबारा जाँचे जाएँगे।",
  "Adjust quantities or pickup here": "यहीं मात्रा या पिकअप बदलें",
  "Checking product availability for this date…": "इस तारीख के लिए उपलब्धता जाँची जा रही है…",
  "Availability could not be confirmed": "उपलब्धता की पुष्टि नहीं हो सकी",
  "Some items need your attention": "कुछ वस्तुओं को जाँचें",
  "Requested:": "माँगी गई मात्रा:",
  "· Available:": "· उपलब्ध:",
  "Choose": "चुनें",
  "instead": "के बदले",
  "Planning a large order?": "बड़ा ऑर्डर करना है?",
  "Choose a date": "तारीख चुनें",
  "Choose a time": "समय चुनें",
  "Choose your pickup": "पिकअप चुनें",
  "Review your cart": "कार्ट देखें",
  "Add items from the menu first": "पहले मेन्यू से वस्तुएँ जोड़ें",
  "Retry": "दोबारा कोशिश करें",
  "Continue": "आगे बढ़ें",
  "Checking...": "जाँच रहे हैं…",
  "Checking…": "जाँच रहे हैं…",
  "Loading…": "लोड हो रहा है…",
  "Loading...": "लोड हो रहा है…",
  "Menu": "मेन्यू",
  "Home": "होम",
  "Cart": "कार्ट",
  "My Orders": "मेरे ऑर्डर",
  "My orders": "मेरे ऑर्डर",
  "Account": "खाता",
  "Log in": "लॉग इन",
  "Help": "मदद",
  "Profile": "प्रोफाइल",
  "View cart": "कार्ट देखें",
  "View Cart": "कार्ट देखें",
  "Add to cart": "कार्ट में जोड़ें",
  "Add to Cart": "कार्ट में जोड़ें",
  "Your cart": "आपका कार्ट",
  "Choose a shop": "दुकान चुनें",
  "All": "सभी",
  "All items": "सभी वस्तुएँ",
  "Search menu": "मेन्यू में खोजें",
  "Checkout action": "ऑर्डर पूरा करें",
  "Review before payment": "भुगतान से पहले जाँचें",
  "Payable total": "भुगतान की राशि",
  "Check your total": "पूरी राशि देखें",
  "Phone verification": "मोबाइल सत्यापन",
  "Checking phone verification…": "मोबाइल सत्यापन जाँच रहे हैं…",
  "Sign in": "लॉग इन",
  "Continue as guest": "बिना लॉग इन आगे बढ़ें",
  "Enter your name": "अपना नाम लिखें",
  "Enter 10-digit mobile number": "10 अंकों का मोबाइल नंबर लिखें",
  "Please enter your name.": "अपना नाम लिखें।",
  "Enter a valid 10-digit mobile number.": "सही 10 अंकों का मोबाइल नंबर लिखें।",
  "Your verified number is used for order updates and pickup identification.": "ऑर्डर की जानकारी और पहचान के लिए आपका सत्यापित नंबर उपयोग होगा।",
  "We’ll use this number for order updates and pickup identification.": "ऑर्डर की जानकारी और पहचान के लिए यह नंबर उपयोग होगा।",
  "Pay": "भुगतान करें",
  "Retry payment": "फिर भुगतान करें",
  "Offers": "ऑफर",
  "Details": "जानकारी",
  "Preparing": "तैयार हो रहा है",
  "Ready": "तैयार है",
  "Confirmed": "पुष्ट है",
  "Pending": "बाकी है",
  "Close": "बंद करें",
  "Back": "वापस",
  "Cancel": "रद्द करें",
  "Refresh": "दोबारा लोड करें",
  "Today": "आज",
  "Tomorrow": "कल",
  "Normal": "सामान्य",
  "Priority": "प्राथमिकता",
  "Adjust cart quantities": "कार्ट की मात्रा बदलें",
  "Priority available": "प्राथमिकता उपलब्ध है",
  "normal": "सामान्य",
  "priority": "प्राथमिकता",
  "Normal pickup": "सामान्य पिकअप",
  "Select pickup time": "पिकअप का समय चुनें",
  "Tap to view available slots": "उपलब्ध समय देखने के लिए दबाएँ",
  "Your cart and details are saved. Pick a time that works for everything in your order.": "कार्ट और जानकारी सुरक्षित हैं। पूरे ऑर्डर के लिए उपलब्ध समय चुनें।",
  "Finding available times…": "उपलब्ध समय ढूँढ रहे हैं…",
  "Try finding times again": "समय दोबारा ढूँढें",
  "No other times are available for this cart right now. Try another date or contact the branch.": "अभी इस कार्ट के लिए दूसरा समय नहीं है। दूसरी तारीख चुनें या दुकान से संपर्क करें।",
  "See all pickup times": "सभी पिकअप समय देखें",
  "Your previous pickup has passed. Showing today’s available times. Your cart is saved.": "पुराना पिकअप समय निकल गया। आज के समय दिखा रहे हैं। कार्ट सुरक्षित है।",
  "Branch & menu": "दुकान और मेन्यू",
  "/ Review": "/ जाँचें",
  "Pickup at": "पिकअप",
  "Choose when to collect": "ऑर्डर लेने का समय चुनें",
  "Times are checked for your whole cart at": "पूरे कार्ट के लिए समय जाँचे जाते हैं:",
  ". Your order is reserved at checkout.": "। आगे बढ़ने पर ऑर्डर का समय सुरक्षित होगा।",
  "Your cart belongs to a different branch.": "कार्ट दूसरी दुकान का है।",
  "before continuing.": "फिर आगे बढ़ें।",
  "Your cart is preserved. Checkout will still validate availability.": "कार्ट सुरक्षित है। ऑर्डर पूरा करते समय उपलब्धता फिर जाँची जाएगी।",
  "Checking dates and times for your cart...": "कार्ट के लिए तारीख और समय जाँचे जा रहे हैं…",
  "Next pickup for all items:": "सभी वस्तुओं के लिए अगला पिकअप:",
  "Approved for future preparation": "आगे की तैयारी के लिए उपलब्ध",
  "- pickup times": "– पिकअप समय",
  "Edit quantities or remove items in your cart": "कार्ट में मात्रा बदलें या वस्तुएँ हटाएँ",
  "Available pickup times": "उपलब्ध पिकअप समय",
  "No matching times on this date. Try another date above.": "इस तारीख पर समय नहीं है। ऊपर दूसरी तारीख चुनें।",
  "Only times that fit every item in your cart are selectable. All times are India time.": "पूरे कार्ट के लिए उपलब्ध समय ही चुने जा सकते हैं। सभी समय भारतीय समय हैं।",
  "Why are": "क्यों हैं",
  "other times not available?": "बाकी समय उपलब्ध नहीं?",
  "Also:": "साथ ही:",
  "items · INR": "वस्तुएँ · ₹",
  "before tax": "टैक्स से पहले",
  "at": "पर",
  "Branches": "दुकानें",
  "menu": "मेन्यू",
  "Freshly made for the moments that matter. Order online, then collect from your chosen branch.": "अपने खास पलों के लिए ताजा स्वाद। ऑनलाइन ऑर्डर करें और चुनी हुई दुकान से लें।",
  "EXPLORE": "देखें",
  "Our story": "हमारी कहानी",
  "YOUR ORDER": "आपका ऑर्डर",
  "Orders": "ऑर्डर",
  "Pickup only": "दुकान से पिकअप",
  "GOOD TO KNOW": "जरूरी जानकारी",
  "Choose a branch to see its live menu.": "मेन्यू देखने के लिए दुकान चुनें।",
  "Pickup times and the full price are confirmed before payment.": "भुगतान से पहले पिकअप समय और पूरी राशि की पुष्टि होगी।",
  "Made with care, ready for pickup.": "प्यार से तैयार, आपके लिए तैयार।",
  "Fresh sweets. Happier moments.": "ताजा मिठाइयाँ, खुशियों के पल।",
  "PICKUP BRANCH": "पिकअप की दुकान",
  "Tradition tastes better": "परंपरा का स्वाद",
  "Soon": "जल्द",
  "Staff dashboard": "स्टाफ डैशबोर्ड",
  "Follow us": "हमसे जुड़ें",
  "New sweets, festive specials and shop updates.": "नई मिठाइयाँ, त्योहारों के खास स्वाद और दुकान की खबरें।",
  "Online orders are prepared for pickup from your selected branch.": "ऑनलाइन ऑर्डर आपकी चुनी दुकान से पिकअप के लिए तैयार होते हैं।",
  "Pickup ·": "पिकअप ·",
  "· Time is checked again at checkout": "· ऑर्डर पूरा करते समय दोबारा समय जाँचा जाएगा",
  "Change branch": "दुकान बदलें",
  "Stay connected": "हमसे जुड़े रहें",
  "Follow Gokul Sweets": "गोकुल स्वीट्स से जुड़ें",
  "Not now": "अभी नहीं",
  "Browse menu": "मेन्यू देखें",
  "Freshly made.": "ताजा तैयार।",
  "Ready for you.": "आपके लिए।",
  "Occasions & gifting": "समारोह और उपहार",
  "Branch details": "दुकान की जानकारी",
  "Good taste starts here": "अच्छे स्वाद की शुरुआत यहाँ से",
  "Sweet moments.": "मिठास भरे पल।",
  "Savour every bite.": "हर निवाले का आनंद लें।",
  "Order Now": "ऑर्डर करें",
  "Explore delivery by area": "अपने क्षेत्र में डिलीवरी देखें",
  "On the menu": "मेन्यू में",
  "Take a look": "देखें",
  "Find your favourites": "अपनी पसंद चुनें",
  "Pick your time": "समय चुनें",
  "Collect & enjoy": "दुकान से लें और आनंद लें",
  "Something for every mood": "हर मन के लिए कुछ खास",
  "What are you craving?": "आज क्या खाना चाहेंगे?",
  "View menu": "मेन्यू देखें",
  "Choose a branch to see its menu and prices.": "मेन्यू और कीमत देखने के लिए दुकान चुनें।",
  "Loading your branch menu...": "दुकान का मेन्यू लोड हो रहा है…",
  "Open menu": "मेन्यू खोलें",
  "No items are currently available at this branch.": "इस दुकान पर अभी वस्तुएँ उपलब्ध नहीं हैं।",
  "Discover on the menu": "मेन्यू में देखें",
  "Choose your favourites. We'll show pickup dates that fit your whole cart.": "अपनी पसंद चुनें। पूरे कार्ट के लिए उपलब्ध पिकअप तारीखें दिखाएँगे।",
  "Order for later": "आगे के लिए ऑर्डर करें",
  "Gokul specials": "गोकुल के खास स्वाद",
  "Our branches": "हमारी दुकानें",
  "Order food": "खाना ऑर्डर करें",
  "Plan an occasion": "समारोह की योजना बनाएँ",
  "Scroll to explore": "नीचे और देखें",
  "OUR BRANCHES": "हमारी दुकानें",
  "Your next visit starts here.": "आपकी अगली मुलाकात यहाँ से शुरू होती है।",
  "Choose a Gokul branch near you to see its live menu and pickup choices.": "मेन्यू और पिकअप के लिए अपने पास की गोकुल दुकान चुनें।",
  "Explore this branch": "यह दुकान देखें",
  "Pickup location required": "पिकअप की दुकान चुनें",
  "Select your pickup branch": "पिकअप की दुकान चुनें",
  "Your branch determines which products, prices and pickup options are available.": "वस्तुएँ, कीमत और पिकअप समय चुनी दुकान के अनुसार होंगे।",
  "Choose Branch": "दुकान चुनें",
  "Freshly prepared": "ताजा तैयार",
  "Pickup branch": "पिकअप की दुकान",
  "Clear filters": "फिल्टर हटाएँ",
  "No matching items": "कोई वस्तु नहीं मिली",
  "Try another search or category to see more of the menu.": "कुछ और खोजें या दूसरी श्रेणी चुनें।",
  "Show all items": "सभी वस्तुएँ देखें",
  "Unable to load menu": "मेन्यू लोड नहीं हुआ",
  "Find a favourite": "अपनी पसंद खोजें",
  "pickup · Change time": "पिकअप · समय बदलें",
  "Your previous pickup has passed. Choose a new date; your cart is saved.": "पुराना पिकअप समय निकल गया। नई तारीख चुनें। कार्ट सुरक्षित है।",
  "Choose pickup to check availability. Browse and build your cart first if you prefer.": "उपलब्धता के लिए पिकअप चुनें। चाहें तो पहले मेन्यू से कार्ट बनाएँ।",
  "That pickup date has passed. Choose a new date; your cart is saved.": "यह तारीख निकल गई। नई तारीख चुनें। कार्ट सुरक्षित है।",
  "Checking your pickup date...": "पिकअप तारीख जाँची जा रही है…",
  "Live preview, not a reservation.": "अभी केवल उपलब्धता दिखाई गई है। समय सुरक्षित नहीं हुआ है।",
  "Your saved pickup time no longer fits this selection.": "चुना समय इस ऑर्डर के लिए अब उपलब्ध नहीं है।",
  "Choose another time": "दूसरा समय चुनें",
  ". Your cart is unchanged.": "। कार्ट में कोई बदलाव नहीं हुआ।",
  "Review these items for your pickup": "पिकअप के लिए इन वस्तुओं को जाँचें",
  "Edit quantities or remove items below, or keep your cart and find another pickup.": "नीचे मात्रा बदलें या वस्तुएँ हटाएँ, या कार्ट रखकर दूसरा पिकअप चुनें।",
  "Find a time for all items": "सभी वस्तुओं के लिए समय ढूँढें",
  "New · No ratings yet": "नया · अभी कोई रेटिंग नहीं",
  "/kg": "/किलो",
  "From": "से",
  "for": "के लिए",
  "ADD": "जोड़ें",
  "No items found": "कोई वस्तु नहीं मिली",
  "Try another category or search term.": "दूसरी श्रेणी या शब्द से खोजें।",
  "Choose quantity": "मात्रा चुनें",
  "Quick select": "जल्दी चुनें",
  "Enter exact quantity": "अपनी मात्रा लिखें",
  "Minimum": "न्यूनतम",
  "steps": "की बढ़ोतरी",
  "Estimated price": "अनुमानित राशि",
  "Final amount is calculated by Gokul Sweets using the selected weight.": "चुने हुए वजन के अनुसार गोकुल स्वीट्स अंतिम राशि की गणना करेगा।",
  "Review items for this branch": "इस दुकान के लिए वस्तुएँ जाँचें",
  "Your original cart is saved. Checkout is paused until you confirm the items for this branch.": "पुराना कार्ट सुरक्षित है। इस दुकान की वस्तुओं की पुष्टि के बाद आगे बढ़ें।",
  "Checking menu and stock...": "मेन्यू और स्टॉक जाँचे जा रहे हैं…",
  "No pickup time has capacity for this date. Choose another date.": "इस तारीख पर पिकअप नहीं है। दूसरी तारीख चुनें।",
  "Clear cart and choose again": "कार्ट खाली करके फिर चुनें",
  "Delete": "हटाएँ",
  "Item total": "वस्तु की राशि",
  "Items": "वस्तुएँ",
  "Select the pickup branch associated with this cart to continue.": "आगे बढ़ने के लिए कार्ट वाली दुकान चुनें।",
  "Continue to Pickup Time": "पिकअप समय चुनें",
  "You can still review your order before payment.": "भुगतान से पहले आप ऑर्डर जाँच सकेंगे।",
  "Pickup date:": "पिकअप तारीख:",
  "Keep current selection": "पुराना चयन रखें",
  "Close and retry": "बंद करके फिर कोशिश करें",
  "Nothing here yet": "अभी कार्ट खाली है",
  "Add your favourite sweets, snacks and meals, then choose a convenient pickup time.": "अपनी पसंद की मिठाइयाँ, नाश्ता और खाना जोड़ें, फिर पिकअप समय चुनें।",
  "Your pickup order": "आपका पिकअप ऑर्डर",
  "ready for review": "जाँच के लिए तैयार",
  "Clear cart": "कार्ट खाली करें",
  "Selected pickup branch": "चुनी गई पिकअप दुकान",
  "Cart branch mismatch": "कार्ट की दुकान अलग है",
  "← Add more items": "← और वस्तुएँ जोड़ें",
  "Your cart is saved. Reconnect before choosing a pickup time.": "कार्ट सुरक्षित है। इंटरनेट आने पर पिकअप समय चुनें।",
  "Preparing your order...": "ऑर्डर तैयार हो रहा है…",
  "Refresh your total": "राशि दोबारा जाँचें",
  "Accept price and reserve pickup": "राशि स्वीकार करके आगे बढ़ें",
  "Check Final Price & Offers": "राशि और ऑफर जाँचें",
  "Before paying": "भुगतान से पहले",
  "The reservation timer does not restart when you add items.": "वस्तुएँ जोड़ने पर पिकअप का बाकी समय नहीं बढ़ेगा।",
  "The reserved checkout time has ended. Your cart is still safe. We are making sure the old pickup reservation has been released before you choose a new slot.": "ऑर्डर पूरा करने का समय समाप्त हुआ। कार्ट सुरक्षित है। नया पिकअप चुनने से पहले पुराने समय की जाँच हो रही है।",
  "Your pickup reservation is still being held. Continue checkout so we can update this same order with your latest cart.": "आपका पिकअप सुरक्षित है। बदले हुए कार्ट के साथ इसी ऑर्डर को अपडेट करने के लिए आगे बढ़ें।",
  "Your pickup reservation stays active while you review offers or add items. The timer does not restart when the cart changes.": "ऑफर देखते समय पिकअप सुरक्षित है। कार्ट बदलने पर बाकी समय नहीं बढ़ेगा।",
  "Do not pay this stale checkout. Return to the cart and continue checkout so the backend can validate the current items.": "इस पुराने कार्ट के लिए भुगतान न करें। कार्ट पर लौटकर नया ऑर्डर जाँचें।",
  "We recovered the payment from the backend. The browser no longer has the original checkout link, so we will continue checking the existing PhonePe payment instead of creating a duplicate payment.": "पहले शुरू हुआ PhonePe भुगतान मिल गया है। नया भुगतान बनाने के बजाय उसकी स्थिति जाँचेंगे।",
  "This page checks our backend automatically. You can also check again manually.": "इस पेज पर स्थिति अपने आप अपडेट होती है। आप खुद भी दोबारा जाँच सकते हैं।",
  "The automatic refund did not reach a successful final state. Your old order has not been restored and no": "पैसे वापसी की पुष्टि नहीं हुई। पुराना ऑर्डर फिर चालू नहीं किया गया और कोई",
  "The order is no longer holding its": "इस ऑर्डर के लिए अब सुरक्षित नहीं है:",
  ". Your cart is still available.": "। आपका कार्ट सुरक्षित है।",
  "If the payment provider later reports that money was actually captured, the backend automatically starts the refund reconciliation flow.": "अगर बाद में भुगतान मिलने की पुष्टि होती है, तो पैसे वापसी की प्रक्रिया अपने आप शुरू होगी।",
  "reservation has been released. Your cart is still safe, so you can choose a new": "समय खाली हो गया है। कार्ट सुरक्षित है, नया समय चुनें:",
  "If the payment provider later reports a captured payment, the backend will move it into automatic refund reconciliation instead of confirming this expired order.": "बाद में भुगतान मिलने पर इस समाप्त ऑर्डर को पुष्ट करने के बजाय पैसे वापसी की प्रक्रिया होगी।",
  "This payment window has closed. Please check its status before starting a new checkout. If you paid, it may take a little longer to confirm.": "यह भुगतान विंडो बंद हो गई। फिर से ऑर्डर करने से पहले भुगतान की स्थिति जाँचें। भुगतान किया है तो पुष्टि में थोड़ा समय लग सकता है।",
  "Your order is confirmed only after our backend verifies a successful payment. Closing or going back from the payment window does not directly cancel the order.": "भुगतान की पुष्टि के बाद ही ऑर्डर पुष्ट होगा। विंडो बंद करने या वापस जाने से ऑर्डर अपने आप रद्द नहीं होता।",
  "Keep this time or choose another available time below. Your current reservation remains safe until the change succeeds.": "पुराना समय रखें या नीचे दूसरा समय चुनें। बदलाव की पुष्टि तक पुराना पिकअप सुरक्षित रहेगा।",
  "Please call the selected branch. Our team can check production capacity and confirm whether this large order can be prepared.": "दुकान को कॉल करें। टीम बड़े ऑर्डर की तैयारी और उपलब्धता की पुष्टि करेगी।",
  "Your reservation is unchanged if provider verification failed. You can retry the check or stay on payment.": "भुगतान की जाँच नहीं होने पर पुराना पिकअप सुरक्षित है। दोबारा जाँचें या भुगतान पेज पर रहें।",
  "No online date within the current booking window can confirm the complete quantity. Please call the branch so the team can check production capacity.": "अभी ऑनलाइन उपलब्ध तारीखों में पूरी मात्रा नहीं मिल सकती। तैयारी की जानकारी के लिए दुकान को कॉल करें।",
  "Fresh sweets, snacks and meals from your chosen branch. Browse the live menu and choose a pickup time at checkout.": "चुनी दुकान से ताजा मिठाइयाँ, नाश्ता और खाना। मेन्यू देखें और ऑर्डर करते समय पिकअप चुनें।",
  "See new sweets, festive specials and shop updates on our social pages.": "सोशल पेज पर नई मिठाइयाँ, त्योहारों के खास स्वाद और दुकान की खबरें देखें।",
  "Branch details will appear here when available. You can still explore the menu.": "दुकान की जानकारी उपलब्ध होने पर यहाँ दिखेगी। आप अभी मेन्यू देख सकते हैं।",
  "Taxes and any priority pickup charge depend on the time you choose at checkout. Review the final amount before paying.": "टैक्स और प्राथमिकता शुल्क चुने समय के अनुसार होंगे। भुगतान से पहले पूरी राशि देखें।",
  "The cart stays saved. Unavailable lines need attention before checkout.": "कार्ट सुरक्षित है। आगे बढ़ने से पहले उपलब्ध न होने वाली वस्तुएँ जाँचें।",
  "These cart items belong to another pickup branch. Select the matching branch before continuing, or clear the cart and start a new order from this branch.": "ये वस्तुएँ दूसरी दुकान की हैं। वह दुकान चुनें या कार्ट खाली करके यहाँ से नया ऑर्डर बनाएँ।",
  "Opening…": "पेज खुल रहा है…",
  "Opening secure payment…": "सुरक्षित भुगतान खुल रहा है…",
  "Online ordering is taking longer to connect.": "ऑनलाइन ऑर्डर जुड़ने में थोड़ा समय लग रहा है।",
  "We couldn't check this pickup time. Your cart is saved. Try again.": "पिकअप समय की जाँच नहीं हो सकी। कार्ट सुरक्षित है। दोबारा कोशिश करें।",
  "Your cart or pickup choice changed. Review the updated times before continuing.": "कार्ट या पिकअप बदल गया। आगे बढ़ने से पहले नया समय जाँचें।",
  "That time has just changed. Your cart is safe; choose another available time below.": "यह समय अभी बदल गया। कार्ट सुरक्षित है। नीचे दूसरा समय चुनें।",
  "We couldn’t check your total. Tap Check price & offers to try again.": "राशि की जाँच नहीं हो सकी। राशि और ऑफर जाँचें दबाकर फिर कोशिश करें।",
  "Please select a pickup date and time.": "पिकअप की तारीख और समय चुनें।",
  "Please enter your customer details.": "अपनी संपर्क जानकारी दें।",
  "Please enter a valid 10-digit Indian mobile number.": "सही 10 अंकों का भारतीय मोबाइल नंबर लिखें।",
  "Please enter a valid customer name.": "सही नाम लिखें।",
  "Select a pickup date and an available pickup time before continuing.": "आगे बढ़ने से पहले तारीख और उपलब्ध पिकअप समय चुनें।",
  "Your cart has changed. Review the updated cart before payment.": "कार्ट बदल गया। भुगतान से पहले नया कार्ट जाँचें।",
  "Your pickup reservation has expired. Please choose a pickup slot again.": "पिकअप का समय समाप्त हुआ। नया समय चुनें।",
  "Enter a valid quantity or weight using the shown minimum and step.": "दिखाई गई न्यूनतम मात्रा और बढ़ोतरी के अनुसार मात्रा लिखें।",
  "Choose a current available pickup time.": "अभी उपलब्ध पिकअप समय चुनें।",
  "Choose a pickup date within the available India dates.": "उपलब्ध भारतीय तारीखों में से पिकअप चुनें।",
  "Keep at least one item, or cancel your order using the order actions.": "कम से कम एक वस्तु रखें या ऑर्डर रद्द करें।",
  "Phone verification is unavailable": "मोबाइल सत्यापन उपलब्ध नहीं है",
  "Log in to your account": "अपने खाते में लॉग इन करें",
  "Need to stop this checkout?": "यह ऑर्डर रोकना है?",
  "Checking payment…": "भुगतान जाँचा जा रहा है…",
  "Check & retry checkout": "जाँचकर नया प्रयास करें",
  "Ready when you are. Tap Pay to open secure checkout.": "भुगतान के लिए तैयार है। सुरक्षित भुगतान खोलने के लिए भुगतान करें दबाएँ।",
  "Closing the payment window does not cancel your order immediately.": "भुगतान विंडो बंद करने से ऑर्डर अपने आप रद्द नहीं होता।",
  "Payment pending": "भुगतान बाकी है",
  "Payment successful": "भुगतान सफल हुआ",
  "Loading your order…": "आपका ऑर्डर लोड हो रहा है…",
  "No orders yet": "अभी कोई ऑर्डर नहीं है",
  "Times available": "समय उपलब्ध है",
  "No matching time": "उपयुक्त समय नहीं है",
  "No matching times on this date": "इस तारीख पर उपयुक्त समय नहीं है",
  "Total before optional offers": "ऑफ़र लगाने से पहले कुल राशि",
  "This price is available until": "यह राशि इस समय तक मान्य है",
  "See the cancellation policy": "ऑर्डर रद्द करने के नियम देखें",
  "before paying.": "भुगतान करने से पहले।",
  "Tax": "कर",
  "Pickup charge": "पिकअप शुल्क",
};
