export const hindi: Record<string,string> = {
 "Clear cart?": "कार्ट खाली करें?",
 "Are you sure you want to clear your cart?": "क्या आप अपना कार्ट खाली करना चाहते हैं?",
 "No, keep cart": "नहीं, कार्ट रखें",
 "Yes, clear cart": "हाँ, कार्ट खाली करें",
 "Choose a branch for your occasion": "अपने समारोह के लिए शाखा चुनें",
 "Select the branch that will prepare your bulk order.": "अपना बड़ा ऑर्डर तैयार करने वाली शाखा चुनें।",
 "Plan at this branch": "इस शाखा में योजना बनाएँ",
 "Branch details could not be loaded.": "शाखाओं की जानकारी लोड नहीं हो सकी।",
 "No branches are available right now.": "अभी कोई शाखा उपलब्ध नहीं है।",
 "Connecting to the branch and loading the latest details.": "शाखा से जुड़कर नई जानकारी लोड हो रही है।",
 "This is taking longer than usual. We are waiting for a response; please keep this page open.": "सामान्य से अधिक समय लग रहा है। हम जवाब की प्रतीक्षा कर रहे हैं; कृपया यह पेज खुला रखें।",
 "Confirming your order and connecting to secure payment. Please keep this page open.": "आपके ऑर्डर की पुष्टि और सुरक्षित भुगतान से जुड़ने की प्रक्रिया चल रही है। कृपया यह पेज खुला रखें।",
 "Waiting for the payment provider to confirm your payment. Please keep this page open.": "भुगतान सेवा से पुष्टि की प्रतीक्षा है। कृपया यह पेज खुला रखें।",
 "Checking your order and connecting to the payment provider. Please keep this page open.": "आपका ऑर्डर जाँचकर भुगतान सेवा से जुड़ रहे हैं। कृपया यह पेज खुला रखें।",

    "Jump to a category": "श्रेणी पर जाएँ",
    "Choose a category to see its items. This clears your search and filters.": "सामान देखने के लिए श्रेणी चुनें। इससे खोज और फ़िल्टर हट जाएँगे।",
    "Preparing your visit…": "आपके स्वागत की तैयारी हो रही है…",

  "Sweets you’ll love": "आपकी पसंद की मिठाइयाँ",
  "Choose weight": "वज़न चुनें",
  "/ piece": "/ पीस",
  "piece": "पीस",
  "pieces": "पीस",
  "Made fresh.": "ताज़ा बनाया।",
  "Loved daily.": "हर दिन पसंद किया।",
  "Little extras.": "छोटी खुशियाँ।",
  "Big smiles.": "बड़ी मुस्कान।",
  "Explore sweets": "मिठाइयाँ देखें",
  "A little something extra?": "साथ में कुछ और?",
  "You can add more than one size or portion.": "आप एक से अधिक आकार या पोर्शन जोड़ सकते हैं।",
  "Choose options": "विकल्प चुनें",
  "Manage sizes": "आकार बदलें",
  "Manage": "बदलें",
  "Maximum price": "अधिकतम कीमत",
  "Items with size or portion choices": "आकार या पोर्शन वाले आइटम",
  "Show items": "आइटम देखें",
  "Filter menu": "मेन्यू फ़िल्टर करें",

  "Estimated total": "अनुमानित कुल राशि",
  "No pickup selected": "पिकअप नहीं चुना गया",
  "Time not selected": "समय नहीं चुना गया",
  "Browse and add items. Choose a pickup date and time before payment.": "वस्तुएँ देखें और कार्ट में जोड़ें। भुगतान से पहले पिकअप की तारीख और समय चुनें।",
  "Item availability is checked for the date shown above. Confirm your pickup at checkout.": "वस्तुओं की उपलब्धता ऊपर दी गई तारीख के लिए जाँची गई है। चेकआउट पर पिकअप की पुष्टि करें।",
  "Unavailable for selected pickup": "चुने हुए पिकअप पर उपलब्ध नहीं",
  "Confirm pickup": "पिकअप की पुष्टि करें",
  "Confirm pickup time": "पिकअप समय की पुष्टि करें",
  "Saved pickup — confirm this date and time before payment.": "सहेजा हुआ पिकअप — भुगतान से पहले इस तारीख और समय की पुष्टि करें।",
  "Your favourites, again": "आपके पसंदीदा स्वाद, फिर से",
  "Reorder for pickup": "पिकअप के लिए फिर ऑर्डर करें",
  "Current menu prices apply. The final price and offers are confirmed at checkout.": "मेन्यू की मौजूदा कीमतें लागू होंगी। अंतिम कीमत और ऑफ़र चेकआउट पर तय होंगे।",
  "Continue to checkout": "चेकआउट पर जाएँ",
  "Checking pickup…": "पिकअप की जाँच हो रही है…",
  "Weight (g)": "वज़न (ग्राम)",
  "A little Gokul in your feed": "आपकी फ़ीड में गोकुल की मिठास",
  "Fresh sweets, new favourites and moments from our kitchen.": "ताज़ी मिठाइयाँ, नए पसंदीदा स्वाद और हमारी रसोई की झलकियाँ।",
 "Choose where you’ll collect": "अपना पिकअप स्थान चुनें",
 "I will collect my order at this branch.": "मैं इसी शाखा से अपना ऑर्डर लूँगा।",
 "YOUR PICKUP BRANCH": "आपकी पिकअप शाखा",
 "What should we call you?": "हम आपको किस नाम से बुलाएँ?",
 "Add your name for a warmer welcome. It is optional.": "बेहतर स्वागत के लिए अपना नाम जोड़ें। यह वैकल्पिक है।",
 "Add your name": "अपना नाम जोड़ें",
 "completed visits": "पूरे हुए ऑर्डर",
 "Available to use": "इस्तेमाल के लिए उपलब्ध",
 "Use coins for a saving on your next eligible order.": "अगले योग्य ऑर्डर पर बचत के लिए कॉइन इस्तेमाल करें।",
 "Pending completion": "ऑर्डर पूरा होने पर मिलेंगे",
 "Choose your saving": "अपनी बचत चुनें",
 "Applied at checkout": "चेकआउट में लागू होगा",
 "Only one saving at a time. Offers apply after coins; fees are excluded.": "एक समय पर एक रिवॉर्ड चुनें। ऑफ़र कॉइन की छूट के बाद लागू होगा; शुल्क पर छूट नहीं है।",
 "Start with your current location": "अपने वर्तमान स्थान से शुरू करें",
 "Use my current location": "मेरा वर्तमान स्थान इस्तेमाल करें",
 "Booked the wrong order?": "गलत ऑर्डर हो गया?",
 "Customer cancellation is available for 10 minutes after payment confirmation. Only the food amount is refundable; additional charges and their taxes are retained.": "भुगतान की पुष्टि के बाद 10 मिनट तक ऑर्डर रद्द कर सकते हैं। केवल खाने की राशि वापस होगी; अतिरिक्त शुल्क और उनके कर वापस नहीं होंगे।",
 "Check the branch before paying. Customer cancellation is available for 10 minutes after payment confirmation. Only the food amount is refundable; additional charges and their taxes are retained.": "भुगतान से पहले शाखा जाँचें। भुगतान की पुष्टि के बाद 10 मिनट तक ऑर्डर रद्द कर सकते हैं। केवल खाने की राशि वापस होगी; अतिरिक्त शुल्क और उनके कर वापस नहीं होंगे।",

 "Install Gokul Sweets": "गोकुल स्वीट्स ऐप इंस्टॉल करें",
 "Gokul, one tap away": "गोकुल, बस एक टैप पर",
 "Keep your orders and rewards close.": "अपने ऑर्डर और रिवॉर्ड आसानी से देखें।",
 "Fresh favourites, right on your home screen.": "आपकी पसंद की ताज़ा मिठाइयाँ, अब होम स्क्रीन पर।",
 "Install App": "ऐप इंस्टॉल करें",
 "Close install banner": "इंस्टॉल सुझाव बंद करें",
 "Opening install options…": "इंस्टॉल विकल्प खुल रहे हैं…",
 "Close install instructions": "इंस्टॉल निर्देश बंद करें",
 "Add Gokul Sweets to your Home Screen": "गोकुल स्वीट्स को अपनी होम स्क्रीन पर जोड़ें",
 "A shortcut to the same Gokul you know. You can always keep using this website.": "आपके अपने गोकुल का शॉर्टकट। इस वेबसाइट से भी ऑर्डर कर सकते हैं।",
 "Tap Share": "Share पर टैप करें",
 "Open your browser’s Share menu.": "अपने ब्राउज़र का Share मेन्यू खोलें।",
 "Add to Home Screen": "Add to Home Screen",
 "Find this option in the Share menu.": "Share मेन्यू में यह विकल्प चुनें।",
 "Tap Add": "Add पर टैप करें",
 "Gokul Sweets will appear on your home screen.": "गोकुल स्वीट्स आपकी होम स्क्रीन पर दिखाई देगा।",
 "If this option is missing, open this page in Safari and use Share.": "यह विकल्प न मिले तो इस पेज को Safari में खोलें और Share चुनें।",
 "Got it": "समझ गया",
 "Installation could not be opened. You can keep ordering in your browser.": "इंस्टॉल विकल्प नहीं खुल सके। आप ब्राउज़र से ऑर्डर कर सकते हैं।",

 "Bulk order": "थोक ऑर्डर",
    "Bulk order requests": "थोक ऑर्डर अनुरोध",
    "Pickup orders": "पिकअप ऑर्डर",
    "Coming soon": "जल्द आ रहा है",
    "Celebrations & Gifts":"उत्सव और उपहार",
 "Choose your favourites from the menu to start your order.":"अपना ऑर्डर शुरू करने के लिए मेन्यू से अपनी पसंद चुनें।",
 "Log out":"लॉग आउट",
 "Branch home":"शाखा का मुख्य पृष्ठ",
 "Back to menu":"मेन्यू पर वापस जाएँ",
 "Requests & quotes":"अनुरोध और मूल्य प्रस्ताव",
 "Browse sweets, snacks and food":"मिठाइयाँ, नाश्ता और भोजन देखें",
 "View your cart":"अपना कार्ट देखें",
 "Plan bulk sweets and celebration gift boxes":"बड़ी मात्रा में मिठाइयों और उत्सव के उपहार बॉक्स की योजना बनाएँ",
 "About Gokul Sweets":"गोकुल स्वीट्स के बारे में",
  "Filters":"फ़िल्टर", "Price up to":"अधिकतम मूल्य", "Any price":"कोई भी मूल्य", "Portion choices":"आधा / पूरा विकल्प",
  "Add more":"और जोड़ें", "Change pickup":"पिकअप बदलें", "Offers & total":"छूट और कुल राशि",
  "Phone verified":"मोबाइल की पुष्टि हो गई", "Best available offer applied automatically":"सबसे अच्छी उपलब्ध छूट अपने आप लगी",
  "Your current menu price":"वर्तमान मेन्यू मूल्य", "Price details":"राशि का विवरण",
  "Total to pay":"भुगतान की कुल राशि", "Pay now":"अभी भुगतान करें", "Opening payment…":"भुगतान खुल रहा है…",
  "Continue your existing order":"मौजूदा ऑर्डर जारी रखें",
  "Your order is already reserved. Check its payment status before starting another checkout.":"आपका ऑर्डर आरक्षित है। नया चेकआउट शुरू करने से पहले उसकी भुगतान स्थिति देखें।",
  "Choose the matching branch before checking out.":"चेकआउट से पहले कार्ट वाली शाखा चुनें।",
  "Payment wasn’t completed. Your cart is saved; review it and try again.":"भुगतान पूरा नहीं हुआ। आपका कार्ट सुरक्षित है; जाँचकर फिर कोशिश करें।",
  "This checkout is saved for a safe retry. Its items and pickup are locked until the order is recovered.":"सुरक्षित पुनः प्रयास के लिए चेकआउट सेव है। ऑर्डर की पुष्टि तक वस्तुएँ और पिकअप नहीं बदल सकते।",

  "Cancel this payment?": "यह भुगतान रद्द करें?",
  "Keep payment": "भुगतान जारी रखें",
  "Confirm cancellation": "रद्द करने की पुष्टि करें",
  "We’ll check for a confirmed payment first. If it hasn’t completed, we’ll release the reservation and keep your cart ready to try again.": "पहले हम भुगतान की पुष्टि जाँचेंगे। भुगतान पूरा न होने पर आरक्षण हटेगा और आपका कार्ट फिर कोशिश करने के लिए सुरक्षित रहेगा।",
  "Ready to try again": "फिर कोशिश के लिए तैयार",
  "The previous payment didn’t complete. Your items are saved; review the current total before paying again.": "पिछला भुगतान पूरा नहीं हुआ। वस्तुएँ सुरक्षित हैं; फिर भुगतान से पहले वर्तमान राशि देखें।",

  "Fresh for your moments": "आपके खास पलों के लिए ताज़ा",
  "Tap to enter": "आगे बढ़ने के लिए टैप करें",
  "Sign in to checkout": "ऑर्डर के लिए लॉग इन करें",
  "Verify your phone to continue": "आगे बढ़ने के लिए मोबाइल की पुष्टि करें",
  "Your cart stays saved. Sign in once to fill your contact details and keep your orders together.": "आपका कार्ट सुरक्षित है। एक बार लॉग इन करके अपने विवरण भरें और सभी ऑर्डर एक जगह देखें।",
  "Sign in to fill your verified contact details and continue to payment.": "अपने सत्यापित संपर्क विवरण भरने और भुगतान करने के लिए लॉग इन करें।",
  "Sign-in is needed to place an order. Your cart is saved. Please try verification again shortly.": "ऑर्डर के लिए लॉग इन ज़रूरी है। आपका कार्ट सुरक्षित है। कुछ देर बाद पुष्टि फिर करें।",
  "Verification is unavailable right now. Your cart is saved; try again.": "अभी मोबाइल पुष्टि उपलब्ध नहीं है। आपका कार्ट सुरक्षित है; फिर कोशिश करें।",
  "Verify your phone to place orders and see your pickup code.": "ऑर्डर करने और पिकअप कोड देखने के लिए मोबाइल की पुष्टि करें।",
  "Payment didn’t complete": "भुगतान पूरा नहीं हुआ",
  "Your cart is saved. We’ll check the payment before opening a fresh checkout.": "आपका कार्ट सुरक्षित है। नया चेकआउट खोलने से पहले हम भुगतान की जाँच करेंगे।",
  "Retry checkout": "फिर चेकआउट करें",

  "Your name (optional)": "आपका नाम (ज़रूरी नहीं)",
  "Optional — we will use GOKUL_GUEST": "नाम खाली छोड़ सकते हैं",
  "more items": "और वस्तुएँ",
  "items": "वस्तुएँ",
  "Choose time": "समय चुनें",
  "Logout": "लॉग आउट",
  "Admin Portal": "प्रबंधन पोर्टल",
  "Admin menu": "प्रबंधन मेन्यू",
  "Admin tools": "प्रबंधन विकल्प",
  "Dashboard": "डैशबोर्ड",
  "Orders & customers": "ऑर्डर और ग्राहक",
  "Live orders": "चालू ऑर्डर",
  "Delivery dispatch": "डिलीवरी भेजें",
  "Occasion enquiries": "समारोह की पूछताछ",
  "Printer queue": "प्रिंटर की सूची",
  "Customers": "ग्राहक",
  "Privacy requests": "गोपनीयता अनुरोध",
  "Menu management": "मेन्यू प्रबंधन",
  "Products & categories": "वस्तुएँ और श्रेणियाँ",
  "Product images": "वस्तुओं की तस्वीरें",
  "Import menu": "मेन्यू आयात करें",
  "Tax categories": "कर श्रेणियाँ",
  "Storefront": "ग्राहक वेबसाइट",
  "About & people": "हमारे बारे में और टीम",
  "Homepage campaigns": "मुखपृष्ठ प्रचार",
  "Branch operations": "शाखा संचालन",
  "Branches & settings": "शाखाएँ और सेटिंग्स",
  "Pickup scheduling": "पिकअप समय की व्यवस्था",
  "Inventory": "स्टॉक",
  "Daily availability": "रोज़ की उपलब्धता",
  "Product policies": "वस्तुओं के नियम",
  "Future production": "आने वाले दिनों की तैयारी",
  "Production & ready stock": "उत्पादन और तैयार स्टॉक",
  "Team": "टीम",
  "Recruitment": "भर्ती",
  "Staff": "कर्मचारी",
  "Approvals": "अनुमोदन",
  "Payroll": "वेतन",
  "Reports": "रिपोर्ट",
  "My account": "मेरा खाता",
  "KITCHEN OPERATIONS · IST": "रसोई संचालन · भारतीय समय",
  "Plan, prepare, hand over": "योजना बनाएँ, तैयार करें, सौंपें",
  "Tap a status, then choose a date or pickup time. Future orders stay scheduled until preparation opens.": "स्थिति चुनें, फिर तारीख या पिकअप समय चुनें। आने वाले ऑर्डर तैयारी का समय होने पर खुलेंगे।",
  "Refresh plan": "योजना फिर देखें",
  "All orders": "सभी ऑर्डर",
  "Overdue": "देर हो गई",
  "Needs preparation": "तैयारी करनी है",
  "Scheduled future": "आने वाले ऑर्डर",
  "Service date": "ऑर्डर की तारीख",
  "All dates": "सभी तारीखें",
  "Pickup / delivery time": "पिकअप / डिलीवरी का समय",
  "All times": "सभी समय",
  "Show all": "सभी दिखाएँ",
  "Delivery": "डिलीवरी",
  "orders": "ऑर्डर",
  "waiting ·": "इंतज़ार में ·",
  "preparing ·": "तैयार हो रहे हैं ·",
  "ready": "तैयार हैं",
  "Start selected in KOT (": "चुने हुए ऑर्डर KOT में शुरू करें (",
  "Select eligible on this page": "इस पेज के तैयारी योग्य ऑर्डर चुनें",
  "Clear selection": "चयन हटाएँ",
  "Loading your kitchen plan…": "रसोई की योजना आ रही है…",
  "No orders in this view. Choose another status or service date.": "यहाँ कोई ऑर्डर नहीं है। दूसरी स्थिति या तारीख चुनें।",
  "Preparation opens": "तैयारी शुरू करने का समय",
  "View order": "ऑर्डर देखें",
  "Previous": "पिछला",
  "Page": "पेज",
  "·": "·",
  "matching orders · 20 per page": "मिलते हुए ऑर्डर · हर पेज पर 20",
  "Next": "अगला",
  "Updated": "आखिरी अपडेट",
  "Start": "शुरू करें",
  "orders in KOT?": "ऑर्डर KOT में?",
  "Each order is checked again. Future, cancelled or already-started orders are skipped.": "हर ऑर्डर फिर जाँचा जाएगा। आने वाले, रद्द या पहले से शुरू ऑर्डर छोड़ दिए जाएँगे।",
  "Keep current status": "अभी की स्थिति रखें",
  "Starting…": "शुरू हो रहा है…",
  "Confirm start": "शुरू करने की पुष्टि करें",
  "Kitchen alarm enabled": "रसोई का अलार्म चालू है",
  "Loading your page…": "आपका पेज लोड हो रहा है…",
  "Checking branch availability…": "शाखा की उपलब्धता जाँची जा रही है…",
  "Branch unavailable": "शाखा उपलब्ध नहीं है",
  "This branch": "यह शाखा",
  "Branch availability could not be checked": "शाखा की उपलब्धता जाँची नहीं जा सकी",
  "Please reconnect and try again, or choose another branch.": "कृपया दोबारा कनेक्ट करके कोशिश करें या दूसरी शाखा चुनें।",
  "This branch is temporarily closed for customer visits and new orders. Please choose another branch. Your placed orders remain available in order history.": "यह शाखा फिलहाल ग्राहकों और नए ऑर्डर के लिए बंद है। कृपया दूसरी शाखा चुनें। आपके पहले से दिए गए ऑर्डर ऑर्डर इतिहास में उपलब्ध रहेंगे।",
  "Choose another branch": "दूसरी शाखा चुनें",
  "Currently not operational": "अभी संचालन में नहीं है",
  "Sold out": "स्टॉक खत्म",
  "Available later": "बाद में उपलब्ध",
  "Resume kitchen sound": "रसोई की आवाज़ फिर शुरू करें",
  "Disable kitchen alarm": "रसोई का अलार्म बंद करें",
  "Enable kitchen alarm": "रसोई का अलार्म चालू करें",
  "orders need preparation. Start them in KOT to stop the alarm.": "ऑर्डर की तैयारी करनी है। अलार्म रोकने के लिए उन्हें KOT में शुरू करें।",
  "No orders need preparation. Alarm is watching for new work.": "अभी कोई तैयारी बाकी नहीं है। नए काम पर अलार्म बजेगा।",
  "Enable sound once per session. It repeats for Needs preparation and Overdue until staff start the orders in KOT.": "आवाज़ एक बार चालू करें। तैयारी वाले या देर हो चुके ऑर्डर KOT में शुरू करने तक अलार्म बजता रहेगा।",
  "Keep the PWA open for continuous sound. Locked-screen alerts use": "लगातार आवाज़ के लिए ऐप खुला रखें। स्क्रीन लॉक होने पर सूचना के लिए देखें",
  "staff push settings": "कर्मचारी सूचना सेटिंग्स",
  "; phone sound settings apply.": "; फ़ोन की आवाज़ सेटिंग्स लागू होंगी।",
  "Cannot check preparation alerts. Reconnect and refresh the orders.": "तैयारी की सूचना नहीं मिल रही। इंटरनेट जोड़ें और ऑर्डर फिर देखें।",
  "Sound was blocked. Enable the kitchen alarm again.": "आवाज़ नहीं चल सकी। रसोई का अलार्म फिर चालू करें।",
  "This device could not enable sound. Use staff push alerts.": "इस डिवाइस पर आवाज़ नहीं चली। कर्मचारी सूचनाएँ इस्तेमाल करें।",

  "Pickup": "पिकअप",
  "Your details": "आपकी जानकारी",
  "Review": "जाँच करें",
  "Checkout": "ऑर्डर पूरा करें",
  "Who's picking up?": "ऑर्डर कौन ले जाएगा?",
  "Enter the name and mobile number we should use for pickup identification and order updates.": "ऑर्डर लेने और जानकारी पाने के लिए नाम और मोबाइल नंबर दें।",
  "Pickup contact": "संपर्क जानकारी",
  "We'll use these details for pickup and order updates. Sign in to fill your verified contact, or continue as a guest.": "ऑर्डर की जानकारी इस नंबर पर मिलेगी। लॉग इन करें या बिना लॉग इन आगे बढ़ें।",
  "Pickup from": "यहाँ से लें",
  "Change": "बदलें",
  "Pickup time": "पिकअप का समय",
  "Order summary": "ऑर्डर का विवरण",
  "item": "वस्तु",
  "more item": "और वस्तु",
  "← Back to Pickup Time": "← पिकअप का समय बदलें",
  "Checkout not found": "यह ऑर्डर नहीं मिला",
  "We could not find the pending order for this checkout.": "इस भुगतान का अधूरा ऑर्डर नहीं मिला।",
  "Return to Cart": "कार्ट पर वापस जाएँ",
  "Pickup reservation expired": "पिकअप का समय समाप्त हुआ",
  "Your cart and customer details are still available.": "आपका कार्ट और संपर्क जानकारी सुरक्षित हैं।",
  "You do not need to add your items or enter your details again.": "वस्तुएँ या जानकारी दोबारा भरने की जरूरत नहीं है।",
  "Releasing expired pickup reservation...": "पुराना पिकअप समय खाली किया जा रहा है…",
  "The old pickup reservation has been released.": "पुराना पिकअप समय खाली हो गया है।",
  "Pickup reserved": "पिकअप समय सुरक्षित है",
  "Time remaining": "बाकी समय",
  "Your cart has been updated": "आपका कार्ट बदल गया है",
  "Continue from Cart": "कार्ट से आगे बढ़ें",
  "Finding your best offers...": "आपके लिए ऑफर ढूँढ रहे हैं…",
  "Pickup slot reserved": "पिकअप समय सुरक्षित है",
  "Complete checkout before your reservation expires.": "बाकी समय में ऑर्डर पूरा करें।",
  "remaining": "बाकी",
  "Hurry — less than 5 minutes remain to complete checkout.": "ऑर्डर पूरा करने के लिए 5 मिनट से कम बचे हैं।",
  "Offers & savings": "ऑफर और बचत",
  "Choose an eligible offer or add more items before payment.": "भुगतान से पहले ऑफर चुनें या और वस्तुएँ जोड़ें।",
  "Your order": "आपका ऑर्डर",
  "Order amount": "ऑर्डर की राशि",
  "Offer saving": "ऑफर से बचत",
  "Offer applied": "ऑफर लागू है",
  "You saved": "आपकी बचत",
  "Unable to continue": "आगे नहीं बढ़ सके",
  "Try checking offers again": "ऑफर दोबारा देखें",
  "Available now": "अभी उपलब्ध",
  "Your eligible offers": "आपके लिए उपलब्ध ऑफर",
  "No eligible offers right now": "अभी कोई ऑफर उपलब्ध नहीं है",
  "You can still continue normally to payment.": "आप बिना ऑफर के भुगतान कर सकते हैं।",
  "Best saving": "सबसे ज्यादा बचत",
  "Applied": "लागू है",
  "Save": "बचाएँ",
  "Pay after offer": "ऑफर के बाद भुगतान",
  "Minimum order": "न्यूनतम ऑर्डर",
  "Maximum saving": "अधिकतम बचत",
  "Add": "जोड़ें",
  "more to unlock": "और जोड़ने पर मिलेंगे",
  "savings.": "की बचत।",
  "Next reward unlocks at": "अगली बचत के लिए राशि",
  "Add items to unlock offer": "ऑफर के लिए वस्तुएँ जोड़ें",
  "✓ Applied": "✓ लागू है",
  "Amount to pay": "भुगतान की राशि",
  "Offer saving applied": "ऑफर की बचत लागू है",
  "Continue to Payment": "भुगतान करें",
  "Continue to payment": "भुगतान करें",
  "You can continue without applying an offer.": "आप बिना ऑफर लगाए आगे बढ़ सकते हैं।",
  "Preparing secure payment...": "सुरक्षित भुगतान तैयार हो रहा है…",
  "We are checking the latest order and payment status with the backend.": "ऑर्डर और भुगतान की स्थिति जाँची जा रही है।",
  "Payment could not be prepared": "भुगतान तैयार नहीं हो सका",
  "Your cart has not been cleared.": "आपका कार्ट सुरक्षित है।",
  "Check My Orders": "मेरे ऑर्डर देखें",
  "Secure checkout": "सुरक्षित भुगतान",
  "Payment": "भुगतान",
  "Order": "ऑर्डर",
  "Your cart changed after this payment was prepared.": "भुगतान तैयार होने के बाद आपका कार्ट बदल गया।",
  "Existing PhonePe payment found": "पहले शुरू किया गया PhonePe भुगतान मिला",
  "Refund in progress": "पैसे वापस किए जा रहे हैं",
  "Refund completed": "पैसे वापस हो गए",
  "Refund needs attention": "पैसे वापसी के लिए मदद चाहिए",
  "Please keep this order number for support:": "मदद के लिए यह ऑर्डर नंबर रखें:",
  "Payment failed": "भुगतान नहीं हुआ",
  "Payment time expired": "भुगतान का समय समाप्त हुआ",
  "Amount": "राशि",
  "Payment status": "भुगतान की स्थिति",
  "Payment ID": "भुगतान आईडी",
  "Provider transaction": "लेनदेन नंबर",
  "Payment deadline": "भुगतान की समय सीमा",
  "Payable amount includes a convenience fee of": "भुगतान की राशि में सुविधा शुल्क शामिल है:",
  "(including": "(जिसमें शामिल है",
  "fee tax).": "शुल्क पर टैक्स)।",
  "Check payment and release the unpaid pickup reservation. Keep your items for another attempt.": "भुगतान की जाँच करके बिना भुगतान वाला ऑर्डर रद्द करें। वस्तुएँ कार्ट में रहेंगी।",
  "Close the gateway first. A payment received after cancellation enters the refund process.": "पहले भुगतान विंडो बंद करें। रद्द करने के बाद मिला भुगतान वापस करने की प्रक्रिया में जाएगा।",
  "Continue payment": "भुगतान जारी रखें",
  "View Order Details": "ऑर्डर का विवरण देखें",
  "Do not retry the old payment.": "पुराना भुगतान दोबारा न करें।",
  "Retry settings": "दोबारा लोड करें",
  "Use standard pickup selection": "सामान्य पिकअप चयन करें",
  "Loading pickup options...": "पिकअप के विकल्प लोड हो रहे हैं…",
  "Choose pickup": "पिकअप चुनें",
  "Pick the date and time that works best for you. Available capacity updates automatically.": "अपनी सुविधा के अनुसार तारीख और समय चुनें। उपलब्ध समय अपने आप अपडेट होते हैं।",
  "Currently reserved for you": "आपके लिए सुरक्षित समय",
  "Pickup date": "पिकअप की तारीख",
  "Open the list and choose the most convenient available time.": "सूची में से अपनी सुविधा का उपलब्ध समय चुनें।",
  "Unable to load pickup times": "पिकअप समय लोड नहीं हुए",
  "Try again": "दोबारा कोशिश करें",
  "No pickup times available for this date.": "इस तारीख पर पिकअप समय उपलब्ध नहीं है।",
  "Selected time": "चुना गया समय",
  "priority left": "प्राथमिकता पिकअप बाकी",
  "Priority pickup available for": "प्राथमिकता पिकअप का शुल्क",
  "extra.": "अतिरिक्त।",
  "Pickup type": "पिकअप का प्रकार",
  "Normal Pickup": "सामान्य पिकअप",
  "Included in your order.": "ऑर्डर में शामिल है।",
  "Full": "पूरा भरा है",
  "Priority Pickup": "प्राथमिकता पिकअप",
  "Uses priority pickup capacity.": "प्राथमिकता पिकअप में से समय लिया जाएगा।",
  "Back to Cart": "कार्ट पर वापस जाएँ",
  "Quantity confirmation required": "मात्रा की पुष्टि जरूरी है",
  "We cannot confirm the complete order for this pickup date": "इस तारीख पर पूरे ऑर्डर की पुष्टि नहीं हो सकती",
  "Some products need more preparation or stock than is currently available online.": "कुछ वस्तुओं के लिए अभी उपलब्ध स्टॉक या तैयारी समय कम है।",
  "You requested": "आपकी माँगी गई मात्रा",
  "Available online": "ऑनलाइन उपलब्ध",
  "Please reduce the quantity, choose another date, or contact the branch for a large-order confirmation.": "मात्रा कम करें, दूसरी तारीख चुनें या बड़े ऑर्डर के लिए दुकान से संपर्क करें।",
  "Earliest available date": "सबसे पहली उपलब्ध तारीख",
  "Choose This Pickup Date": "यह तारीख चुनें",
  "Need this quantity specially prepared?": "ज्यादा मात्रा में बनवाना है?",
  "Call": "कॉल करें",
  "Adjust Cart Quantity": "मात्रा बदलें",
  "Your cart is empty": "आपका कार्ट खाली है",
  "Add some items before reviewing your order.": "पहले कार्ट में वस्तुएँ जोड़ें।",
  "Explore Menu": "मेन्यू देखें",
  "Branch mismatch": "दुकान अलग है",
  "Please select the branch associated with your cart.": "अपने कार्ट वाली दुकान चुनें।",
  "Select Branch": "दुकान चुनें",
  "Pickup time required": "पिकअप समय चुनना जरूरी है",
  "Select a pickup date and time before reviewing your order.": "पहले पिकअप की तारीख और समय चुनें।",
  "Choose Pickup": "पिकअप चुनें",
  "Customer details required": "संपर्क जानकारी जरूरी है",
  "Enter your name and phone number before reviewing your order.": "आगे बढ़ने के लिए संपर्क जानकारी दें।",
  "Enter Details": "जानकारी दें",
  "Review & offers": "ऑर्डर और ऑफर",
  "Almost there": "बस एक कदम बाकी",
  "Review your pickup order": "अपना ऑर्डर जाँचें",
  "Check your pickup time, contact details and items. Then check eligible offers or enter an exclusive code without leaving this page.": "पिकअप समय, संपर्क और वस्तुएँ जाँचें। इसी पेज पर ऑफर देखें या ऑफर कोड डालें।",
  "Pickup details": "पिकअप की जानकारी",
  "Normal capacity is full for this pickup time.": "इस समय सामान्य पिकअप पूरा भरा है।",
  "Priority charge:": "प्राथमिकता शुल्क:",
  "Change time": "समय बदलें",
  "Edit": "बदलें",
  "Priority pickup": "प्राथमिकता पिकअप",
  "No surprises at payment": "भुगतान से पहले पूरी राशि देखें",
  "See item prices, GST, any pickup charge and your savings together before you pay.": "वस्तुओं की कीमत, GST, पिकअप शुल्क और बचत भुगतान से पहले देखें।",
  "You're offline. Your cart is saved. Reconnect and check your final price again before continuing.": "इंटरनेट नहीं है। कार्ट सुरक्षित है। इंटरनेट आने पर पूरी राशि दोबारा जाँचें।",
  "Your price, before offers": "ऑफर से पहले राशि",
  "This price needs refreshing. Your cart and pickup details are saved.": "राशि दोबारा जाँचनी है। कार्ट और पिकअप सुरक्षित हैं।",
  "Items subtotal": "वस्तुओं की राशि",
  "GST": "GST",
  "Convenience fee (tax included)": "सुविधा शुल्क (टैक्स सहित)",
  "Final price": "अंतिम राशि",
  "Payable": "भुगतान की राशि",
  "Confirmed final amount": "पुष्ट अंतिम राशि",
  "I have reviewed the updated total and offers.": "मैंने नई राशि और ऑफर देख लिए हैं।",
  "Review updated total": "नई राशि जाँचें",
  "Review & reserve": "राशि देखकर आगे बढ़ें",
  "Check price & offers": "राशि और ऑफर जाँचें",
  "Checking your total…": "आपकी राशि जाँची जा रही है…",
  "Opening checkout…": "ऑर्डर का पेज खुल रहा है…",
  "Check your final price": "पूरी राशि जाँचें",
  "Review your total, then explore any available offers before paying.": "राशि जाँचें और भुगतान से पहले ऑफर देखें।",
  "← Back to Cart": "← कार्ट पर वापस जाएँ",
  "Adjust your pickup here": "पिकअप और मात्रा बदलें",
  "Your current reservation stays unchanged if the check fails. No payment is started here.": "जाँच नहीं होने पर पुराना पिकअप सुरक्षित रहेगा। यहाँ भुगतान शुरू नहीं होगा।",
  "Grams · minimum": "ग्राम · न्यूनतम",
  ", step": ", बढ़ोतरी",
  "Remove": "हटाएँ",
  "Choose an available time": "उपलब्ध समय चुनें",
  "Refresh available times": "उपलब्ध समय दोबारा देखें",
  "Keep current pickup": "पुराना पिकअप रखें",
  "Gokul Sweets": "गोकुल स्वीट्स",
  "FRESH FOR YOUR MOMENTS": "आपके हर पल में ताजगी",
  "PICKUP FROM": "यहाँ से लें",
  "Complete checkout before the timer ends.": "बाकी समय में ऑर्डर पूरा करें।",
  "Choose a new pickup time before continuing. Your cart is still available.": "आगे बढ़ने के लिए नया पिकअप समय चुनें। कार्ट सुरक्षित है।",
  "Your cart has changed": "कार्ट बदल गया है",
  "Review changes here": "बदलाव यहाँ देखें",
  "Save on this order": "इस ऑर्डर पर बचत करें",
  "See offers available for this order": "इस ऑर्डर के ऑफर देखें",
  "We'll check the server using your final cart value, branch, pickup type and eligibility.": "आपकी वस्तुओं, दुकान और पिकअप के अनुसार ऑफर जाँचे जाएँगे।",
  "Find available offers": "ऑफर देखें",
  "No public offers available": "अभी कोई सार्वजनिक ऑफर नहीं है",
  "Have a creator, partner or promotional code? You can still enter it below.": "ऑफर कोड है? नीचे डालें।",
  "Applied ✓": "लागू है ✓",
  "more to unlock the next saving level.": "और जोड़ने पर अगली बचत मिलेगी।",
  "Have a creator or exclusive code?": "आपके पास ऑफर कोड है?",
  "Enter a code shared by an influencer, partner, event or private campaign.": "आपको मिला ऑफर कोड यहाँ डालें।",
  "Offer applied ✓": "ऑफर लागू है ✓",
  "Adjust quantities or pickup": "मात्रा या पिकअप बदलें",
  "Recheck current cart and total": "कार्ट और राशि दोबारा जाँचें",
  "Your name": "आपका नाम",
  "Mobile number": "मोबाइल नंबर",
  "Continue to Review": "ऑर्डर जाँचें",
  "Before you leave payment": "भुगतान से वापस जाने से पहले",
  "Keep this order to pay later, or check payment and cancel the unpaid reservation now. Your cart stays saved. A confirmed payment will preserve the order.": "बाद में भुगतान के लिए ऑर्डर रखें या भुगतान जाँचकर अभी रद्द करें। कार्ट सुरक्षित रहेगा। भुगतान हो चुका है तो ऑर्डर रद्द नहीं होगा।",
  "Stay & retry payment": "रुकें और भुगतान करें",
  "Leave & keep order for later": "वापस जाएँ और ऑर्डर रखें",
  "Cancel order & keep cart": "ऑर्डर रद्द करें, कार्ट रखें",
  "Cancel this order": "यह ऑर्डर रद्द करें",
  "Check Payment Status": "भुगतान की स्थिति देखें",
  "A little extra for your pickup": "ऑर्डर में कुछ और जोड़ें",
  "Pairs well with your order": "आपके ऑर्डर के साथ अच्छा रहेगा",
  "No thanks": "नहीं, धन्यवाद",
  "· including item tax": "· वस्तु का टैक्स शामिल है",
  "Reaches this offer's spend threshold": "इस ऑफर के लिए जरूरी राशि पूरी होती है",
  "Optional additions at the menu price. Price and pickup availability are checked again before payment.": "मेन्यू की कीमत पर अपनी पसंद से जोड़ें। भुगतान से पहले राशि और पिकअप दोबारा जाँचे जाएँगे।",
  "Adjust quantities or pickup here": "यहीं मात्रा या पिकअप बदलें",
  "Checking product availability for this date…": "इस तारीख के लिए उपलब्धता जाँची जा रही है…",
  "Availability could not be confirmed": "उपलब्धता की पुष्टि नहीं हो सकी",
  "Some items need your attention": "कुछ वस्तुओं को जाँचें",
  "Requested:": "माँगी गई मात्रा:",
  "· Available:": "· उपलब्ध:",
  "Choose": "चुनें",
  "instead": "के बदले",
  "Planning a large order?": "बड़ा ऑर्डर करना है?",
  "Choose a date": "तारीख चुनें",
  "Choose a time": "समय चुनें",
  "Choose your pickup": "पिकअप चुनें",
  "Review your cart": "कार्ट देखें",
  "Add items from the menu first": "पहले मेन्यू से वस्तुएँ जोड़ें",
  "Retry": "दोबारा कोशिश करें",
  "Continue": "आगे बढ़ें",
  "Checking...": "जाँच रहे हैं…",
  "Checking…": "जाँच रहे हैं…",
  "Loading…": "लोड हो रहा है…",
  "Loading...": "लोड हो रहा है…",
  "Menu": "मेन्यू",
  "Home": "होम",
  "Cart": "कार्ट",
  "My Orders": "मेरे ऑर्डर",
  "My orders": "मेरे ऑर्डर",
  "Account": "खाता",
  "Log in": "लॉग इन",
  "Help": "मदद",
  "Profile": "प्रोफाइल",
  "View cart": "कार्ट देखें",
  "View Cart": "कार्ट देखें",
  "Add to cart": "कार्ट में जोड़ें",
  "Add to Cart": "कार्ट में जोड़ें",
  "Your cart": "आपका कार्ट",
  "Choose a shop": "दुकान चुनें",
  "All": "सभी",
  "All items": "सभी वस्तुएँ",
  "Search menu": "मेन्यू में खोजें",
  "Checkout action": "ऑर्डर पूरा करें",
  "Review before payment": "भुगतान से पहले जाँचें",
  "Payable total": "भुगतान की राशि",
  "Check your total": "पूरी राशि देखें",
  "Phone verification": "मोबाइल सत्यापन",
  "Checking phone verification…": "मोबाइल सत्यापन जाँच रहे हैं…",
  "Sign in": "लॉग इन",
  "Continue as guest": "बिना लॉग इन आगे बढ़ें",
  "Enter your name": "अपना नाम लिखें",
  "Enter 10-digit mobile number": "10 अंकों का मोबाइल नंबर लिखें",
  "Please enter your name.": "अपना नाम लिखें।",
  "Enter a valid 10-digit mobile number.": "सही 10 अंकों का मोबाइल नंबर लिखें।",
  "Your verified number is used for order updates and pickup identification.": "ऑर्डर की जानकारी और पहचान के लिए आपका सत्यापित नंबर उपयोग होगा।",
  "We’ll use this number for order updates and pickup identification.": "ऑर्डर की जानकारी और पहचान के लिए यह नंबर उपयोग होगा।",
  "Pay": "भुगतान करें",
  "Retry payment": "फिर भुगतान करें",
  "Offers": "ऑफर",
  "Details": "जानकारी",
  "Preparing": "तैयार हो रहा है",
  "Ready": "तैयार है",
  "Confirmed": "पुष्ट है",
  "Pending": "बाकी है",
  "Close": "बंद करें",
  "Back": "वापस",
  "Cancel": "रद्द करें",
  "Refresh": "दोबारा लोड करें",
  "Today": "आज",
  "Tomorrow": "कल",
  "Normal": "सामान्य",
  "Priority": "प्राथमिकता",
  "Adjust cart quantities": "कार्ट की मात्रा बदलें",
  "Priority available": "प्राथमिकता उपलब्ध है",
  "normal": "सामान्य",
  "priority": "प्राथमिकता",
  "Normal pickup": "सामान्य पिकअप",
  "Select pickup time": "पिकअप का समय चुनें",
  "Tap to view available slots": "उपलब्ध समय देखने के लिए दबाएँ",
  "Your cart and details are saved. Pick a time that works for everything in your order.": "कार्ट और जानकारी सुरक्षित हैं। पूरे ऑर्डर के लिए उपलब्ध समय चुनें।",
  "Finding available times…": "उपलब्ध समय ढूँढ रहे हैं…",
  "Try finding times again": "समय दोबारा ढूँढें",
  "No other times are available for this cart right now. Try another date or contact the branch.": "अभी इस कार्ट के लिए दूसरा समय नहीं है। दूसरी तारीख चुनें या दुकान से संपर्क करें।",
  "See all pickup times": "सभी पिकअप समय देखें",
  "Your previous pickup has passed. Showing today’s available times. Your cart is saved.": "पुराना पिकअप समय निकल गया। आज के समय दिखा रहे हैं। कार्ट सुरक्षित है।",
  "Branch & menu": "दुकान और मेन्यू",
  "/ Review": "/ जाँचें",
  "Some items aren’t available at your selected pickup time. Choose another time or remove those items. Your pickup hasn’t changed.": "चुने हुए पिकअप समय पर कुछ वस्तुएँ उपलब्ध नहीं हैं। दूसरा समय चुनें या उन वस्तुओं को हटाएँ। आपका पिकअप बदला नहीं गया है।",
  "Choose when you’ll collect your order. Check the date and time before continuing.": "ऑर्डर लेने की तारीख और समय चुनें। आगे बढ़ने से पहले दोनों जाँच लें।",
  "Choose a date, then tap a pickup time. Nothing changes until you confirm.": "पहले तारीख चुनें, फिर पिकअप समय पर टैप करें। आपकी पुष्टि के बाद ही बदलाव होगा।",
  "No pickup times available for these items on this date. Try another date or remove items.": "इस तारीख पर इन वस्तुओं के लिए पिकअप समय उपलब्ध नहीं है। दूसरी तारीख चुनें या वस्तुएँ हटाएँ।",
  "Your pickup time has passed. Choose another time. Your pickup hasn’t changed.": "आपका पिकअप समय बीत चुका है। दूसरा समय चुनें। आपका पिकअप बदला नहीं गया है।",
  "Choose a pickup time to see your final total.": "अंतिम कुल राशि देखने के लिए पिकअप का समय चुनें।",
  "Choose pickup time": "पिकअप समय चुनें",
  "Your selected pickup date": "आपकी चुनी हुई पिकअप तारीख",
  "Your selected pickup": "आपका चुना हुआ पिकअप",
  "Checking your selected pickup…": "आपके चुने हुए पिकअप की जाँच हो रही है…",
  "Your selected pickup cannot fulfil this cart. Choose and confirm another date and time, or remove items. We have not changed your pickup.": "इस कार्ट की सभी वस्तुएँ चुने हुए पिकअप पर उपलब्ध नहीं हैं। दूसरी तारीख और समय चुनकर पुष्टि करें, या वस्तुएँ हटाएँ। आपका पिकअप बदला नहीं गया है।",
  "Choose and confirm a pickup date and time to enable payment.": "भुगतान करने के लिए पिकअप की तारीख और समय चुनकर पुष्टि करें।",
  "Pickup at": "पिकअप",
  "Choose when to collect": "ऑर्डर लेने का समय चुनें",
  "Times are checked for your whole cart at": "पूरे कार्ट के लिए समय जाँचे जाते हैं:",
  ". Your order is reserved at checkout.": "। आगे बढ़ने पर ऑर्डर का समय सुरक्षित होगा।",
  "Your cart belongs to a different branch.": "कार्ट दूसरी दुकान का है।",
  "before continuing.": "फिर आगे बढ़ें।",
  "Your cart is preserved. Checkout will still validate availability.": "कार्ट सुरक्षित है। ऑर्डर पूरा करते समय उपलब्धता फिर जाँची जाएगी।",
  "Checking dates and times for your cart...": "कार्ट के लिए तारीख और समय जाँचे जा रहे हैं…",
  "Next pickup for all items:": "सभी वस्तुओं के लिए अगला पिकअप:",
  "Approved for future preparation": "आगे की तैयारी के लिए उपलब्ध",
  "- pickup times": "– पिकअप समय",
  "Edit quantities or remove items in your cart": "कार्ट में मात्रा बदलें या वस्तुएँ हटाएँ",
  "Available pickup times": "उपलब्ध पिकअप समय",
  "No matching times on this date. Try another date above.": "इस तारीख पर समय नहीं है। ऊपर दूसरी तारीख चुनें।",
  "Only times that fit every item in your cart are selectable. All times are India time.": "पूरे कार्ट के लिए उपलब्ध समय ही चुने जा सकते हैं। सभी समय भारतीय समय हैं।",
  "Why are": "क्यों हैं",
  "other times not available?": "बाकी समय उपलब्ध नहीं?",
  "Also:": "साथ ही:",
  "items · INR": "वस्तुएँ · ₹",
  "before tax": "टैक्स से पहले",
  "at": "पर",
  "Branches": "दुकानें",
  "menu": "मेन्यू",
  "Freshly made for the moments that matter. Order online, then collect from your chosen branch.": "अपने खास पलों के लिए ताजा स्वाद। ऑनलाइन ऑर्डर करें और चुनी हुई दुकान से लें।",
  "EXPLORE": "देखें",
  "Our story": "हमारी कहानी",
  "YOUR ORDER": "आपका ऑर्डर",
  "Orders": "ऑर्डर",
  "Pickup only": "दुकान से पिकअप",
  "GOOD TO KNOW": "जरूरी जानकारी",
  "Choose a branch to see its live menu.": "मेन्यू देखने के लिए दुकान चुनें।",
  "Pickup times and the full price are confirmed before payment.": "भुगतान से पहले पिकअप समय और पूरी राशि की पुष्टि होगी।",
  "Made with care, ready for pickup.": "प्यार से तैयार, आपके लिए तैयार।",
  "Fresh sweets. Happier moments.": "ताजा मिठाइयाँ, खुशियों के पल।",
  "PICKUP BRANCH": "पिकअप की दुकान",
  "Tradition tastes better": "परंपरा का स्वाद",
  "Soon": "जल्द",
  "Staff dashboard": "स्टाफ डैशबोर्ड",
  "Follow us": "हमसे जुड़ें",
  "New sweets, festive specials and shop updates.": "नई मिठाइयाँ, त्योहारों के खास स्वाद और दुकान की खबरें।",
  "Online orders are prepared for pickup from your selected branch.": "ऑनलाइन ऑर्डर आपकी चुनी दुकान से पिकअप के लिए तैयार होते हैं।",
  "Pickup ·": "पिकअप ·",
  "· Time is checked again at checkout": "· ऑर्डर पूरा करते समय दोबारा समय जाँचा जाएगा",
  "Change branch": "दुकान बदलें",
  "Stay connected": "हमसे जुड़े रहें",
  "Follow Gokul Sweets": "गोकुल स्वीट्स से जुड़ें",
  "Not now": "अभी नहीं",
  "Browse menu": "मेन्यू देखें",
  "Freshly made.": "ताजा तैयार।",
  "Ready for you.": "आपके लिए।",
  "Occasions & gifting": "समारोह और उपहार",
  "Branch details": "दुकान की जानकारी",
  "Good taste starts here": "अच्छे स्वाद की शुरुआत यहाँ से",
  "Sweet moments.": "मिठास भरे पल।",
  "Savour every bite.": "हर निवाले का आनंद लें।",
  "Order Now": "ऑर्डर करें",
  "Explore delivery by area": "अपने क्षेत्र में डिलीवरी देखें",
  "On the menu": "मेन्यू में",
  "Take a look": "देखें",
  "Find your favourites": "अपनी पसंद चुनें",
  "Pick your time": "समय चुनें",
  "Collect & enjoy": "दुकान से लें और आनंद लें",
  "Something for every mood": "हर मन के लिए कुछ खास",
  "What are you craving?": "आज क्या खाना चाहेंगे?",
  "View menu": "मेन्यू देखें",
  "Choose a branch to see its menu and prices.": "मेन्यू और कीमत देखने के लिए दुकान चुनें।",
  "Loading your branch menu...": "दुकान का मेन्यू लोड हो रहा है…",
  "Open menu": "मेन्यू खोलें",
  "No items are currently available at this branch.": "इस दुकान पर अभी वस्तुएँ उपलब्ध नहीं हैं।",
  "Discover on the menu": "मेन्यू में देखें",
  "Choose your favourites. We'll show pickup dates that fit your whole cart.": "अपनी पसंद चुनें। पूरे कार्ट के लिए उपलब्ध पिकअप तारीखें दिखाएँगे।",
  "Order for later": "आगे के लिए ऑर्डर करें",
  "Gokul specials": "गोकुल के खास स्वाद",
  "Our branches": "हमारी दुकानें",
  "Order food": "खाना ऑर्डर करें",
  "Plan an occasion": "समारोह की योजना बनाएँ",
  "Scroll to explore": "नीचे और देखें",
  "OUR BRANCHES": "हमारी दुकानें",
  "Your next visit starts here.": "आपकी अगली मुलाकात यहाँ से शुरू होती है।",
  "Choose a Gokul branch near you to see its live menu and pickup choices.": "मेन्यू और पिकअप के लिए अपने पास की गोकुल दुकान चुनें।",
  "Explore this branch": "यह दुकान देखें",
  "Pickup location required": "पिकअप की दुकान चुनें",
  "Select your pickup branch": "पिकअप की दुकान चुनें",
  "Your branch determines which products, prices and pickup options are available.": "वस्तुएँ, कीमत और पिकअप समय चुनी दुकान के अनुसार होंगे।",
  "Choose Branch": "दुकान चुनें",
  "Freshly prepared": "ताजा तैयार",
  "Pickup branch": "पिकअप की दुकान",
  "Clear filters": "फिल्टर हटाएँ",
  "No matching items": "कोई वस्तु नहीं मिली",
  "Try another search or category to see more of the menu.": "कुछ और खोजें या दूसरी श्रेणी चुनें।",
  "Show all items": "सभी वस्तुएँ देखें",
  "Unable to load menu": "मेन्यू लोड नहीं हुआ",
  "Find a favourite": "अपनी पसंद खोजें",
  "pickup · Change time": "पिकअप · समय बदलें",
  "Your previous pickup has passed. Choose a new date; your cart is saved.": "पुराना पिकअप समय निकल गया। नई तारीख चुनें। कार्ट सुरक्षित है।",
  "Choose pickup to check availability. Browse and build your cart first if you prefer.": "उपलब्धता के लिए पिकअप चुनें। चाहें तो पहले मेन्यू से कार्ट बनाएँ।",
  "That pickup date has passed. Choose a new date; your cart is saved.": "यह तारीख निकल गई। नई तारीख चुनें। कार्ट सुरक्षित है।",
  "Checking your pickup date...": "पिकअप तारीख जाँची जा रही है…",
  "Live preview, not a reservation.": "अभी केवल उपलब्धता दिखाई गई है। समय सुरक्षित नहीं हुआ है।",
  "Your saved pickup time no longer fits this selection.": "चुना समय इस ऑर्डर के लिए अब उपलब्ध नहीं है।",
  "Choose another time": "दूसरा समय चुनें",
  ". Your cart is unchanged.": "। कार्ट में कोई बदलाव नहीं हुआ।",
  "Review these items for your pickup": "पिकअप के लिए इन वस्तुओं को जाँचें",
  "Edit quantities or remove items below, or keep your cart and find another pickup.": "नीचे मात्रा बदलें या वस्तुएँ हटाएँ, या कार्ट रखकर दूसरा पिकअप चुनें।",
  "Find a time for all items": "सभी वस्तुओं के लिए समय ढूँढें",
  "New · No ratings yet": "नया · अभी कोई रेटिंग नहीं",
  "/kg": "/किलो",
  "From": "से",
  "for": "के लिए",
  "ADD": "जोड़ें",
  "No items found": "कोई वस्तु नहीं मिली",
  "Try another category or search term.": "दूसरी श्रेणी या शब्द से खोजें।",
  "Choose quantity": "मात्रा चुनें",
  "Quick select": "जल्दी चुनें",
  "Enter exact quantity": "अपनी मात्रा लिखें",
  "Minimum": "न्यूनतम",
  "steps": "की बढ़ोतरी",
  "Estimated price": "अनुमानित राशि",
  "Final amount is calculated by Gokul Sweets using the selected weight.": "चुने हुए वजन के अनुसार गोकुल स्वीट्स अंतिम राशि की गणना करेगा।",
  "Review items for this branch": "इस दुकान के लिए वस्तुएँ जाँचें",
  "Your original cart is saved. Checkout is paused until you confirm the items for this branch.": "पुराना कार्ट सुरक्षित है। इस दुकान की वस्तुओं की पुष्टि के बाद आगे बढ़ें।",
  "Checking menu and stock...": "मेन्यू और स्टॉक जाँचे जा रहे हैं…",
  "No pickup time has capacity for this date. Choose another date.": "इस तारीख पर पिकअप नहीं है। दूसरी तारीख चुनें।",
  "Clear cart and choose again": "कार्ट खाली करके फिर चुनें",
  "Delete": "हटाएँ",
  "Item total": "वस्तु की राशि",
  "Items": "वस्तुएँ",
  "Select the pickup branch associated with this cart to continue.": "आगे बढ़ने के लिए कार्ट वाली दुकान चुनें।",
  "Continue to Pickup Time": "पिकअप समय चुनें",
  "You can still review your order before payment.": "भुगतान से पहले आप ऑर्डर जाँच सकेंगे।",
  "Pickup date:": "पिकअप तारीख:",
  "Keep current selection": "पुराना चयन रखें",
  "Close and retry": "बंद करके फिर कोशिश करें",
  "Nothing here yet": "अभी कार्ट खाली है",
  "Add your favourite sweets, snacks and meals, then choose a convenient pickup time.": "अपनी पसंद की मिठाइयाँ, नाश्ता और खाना जोड़ें, फिर पिकअप समय चुनें।",
  "Your pickup order": "आपका पिकअप ऑर्डर",
  "ready for review": "जाँच के लिए तैयार",
  "Clear cart": "कार्ट खाली करें",
  "Selected pickup branch": "चुनी गई पिकअप दुकान",
  "Cart branch mismatch": "कार्ट की दुकान अलग है",
  "← Add more items": "← और वस्तुएँ जोड़ें",
  "Your cart is saved. Reconnect before choosing a pickup time.": "कार्ट सुरक्षित है। इंटरनेट आने पर पिकअप समय चुनें।",
  "Preparing your order...": "ऑर्डर तैयार हो रहा है…",
  "Refresh your total": "राशि दोबारा जाँचें",
  "Accept price and reserve pickup": "राशि स्वीकार करके आगे बढ़ें",
  "Check Final Price & Offers": "राशि और ऑफर जाँचें",
  "Before paying": "भुगतान से पहले",
  "The reservation timer does not restart when you add items.": "वस्तुएँ जोड़ने पर पिकअप का बाकी समय नहीं बढ़ेगा।",
  "The reserved checkout time has ended. Your cart is still safe. We are making sure the old pickup reservation has been released before you choose a new slot.": "ऑर्डर पूरा करने का समय समाप्त हुआ। कार्ट सुरक्षित है। नया पिकअप चुनने से पहले पुराने समय की जाँच हो रही है।",
  "Your pickup reservation is still being held. Continue checkout so we can update this same order with your latest cart.": "आपका पिकअप सुरक्षित है। बदले हुए कार्ट के साथ इसी ऑर्डर को अपडेट करने के लिए आगे बढ़ें।",
  "Your pickup reservation stays active while you review offers or add items. The timer does not restart when the cart changes.": "ऑफर देखते समय पिकअप सुरक्षित है। कार्ट बदलने पर बाकी समय नहीं बढ़ेगा।",
  "Do not pay this stale checkout. Return to the cart and continue checkout so the backend can validate the current items.": "इस पुराने कार्ट के लिए भुगतान न करें। कार्ट पर लौटकर नया ऑर्डर जाँचें।",
  "We recovered the payment from the backend. The browser no longer has the original checkout link, so we will continue checking the existing PhonePe payment instead of creating a duplicate payment.": "पहले शुरू हुआ PhonePe भुगतान मिल गया है। नया भुगतान बनाने के बजाय उसकी स्थिति जाँचेंगे।",
  "This page checks our backend automatically. You can also check again manually.": "इस पेज पर स्थिति अपने आप अपडेट होती है। आप खुद भी दोबारा जाँच सकते हैं।",
  "The automatic refund did not reach a successful final state. Your old order has not been restored and no": "पैसे वापसी की पुष्टि नहीं हुई। पुराना ऑर्डर फिर चालू नहीं किया गया और कोई",
  "The order is no longer holding its": "इस ऑर्डर के लिए अब सुरक्षित नहीं है:",
  ". Your cart is still available.": "। आपका कार्ट सुरक्षित है।",
  "If the payment provider later reports that money was actually captured, the backend automatically starts the refund reconciliation flow.": "अगर बाद में भुगतान मिलने की पुष्टि होती है, तो पैसे वापसी की प्रक्रिया अपने आप शुरू होगी।",
  "reservation has been released. Your cart is still safe, so you can choose a new": "समय खाली हो गया है। कार्ट सुरक्षित है, नया समय चुनें:",
  "If the payment provider later reports a captured payment, the backend will move it into automatic refund reconciliation instead of confirming this expired order.": "बाद में भुगतान मिलने पर इस समाप्त ऑर्डर को पुष्ट करने के बजाय पैसे वापसी की प्रक्रिया होगी।",
  "This payment window has closed. Please check its status before starting a new checkout. If you paid, it may take a little longer to confirm.": "यह भुगतान विंडो बंद हो गई। फिर से ऑर्डर करने से पहले भुगतान की स्थिति जाँचें। भुगतान किया है तो पुष्टि में थोड़ा समय लग सकता है।",
  "Your order is confirmed only after our backend verifies a successful payment. Closing or going back from the payment window does not directly cancel the order.": "भुगतान की पुष्टि के बाद ही ऑर्डर पुष्ट होगा। विंडो बंद करने या वापस जाने से ऑर्डर अपने आप रद्द नहीं होता।",
  "Keep this time or choose another available time below. Your current reservation remains safe until the change succeeds.": "पुराना समय रखें या नीचे दूसरा समय चुनें। बदलाव की पुष्टि तक पुराना पिकअप सुरक्षित रहेगा।",
  "Please call the selected branch. Our team can check production capacity and confirm whether this large order can be prepared.": "दुकान को कॉल करें। टीम बड़े ऑर्डर की तैयारी और उपलब्धता की पुष्टि करेगी।",
  "Your reservation is unchanged if provider verification failed. You can retry the check or stay on payment.": "भुगतान की जाँच नहीं होने पर पुराना पिकअप सुरक्षित है। दोबारा जाँचें या भुगतान पेज पर रहें।",
  "No online date within the current booking window can confirm the complete quantity. Please call the branch so the team can check production capacity.": "अभी ऑनलाइन उपलब्ध तारीखों में पूरी मात्रा नहीं मिल सकती। तैयारी की जानकारी के लिए दुकान को कॉल करें।",
  "Fresh sweets, snacks and meals from your chosen branch. Browse the live menu and choose a pickup time at checkout.": "चुनी दुकान से ताजा मिठाइयाँ, नाश्ता और खाना। मेन्यू देखें और ऑर्डर करते समय पिकअप चुनें।",
  "See new sweets, festive specials and shop updates on our social pages.": "सोशल पेज पर नई मिठाइयाँ, त्योहारों के खास स्वाद और दुकान की खबरें देखें।",
  "Branch details will appear here when available. You can still explore the menu.": "दुकान की जानकारी उपलब्ध होने पर यहाँ दिखेगी। आप अभी मेन्यू देख सकते हैं।",
  "Taxes and any priority pickup charge depend on the time you choose at checkout. Review the final amount before paying.": "टैक्स और प्राथमिकता शुल्क चुने समय के अनुसार होंगे। भुगतान से पहले पूरी राशि देखें।",
  "The cart stays saved. Unavailable lines need attention before checkout.": "कार्ट सुरक्षित है। आगे बढ़ने से पहले उपलब्ध न होने वाली वस्तुएँ जाँचें।",
  "These cart items belong to another pickup branch. Select the matching branch before continuing, or clear the cart and start a new order from this branch.": "ये वस्तुएँ दूसरी दुकान की हैं। वह दुकान चुनें या कार्ट खाली करके यहाँ से नया ऑर्डर बनाएँ।",
  "Opening…": "पेज खुल रहा है…",
  "Opening secure payment…": "सुरक्षित भुगतान खुल रहा है…",
  "Online ordering is taking longer to connect.": "ऑनलाइन ऑर्डर जुड़ने में थोड़ा समय लग रहा है।",
  "We couldn't check this pickup time. Your cart is saved. Try again.": "पिकअप समय की जाँच नहीं हो सकी। कार्ट सुरक्षित है। दोबारा कोशिश करें।",
  "Your cart or pickup choice changed. Review the updated times before continuing.": "कार्ट या पिकअप बदल गया। आगे बढ़ने से पहले नया समय जाँचें।",
  "That time has just changed. Your cart is safe; choose another available time below.": "यह समय अभी बदल गया। कार्ट सुरक्षित है। नीचे दूसरा समय चुनें।",
  "We couldn’t check your total. Tap Check price & offers to try again.": "राशि की जाँच नहीं हो सकी। राशि और ऑफर जाँचें दबाकर फिर कोशिश करें।",
  "Please select a pickup date and time.": "पिकअप की तारीख और समय चुनें।",
  "Please enter your customer details.": "अपनी संपर्क जानकारी दें।",
  "Please enter a valid 10-digit Indian mobile number.": "सही 10 अंकों का भारतीय मोबाइल नंबर लिखें।",
  "Please enter a valid customer name.": "सही नाम लिखें।",
  "Select a pickup date and an available pickup time before continuing.": "आगे बढ़ने से पहले तारीख और उपलब्ध पिकअप समय चुनें।",
  "Your cart has changed. Review the updated cart before payment.": "कार्ट बदल गया। भुगतान से पहले नया कार्ट जाँचें।",
  "Your pickup reservation has expired. Please choose a pickup slot again.": "पिकअप का समय समाप्त हुआ। नया समय चुनें।",
  "Enter a valid quantity or weight using the shown minimum and step.": "दिखाई गई न्यूनतम मात्रा और बढ़ोतरी के अनुसार मात्रा लिखें।",
  "Choose a current available pickup time.": "अभी उपलब्ध पिकअप समय चुनें।",
  "Choose a pickup date within the available India dates.": "उपलब्ध भारतीय तारीखों में से पिकअप चुनें।",
  "Keep at least one item, or cancel your order using the order actions.": "कम से कम एक वस्तु रखें या ऑर्डर रद्द करें।",
  "Phone verification is unavailable": "मोबाइल सत्यापन उपलब्ध नहीं है",
  "Log in to your account": "अपने खाते में लॉग इन करें",
  "Need to stop this checkout?": "यह ऑर्डर रोकना है?",
  "Checking payment…": "भुगतान जाँचा जा रहा है…",
  "Check & retry checkout": "जाँचकर नया प्रयास करें",
  "Ready when you are. Tap Pay to open secure checkout.": "भुगतान के लिए तैयार है। सुरक्षित भुगतान खोलने के लिए भुगतान करें दबाएँ।",
  "Closing the payment window does not cancel your order immediately.": "भुगतान विंडो बंद करने से ऑर्डर अपने आप रद्द नहीं होता।",
  "Payment pending": "भुगतान बाकी है",
  "Payment successful": "भुगतान सफल हुआ",
  "Loading your order…": "आपका ऑर्डर लोड हो रहा है…",
  "No orders yet": "अभी कोई ऑर्डर नहीं है",
  "Times available": "समय उपलब्ध है",
  "No matching time": "उपयुक्त समय नहीं है",
  "No matching times on this date": "इस तारीख पर उपयुक्त समय नहीं है",
  "Total before optional offers": "ऑफ़र लगाने से पहले कुल राशि",
  "This price is available until": "यह राशि इस समय तक मान्य है",
  "See the cancellation policy": "ऑर्डर रद्द करने के नियम देखें",
  "before paying.": "भुगतान करने से पहले।",
  "Tax": "कर",
  "Pickup charge": "पिकअप शुल्क",
};

Object.assign(hindi, {
  "Log in": "लॉग इन",
  "Account": "मेरा खाता",
  "Log in to your account": "अपने खाते में लॉग इन करें",
  "Your Gokul profile": "आपका गोकुल खाता",
  "All your Gokul moments, together.": "आपके ऑर्डर और पसंद, एक ही जगह।",
  "Sign in to see your earned badges, orders and saved choices.": "अपने ऑर्डर, पसंद और मिले सम्मान देखने के लिए लॉग इन करें।",
  "A little joy": "हर मुलाकात में",
  "in every visit.": "मिठास भरा अपनापन।",
  "Fresh sweets, snacks and meals for the moments you share. Order ahead and collect at your chosen branch.": "ताज़ी मिठाइयाँ, चटपटे नाश्ते और स्वादिष्ट खाना। अभी ऑर्डर करें, अपने चुने समय पर दुकान से लें।",
  "Loading your profile…": "आपका खाता खोल रहे हैं…",
  "Loading your account…": "आपका खाता खोल रहे हैं…",
  "Your account could not load. Your orders remain safe.": "खाता नहीं खुल पाया। आपके ऑर्डर सुरक्षित हैं।",
  "Try again": "फिर कोशिश करें",
  "Your account": "आपका खाता",
  "Verify your phone": "मोबाइल नंबर की पुष्टि करें",
  "Optional verification helps secure your account. You can still place a pickup order as a guest.": "मोबाइल नंबर की पुष्टि करने से आपका खाता सुरक्षित रहता है। बिना लॉग इन किए भी दुकान से लेने का ऑर्डर कर सकते हैं।",
  "Verify with SMS": "SMS से पुष्टि करें",
  "✓ Phone verified": "✓ मोबाइल नंबर की पुष्टि हो गई",
  "Manage account": "खाता देखें",
  "Your Gokul account": "आपका गोकुल खाता",
  "Your verified phone stays linked to your account. Saved addresses and preferences can be edited in their sections.": "यह मोबाइल नंबर आपके खाते से जुड़ा है। पता और पसंद नीचे बदल सकते हैं।",
  "Your contact and saved choices.": "आपकी जानकारी और पसंद।",
  "Profile details": "आपकी जानकारी",
  "Verified phone": "मोबाइल नंबर",
  "Save name": "नाम सेव करें",
  "Your name": "आपका नाम",
  "Name": "नाम",
  "Sign out": "लॉग आउट",
  "Edit details": "जानकारी बदलें",
  "Notification inbox": "सूचनाएँ",
  "Privacy and data": "गोपनीयता और जानकारी",
  "Your badges": "आपके सम्मान",
  "Earned from completed paid orders on your account.": "आपके पूरे हुए ऑर्डर पर मिले सम्मान।",
  "Badges recognise visits. They are not points or discounts.": "ये सम्मान आपके साथ का धन्यवाद हैं। इनसे छूट या अंक नहीं मिलते।",
  "Your orders": "आपके ऑर्डर",
  "Only orders placed while signed in to this account.": "इस खाते से किए गए ऑर्डर यहाँ दिखेंगे।",
  "All branches": "सभी दुकानें",
  "Order details": "ऑर्डर की जानकारी",
  "Loading order details…": "ऑर्डर खोल रहे हैं…",
  "Order number": "ऑर्डर नंबर",
  "Reorder": "फिर ऑर्डर करें",
  "No orders belong to this verified account yet.": "इस खाते से अभी कोई ऑर्डर नहीं हुआ है।",
  "Review this reorder": "दोबारा ऑर्डर करने से पहले देखें",
  "Prices changed:": "नई कीमतें:",
  ". Current menu prices will apply.": "। अभी की मेन्यू कीमतें लगेंगी।",
  "Unavailable or changed:": "उपलब्ध नहीं या बदल गए:",
  ". Browse the menu to choose alternatives.": "। मेन्यू से दूसरा विकल्प चुनें।",
  "Add to cart": "कार्ट में डालें",
  "Save preferences": "पसंद सेव करें",
  "Your preferences": "आपकी पसंद",
  "Saved addresses": "सेव किए पते",
  "Saved favourites": "आपकी पसंदीदा चीज़ें",
  "Preferred branch": "पसंदीदा दुकान",
  "Manage addresses": "पते बदलें",
  "Manage preferences": "पसंद बदलें",
  "Save": "सेव करें",
  "as preferred": "पसंदीदा बनाएँ",
  "Remove": "हटाएँ",
  "Browse": "देखें",
  "Choose a branch →": "दुकान चुनें →",
  "Dietary notes": "खाने से जुड़ी पसंद",
  "Dietary notes are for your reference; check ingredients with the branch for each order.": "खाने से जुड़ी पसंद यहाँ लिख सकते हैं। सामग्री की जानकारी हर ऑर्डर पर दुकान से पूछें।",
  "Saved for your account. Delivery coverage and final address are checked separately at checkout.": "आपके खाते में सेव हैं। डिलीवरी उपलब्धता और सही पता ऑर्डर करते समय जाँचा जाएगा।",
  "Save an item from the current branch menu. Availability and prices are checked again when ordering.": "इस दुकान की पसंदीदा चीज़ सेव करें। ऑर्डर करते समय कीमत और उपलब्धता फिर जाँची जाएगी।",
  "Rewards": "आपके लाभ",
  "Earned points are not available yet. A balance will appear here when the rewards programme is launched.": "लाभ योजना शुरू होने पर आपके अंक यहाँ दिखेंगे।",
  "Daily operations": "आज का काम",
  "Live Orders": "चालू ऑर्डर",
  "Monitor customer pickup and delivery orders as they move through preparation.": "दुकान से लेने और डिलीवरी वाले ऑर्डर की तैयारी यहाँ देखें।",
  "Branch": "दुकान",
  "No branch available": "कोई दुकान उपलब्ध नहीं",
  "Last updated:": "अभी की जानकारी:",
  "Kitchen operations": "रसोई का काम",
  "Preparation Queue": "तैयारी की सूची",
  "Preparation started. KOT created.": "तैयारी शुरू हो गई। रसोई पर्ची बन गई।",
  "Order marked ready.": "ऑर्डर तैयार है।",
  "Swipe to start KOT": "सरकाएँ · तैयारी शुरू करें",
  "Swipe to mark ready": "सरकाएँ · तैयार हो गया",
  "Updating order…": "ऑर्डर अपडेट कर रहे हैं…",
  "Use button instead": "बटन से करें",
  "Confirm": "हाँ, करें",
  "Cancel": "रहने दें",
  "Tax collection": "टैक्स लागू करें",
  "Apply tax to new pickup, delivery, add-on and occasion bookings, including pickup convenience-fee tax. Turning this off keeps the tax rates saved for later.": "नए पिकअप, डिलीवरी, अतिरिक्त सामान और समारोह की बुकिंग पर टैक्स लगाएँ। इसमें पिकअप सुविधा शुल्क का टैक्स भी शामिल है। बंद करने पर नया टैक्स नहीं लगेगा, लेकिन दरें आगे के लिए सेव रहेंगी।",
  "Tax ON · tap to turn off": "टैक्स चालू · बंद करने के लिए दबाएँ",
  "Tax OFF · tap to turn on": "टैक्स बंद · चालू करने के लिए दबाएँ",
  "Existing paid orders and accepted occasion quotations are unchanged.": "पुराने भुगतान वाले ऑर्डर और मंज़ूर समारोह की कीमतें नहीं बदलेंगी।",
  "Saved. New quotes use this setting. Existing orders keep their original amounts.": "सेव हो गया। नए ऑर्डर पर यह सेटिंग लगेगी। पुराने ऑर्डर की राशि वही रहेगी।",
  "Loading…": "खोल रहे हैं…",
  "The best available offer is applied automatically. Add a little extra below if you like, then continue to payment.": "आपके लिए सबसे अच्छी उपलब्ध छूट अपने आप लगेगी। चाहें तो नीचे से कुछ और जोड़ें, फिर भुगतान करें।",
  "A branch favourite": "इस दुकान की पसंदीदा मिठाई",
  "+ Add": "+ जोड़ें",
  "1 piece": "1 पीस",
  "Reaches this offer’s spend threshold": "इसे जोड़ने पर छूट मिल सकती है",
  "more to unlock this saving in eligible items —": "और जोड़ने पर यह छूट पा सकते हैं —",
  "’s next saving:": " की अगली छूट:",
  "off. The convenience fee doesn’t count.": " की बचत। सुविधा शुल्क इसमें नहीं गिना जाता।",
  "Convenience fee": "सुविधा शुल्क",
  "Includes": "इसमें शामिल है",
  "fee tax": "शुल्क का टैक्स",
  "Order total": "कुल राशि",
  "tax)": "टैक्स)",
  "(includes ₹": "(इसमें ₹",
  "Convenience fee ₹": "सुविधा शुल्क ₹",
  "(unit ₹": "(प्रति इकाई ₹",
  ", tax": " , टैक्स",
  "Your pickup is reserved. Choose an offer below or continue to payment.": "आपका समय बुक हो गया है। नीचे छूट चुनें या भुगतान करें।",
  "Review the cart again so this same pending order can be updated before payment.": "भुगतान से पहले कार्ट देखें। इसी ऑर्डर में बदलाव सेव हो जाएगा।",
  "Keeping your pickup layout.": "आपकी समय की पसंद वही रहेगी।",
  "Editing a reserved order: your existing pickup selector keeps its held stock.": "इस बुक किए ऑर्डर का सामान आपके लिए सुरक्षित है।",
  "Cannot check preparation alerts. Reconnect and refresh the orders.": "तैयारी की जानकारी नहीं मिल रही। इंटरनेट जोड़ें और फिर देखें।",
  "Sound was blocked. Enable the kitchen alarm again.": "आवाज़ चालू नहीं हो पाई। रसोई का अलार्म फिर चालू करें।",
  "This device could not enable sound. Use staff push alerts.": "इस फोन में आवाज़ चालू नहीं हुई। फोन की सूचनाएँ चालू करें।"
});

Object.assign(hindi,{"For iPhone banners: open the installed app, enable staff push here, then allow Notifications, Banners and Sounds in iPhone Settings. Focus or Silent mode can suppress alerts.":"iPhone पर बैनर के लिए: इंस्टॉल किया ऐप खोलें और यहाँ फोन की सूचनाएँ चालू करें। फिर iPhone सेटिंग्स में इस ऐप के Notifications, Banners और Sounds चालू करें। Focus या साइलेंट मोड में आवाज़ रुक सकती है।"});

Object.assign(hindi, {
 "Finding your best offer and opening payment…": "आपके लिए सबसे अच्छी छूट लगा रहे हैं। अब भुगतान करें…",
 "Updating order…": "ऑर्डर आगे बढ़ा रहे हैं…",
 "Start preparation": "तैयारी शुरू करें",
 "Mark ready": "ऑर्डर तैयार है",
 "Or tap to confirm": "या यहाँ दबाकर पुष्टि करें",
 "Confirm order action": "ऑर्डर आगे बढ़ाने की पुष्टि",
 "Start preparation and create KOT?": "तैयारी शुरू करके रसोई की पर्ची बनाएँ?",
 "Is this order packed and ready?": "क्या ऑर्डर पैक हो गया है और देने के लिए तैयार है?",
 "Yes, start KOT": "हाँ, तैयारी शुरू करें",
 "Yes, mark ready": "हाँ, ऑर्डर तैयार है",
 "orders are overdue for ready": "ऑर्डर समय से पीछे हैं — तैयार करें",
 "Start KOT or mark the completed orders ready to stop the alarm.": "अलार्म रोकने के लिए तैयारी शुरू करें या पूरा ऑर्डर तैयार चिह्नित करें।",
 "No orders need action. Alarm is watching for new work.": "अभी कोई काम बाकी नहीं है। नया काम आते ही अलार्म बजेगा।",
 "Enable sound once per session. It repeats until waiting orders enter KOT and overdue preparing orders are marked ready.": "ऐप खोलने पर एक बार आवाज़ चालू करें। तैयारी शुरू करने और देर से तैयार हो रहे ऑर्डर पूरे करने तक अलार्म बजता रहेगा।",
 "IST": "भारतीय समय"
});

Object.assign(hindi,{"Check your pickup and items. Add something extra if you like, then continue to payment. We’ll apply your best available offer.":"समय और सामान देख लें। चाहें तो कुछ और जोड़ें, फिर भुगतान करें। आपके लिए सबसे अच्छी छूट हम लगा देंगे।"});

Object.assign(hindi, {"Suggested add-ons": "सुझाए गए अतिरिक्त सामान"});

Object.assign(hindi, {
 "Swipe to hand over":"सौंपने के लिए स्वाइप करें",
 "Verify pickup code":"पिकअप कोड जाँचें",
 "Continue to pickup code verification?":"पिकअप कोड की जाँच जारी रखें?",
 "Enter pickup code":"पिकअप कोड डालें",
 "Pickup code":"पिकअप कोड",
 "Your pickup code":"आपका पिकअप कोड",
 "Confirm pickup":"पिकअप की पुष्टि करें",
 "Verifying…":"जाँच हो रही है…",
 "Loading pickup code…":"पिकअप कोड लोड हो रहा है…",
 "Ask the customer for the four-digit code shown on their order. Confirm before handing over the food.":"ग्राहक से उनके ऑर्डर पर दिख रहा चार अंकों का कोड पूछें। सामान सौंपने से पहले पुष्टि करें।",
 "Share these four digits with staff when collecting your order. Keep this code private until handover.":"ऑर्डर लेते समय ये चार अंक कर्मचारी को बताएँ। सामान लेने तक यह कोड निजी रखें।",
 "Incorrect pickup code. Check the four digits with the customer.":"पिकअप कोड गलत है। ग्राहक से चारों अंक जाँच लें।",
 "Too many incorrect pickup codes. Try again in 15 minutes.":"कई बार गलत पिकअप कोड डाला गया है। 15 मिनट बाद दोबारा कोशिश करें।",
 "Online payment fee":"ऑनलाइन भुगतान शुल्क",
 "Online payment fee settings":"ऑनलाइन भुगतान शुल्क की सेटिंग",
 "Enable online payment fee":"ऑनलाइन भुगतान शुल्क चालू करें",
 "Payment fee (%)":"भुगतान शुल्क (%)",
 "Payment fee tax rate (%)":"भुगतान शुल्क पर कर (%)",
 "Save payment fee":"भुगतान शुल्क सहेजें",
 "Provider terms and fee tax treatment have been reviewed":"भुगतान सेवा की शर्तें और शुल्क पर कर की समीक्षा हो चुकी है",
 "Example: 2% on ₹1,000 adds ₹20. The global tax-off setting also turns off this fee’s tax component.":"उदाहरण: ₹1,000 पर 2% शुल्क ₹20 जोड़ता है। सभी कर बंद करने की सेटिंग इस शुल्क का कर भी बंद करती है।",
 "A separate percentage charge on the payable amount after discounts, including convenience or delivery charges. The percentage includes fee tax; it is shown before payment. Off or 0% means no charge.":"छूट के बाद देय राशि पर अलग प्रतिशत शुल्क, जिसमें सुविधा या डिलीवरी शुल्क भी शामिल हैं। प्रतिशत में शुल्क का कर शामिल है; यह भुगतान से पहले दिखता है। बंद या 0% होने पर कोई शुल्क नहीं लगता।"
});

Object.assign(hindi, {
 "View optional additions":"वैकल्पिक चीज़ें देखें",
 "Retry pairings":"सुझाव फिर से जाँचें",
 "We couldn’t load pairings. Try again.":"सुझाव लोड नहीं हो सके। फिर से कोशिश करें।",
 "Optional additions":"वैकल्पिक चीज़ें",
 "Choose pickup to see optional additions.":"वैकल्पिक चीज़ें देखने के लिए पिकअप चुनें।",
 "No optional additions right now.":"अभी कोई वैकल्पिक चीज़ उपलब्ध नहीं है।",
 "Optional additions at menu prices.":"मेन्यू की कीमत पर अपनी पसंद से जोड़ें।",
 "Checking suggestions. Continue browsing.":"सुझाव जाँचे जा रहे हैं। मेन्यू देखना जारी रखें।",
 "We couldn’t confirm the updated reservation. Your addition remains in the cart. Recheck the current cart and total before payment.":"नई बुकिंग की पुष्टि नहीं हो सकी। जोड़ी गई चीज़ कार्ट में सुरक्षित है। भुगतान से पहले कार्ट और कुल राशि दोबारा जाँचें।"
});

Object.assign(hindi, {
 "View customer favourites":"ग्राहकों की पसंद देखें",
 "Checking favourites…":"पसंदीदा चीज़ें जाँची जा रही हैं…",
 "No rated favourites right now":"अभी कोई रेटिंग वाली पसंद उपलब्ध नहीं है",
 "Review reserved total":"बुकिंग की कुल राशि देखें",
 "Recheck reserved total":"बुकिंग की कुल राशि दोबारा जाँचें",
 "Reserved total recovered. Review the confirmed amount before payment.":"बुकिंग की राशि मिल गई है। भुगतान से पहले पुष्टि की गई कुल राशि देखें।",
 "We couldn’t confirm the offer update. Your reservation and cart are saved. Recheck the reserved total before payment.":"ऑफ़र में बदलाव की पुष्टि नहीं हो सकी। आपकी बुकिंग और कार्ट सुरक्षित हैं। भुगतान से पहले बुकिंग की कुल राशि दोबारा जाँचें।"
});

Object.assign(hindi, {
 "Order desk":"ऑर्डर कार्य-पटल",
 "Open order desk":"ऑर्डर कार्य-पटल खोलें",
 "Orders & history":"ऑर्डर और इतिहास",
 "General orders & history":"सभी ऑर्डर और इतिहास",
 "Prepare / KOT":"तैयारी / KOT",
 "Handover":"ऑर्डर सौंपें",
 "Scheduled":"बाद के ऑर्डर",
 "Order workspace":"ऑर्डर कार्य-क्षेत्र",
 "Demand & exports":"मात्रा और निर्यात",
 "Find an order number":"ऑर्डर नंबर खोजें",
 "Order number":"ऑर्डर नंबर",
 "To prepare":"तैयारी शुरू करें",
 "Preparing":"तैयार हो रहा है",
 "Ready":"तैयार है",
 "Later pickups":"बाद के पिकअप",
 "Select":"चुनें",
 "selected":"चुने गए",
 "Select 20 eligible on this page":"इस पृष्ठ के 20 योग्य ऑर्डर चुनें",
 "Start selected + KOT":"चुने हुए शुरू करें + KOT",
 "Clear selection":"चयन हटाएँ",
 "Clear filters":"फ़िल्टर हटाएँ",
 "Details":"विवरण",
 "Start preparation":"तैयारी शुरू करें",
 "Mark ready":"तैयार चिह्नित करें",
 "This order is being prepared.":"यह ऑर्डर अभी तैयार हो रहा है।",
 "Preparation has not started yet.":"इस ऑर्डर की तैयारी अभी शुरू नहीं हुई है।",
 "This order has already been handed over.":"यह ऑर्डर पहले ही सौंपा जा चुका है।",
 "This order is not in the ready queue.":"यह ऑर्डर तैयार कतार में नहीं है।",
 "Order not found in this branch.":"इस शाखा में ऑर्डर नहीं मिला।",
 "Counter only · early packing allowed":"केवल काउंटर के सामान · पहले पैक कर सकते हैं",
 "Earliest pickup first · future kitchen orders stay scheduled":"पहले के पिकअप पहले · बाद के रसोई ऑर्डर निर्धारित समय पर शुरू होंगे",
 "Automatic updates · pickup times in IST":"अपने आप अपडेट · पिकअप का समय IST में",
 "Loading order desk…":"ऑर्डर कार्य-पटल लोड हो रहा है…",
 "No orders in this queue.":"इस कतार में कोई ऑर्डर नहीं है।",
 "Daily item demand":"दिन के अनुसार सामान की मात्रा",
 "Confirmed orders by pickup date. These quantities are demand, not available stock.":"पिकअप तारीख के अनुसार पुष्ट ऑर्डर। यह माँगी गई मात्रा है, उपलब्ध स्टॉक नहीं।",
 "Ordered":"ऑर्डर की मात्रा",
 "Not started":"अभी शुरू नहीं हुआ",
 "Completed / dispatched":"पूरा / भेज दिया गया",
 "Download Excel":"एक्सेल डाउनलोड करें",
 "Preparing export…":"निर्यात तैयार हो रहा है…",
 "Early packing settings":"पहले पैक करने की सेटिंग",
 "From":"से",
 "To":"तक",
 "Up to 31 days · all matching orders are exported":"अधिकतम 31 दिन · सभी चुने हुए ऑर्डर निर्यात होंगे",
 "Choose a date range of at most 31 days.":"अधिकतम 31 दिनों की तारीख सीमा चुनें।",
 "Loading demand…":"मात्रा लोड हो रही है…",
 "No confirmed item demand on this date.":"इस तारीख के लिए कोई पुष्ट ऑर्डर नहीं है।",
 "Counter products allowed for early packing":"पहले पैक किए जा सकने वाले काउंटर के सामान",
 "Enable only counter items safe to pack early on the pickup day. Any kitchen item keeps a mixed order scheduled.":"केवल ऐसे काउंटर सामान चालू करें जिन्हें पिकअप के दिन पहले पैक करना सुरक्षित है। रसोई का कोई सामान होने पर पूरा ऑर्डर अपने निर्धारित समय पर शुरू होगा।",
 "Customer-requested pickup change":"ग्राहक के अनुरोध पर पिकअप बदलें",
 "Only before preparation and KOT creation. Stock, capacity and existing charges are checked before saving.":"केवल तैयारी और KOT बनने से पहले। सहेजने से पहले स्टॉक, क्षमता और शुल्क की जाँच होगी।",
 "Customer request / reason":"ग्राहक का अनुरोध / कारण",
 "Choose a time":"समय चुनें",
 "Check & save pickup":"जाँचें और पिकअप सहेजें",
 "Pickup time changed.":"पिकअप का समय बदल दिया गया।",
 "Alarm enabled. Sound starts automatically after your next tap if the browser requires it.":"अलार्म चालू है। ब्राउज़र की आवश्यकता होने पर अगले सामान्य टैप के बाद आवाज़ शुरू होगी।",
 "Welcome to your Gokul branch":"आपकी गोकुल ब्रांच में स्वागत है",
 "Fresh sweets, snacks and meals from your neighbourhood Gokul branch.":"आपके पास की गोकुल ब्रांच से ताज़ी मिठाइयाँ, नाश्ता और भोजन।",
 "Order online · Collect here":"ऑनलाइन ऑर्डर करें · यहाँ से लें",
 "Explore the branch · Contact us to visit":"ब्रांच देखें · आने से पहले संपर्क करें",
 "See this branch’s items, prices and availability on the menu.":"मेन्यू में इस ब्रांच के सामान, कीमत और उपलब्धता देखें।",
 "Find us":"हमारा पता",
 "Address being updated":"पता अपडेट किया जा रहा है",
 "Opening hours":"खुलने का समय",
 "Contact the branch for hours":"समय जानने के लिए ब्रांच से संपर्क करें",
 "Get directions":"रास्ता देखें",
 "Call branch":"ब्रांच को कॉल करें",
 "A little planning. An easy pickup.":"थोड़ी योजना। आसान पिकअप।",
 "Your order, ready to collect":"आपका ऑर्डर, पिकअप के लिए तैयार",
 "Online orders are for pickup at this branch. Choose an available time at checkout.":"ऑनलाइन ऑर्डर इस ब्रांच से लेने के लिए हैं। चेकआउट पर उपलब्ध समय चुनें।",
 "Choose your favourites":"अपनी पसंद चुनें",
 "Browse the menu and add what you love.":"मेन्यू देखें और पसंद के सामान जोड़ें।",
 "Choose pickup & pay":"पिकअप चुनें और भुगतान करें",
 "Select an available slot and pay online.":"उपलब्ध समय चुनें और ऑनलाइन भुगतान करें।",
 "Collect at this branch":"इस ब्रांच से ऑर्डर लें",
 "Follow your order status and show your pickup code.":"ऑर्डर की स्थिति देखें और अपना पिकअप कोड दिखाएँ।"
});
