import type {OccasionSweet,PackingDraft,OccasionBox} from "@/types/occasionCatalogue";
export type RequestedOccasionItem={productId:number;quantity:number;unit:"GRAM"|"PIECE";supplementalGrams?:number};
export function buildOccasionItems(products:OccasionSweet[],quantities:Record<number,number>,units:Record<number,"KG"|"PIECE">,groups:PackingDraft[]):RequestedOccasionItem[] {
 return products.flatMap<RequestedOccasionItem>(product=>{const bulk=Number(quantities[product.id]??0);const unit=units[product.id]??(product.saleMode==="WEIGHT"?"KG":"PIECE");const boxPieces=groups.filter(g=>g.kind==="MIXED").reduce((sum,g)=>sum+(g.recipe.find(x=>x.productId===product.id)?.pieces??0)*g.boxCount,0);const pieces=boxPieces+(unit==="PIECE"?bulk:0),grams=(unit==="KG"?Math.round(bulk*1000):0)+groups.filter(g=>g.kind==="WEIGHT"&&g.productId===product.id).reduce((sum,g)=>sum+(g.totalGrams??0),0);
 if(pieces>0)return [{productId:product.id,quantity:pieces,unit:"PIECE" as const,...(grams>0?{supplementalGrams:grams}:{})}];if(grams>0)return [{productId:product.id,quantity:grams,unit:"GRAM" as const}];return [];});
}
export function packingError(groups:PackingDraft[],items:RequestedOccasionItem[],boxes:OccasionBox[]):string|null {
 const allocated=new Map<number,number>();for(const [n,g]of groups.entries()){const prefix=`Packing group ${n+1}: `;const box=boxes.find(b=>b.id===g.boxId);if(!box)return prefix+"choose a published box.";if(!Number.isInteger(g.boxCount)||g.boxCount<1||g.boxCount>10000)return prefix+"choose a quantity that fills 1–10,000 whole boxes.";
 if(g.kind==="MIXED"){if(!g.recipe.length)return prefix+"add at least one item to each box.";if(g.recipe.some(x=>!Number.isInteger(x.pieces)||x.pieces<1))return prefix+"pieces must be whole numbers.";if(g.recipe.reduce((s,x)=>s+x.pieces,0)>box.capacityPieces)return prefix+"the assortment exceeds this box's piece capacity.";}
 else {if(!g.productId||g.totalGrams!==g.boxCount*(g.packGrams??0)||box.capacityGrams!==g.packGrams)return prefix+"choose matching pack size, packaging and total kg.";allocated.set(g.productId,(allocated.get(g.productId)??0)+(g.totalGrams??0));}}
 for(const [productId,total]of allocated){const item=items.find(x=>x.productId===productId);if(total>(item?.unit==="GRAM"?item.quantity:item?.supplementalGrams??0))return "Weight packing exceeds the selected kg. Increase the item's kg quantity above or reduce the packing groups.";}return null;
}
export const inclusiveRate=(product:OccasionSweet)=>product.unitPrice==null||product.taxPercent==null?null:Math.round(product.unitPrice*(1+product.taxPercent/100)*100)/100;
export function indicativeFood(item:RequestedOccasionItem,product:OccasionSweet):number|null {if(product.unitPrice==null||product.taxPercent==null)return null;let amount=item.quantity;if(product.saleMode==="WEIGHT"){if(item.unit==="PIECE"){if(!product.pieceGrams)return null;amount=item.quantity*product.pieceGrams+(item.supplementalGrams??0);}amount/=1000;}const base=Math.round(product.unitPrice*amount*100)/100;return base+Math.round(base*product.taxPercent)/100;}
