"use client";
import {useEffect,useState} from 'react';
import {adminFetch} from '@/services/adminApi';
type Row={id:number;code:string;name:string;description:string;required_orders:number;minimum_subtotal:number;bonus_percent:number;appearance:string;active:boolean;version:number};
const blank={id:null as number|null,version:null as number|null,code:'',name:'',description:'',requiredOrders:1,minimumSubtotal:0,bonusPercent:0,appearance:'GOLD',active:true};
export default function BadgeSettings({authorization}:{authorization:string}){
 const [rows,setRows]=useState<Row[]>([]),[form,setForm]=useState(blank),[reason,setReason]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[loaded,setLoaded]=useState(false);
 useEffect(()=>{const c=new AbortController();void adminFetch('/api/admin/loyalty/badges',authorization,{signal:AbortSignal.any([c.signal,AbortSignal.timeout(8000)])}).then(async r=>{if(!r.ok)throw new Error('Badges could not be loaded.');const v=await r.json();if(!c.signal.aborted){setRows(v);setLoaded(true);}}).catch(e=>{if(!c.signal.aborted){setError(e.message);setLoaded(false);}});return()=>c.abort();},[authorization,revision]);
 async function save(){if(busy)return;setBusy(true);setError('');try{const r=await adminFetch('/api/admin/loyalty/badges',authorization,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,reason}),signal:AbortSignal.timeout(10000)});if(!r.ok){const v=await r.json().catch(()=>null);throw new Error(v?.message??'Badge could not be saved.');}setForm(blank);setReason('');setRevision(v=>v+1);}catch(e){setError(e instanceof Error?e.message:'Badge save failed.');}finally{setBusy(false);}}
 return <section id="badge-settings" className="rounded-2xl border border-[#eadfd6] bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-sm text-[#980c31]">Customer recognition</p><h2 className="text-xl font-bold">Badges & coin benefits</h2></div><button type="button" className="rounded-xl border px-4 py-2" onClick={()=>{setForm(blank);setError('');}}>New badge</button></div><p className="my-3 text-sm">Only completed paid orders meeting each badge’s minimum product subtotal count. Subtotal is after discounts and before fees. The highest qualifying tier applies; percentages never stack. Existing orders retain their saved earning rules.</p>{error&&<p role="alert" className="my-3 text-red-800">{error} <button type="button" className="underline" onClick={()=>setRevision(v=>v+1)}>Reload badges</button></p>}
 <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Badge','Completed orders','Minimum / order','Bonus coins','Status',''].map((s,i)=><th key={i} className="p-2">{s}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t"><td className="p-2 font-semibold">{r.name}</td><td className="p-2">{r.required_orders}</td><td className="p-2">₹{r.minimum_subtotal}</td><td className="p-2">+{r.bonus_percent}%</td><td className="p-2">{r.active?'Active':'Paused'}</td><td><button type="button" className="min-h-11 px-3 underline" onClick={()=>{setForm({id:r.id,version:r.version,code:r.code,name:r.name,description:r.description,requiredOrders:r.required_orders,minimumSubtotal:Number(r.minimum_subtotal),bonusPercent:Number(r.bonus_percent),appearance:r.appearance,active:r.active});setError('');}}>Edit</button></td></tr>)}</tbody></table></div>
 <form onSubmit={e=>{e.preventDefault();void save();}} className="mt-5 grid gap-4 md:grid-cols-2"><fieldset disabled={busy||!loaded} className="grid gap-3"><legend className="mb-3 font-bold">{form.id?'Edit badge':'Create badge'}</legend><label>Badge code<input required disabled={form.id!==null} pattern="[A-Z][A-Z0-9_]{0,39}" maxLength={40} className="block w-full rounded-lg border p-2" value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase()})}/></label><label>Name<input required maxLength={80} className="block w-full rounded-lg border p-2" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Description<input maxLength={240} className="block w-full rounded-lg border p-2" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label>{(['requiredOrders','minimumSubtotal','bonusPercent'] as const).map(k=><label key={k}>{({requiredOrders:'Completed paid orders required',minimumSubtotal:'Minimum qualifying subtotal per order (₹)',bonusPercent:'Additional coins (%)'})[k]}<input required type="number" min={k==='requiredOrders'?1:0} max={k==='requiredOrders'?100000:k==='bonusPercent'?100:1000000} step={k==='requiredOrders'?1:.01} className="block w-full rounded-lg border p-2" value={form[k]} onChange={e=>setForm({...form,[k]:Number(e.target.value)})}/></label>)}<label>Medallion colour<select className="block w-full rounded-lg border p-2" value={form.appearance} onChange={e=>setForm({...form,appearance:e.target.value})}>{['GOLD','SILVER','MAROON'].map(v=><option key={v}>{v}</option>)}</select></label><label><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/> Active</label><label>Audit reason<textarea required minLength={8} maxLength={300} className="block w-full rounded-lg border p-2" value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={reason.trim().length<8} className="min-h-11 rounded-xl bg-[#8f1838] px-4 text-white">{busy?'Saving…':'Save badge'}</button></fieldset><aside className="rounded-xl border border-[#ecdcad] bg-[#fffaf0] p-5"><p className="text-xs uppercase tracking-wide">Customer preview</p><h3 className="my-3 text-2xl font-bold">{form.name||'Your badge'}</h3><p>{form.description}</p><p className="mt-4">Complete {form.requiredOrders} paid orders of ₹{form.minimumSubtotal} or more each.</p><strong className="my-4 block text-[#087f55]">+{form.bonusPercent}% bonus coins on eligible future purchases</strong><p className="text-sm">If the normal order earns 25 coins, this tier adds {Math.floor(25*form.bonusPercent/100)} coins. Normal earning minimums, exclusions, refund reversals and expiry still apply.</p><p className="mt-4 text-sm">Changing eligibility can change a customer’s current tier. Pausing a badge removes its benefit for future orders. Previously earned recognition will not replay its celebration.</p></aside></form></section>;
}
