"use client";
import AdminHelp from "@/components/admin/AdminHelp";
import {useEffect,useState} from "react";
import {adminFetch} from "@/services/adminApi";
export default function BranchOperationalToggle({branchId,authorization}:{branchId:number;authorization:string}){
 const [value,setValue]=useState<boolean|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 useEffect(()=>{const controller=new AbortController();void adminFetch(`/api/admin/branches/${branchId}/operational`,authorization,{signal:controller.signal}).then(async response=>{if(!response.ok)throw Error("Operational status could not load.");const result=await response.json();if(!controller.signal.aborted)setValue(result.operational);}).catch(reason=>{if(!controller.signal.aborted)setMessage(reason.message);});return()=>controller.abort();},[branchId,authorization]);
 async function change(){if(value===null)return;setBusy(true);setMessage("");try{const response=await adminFetch(`/api/admin/branches/${branchId}/operational`,authorization,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({operational:!value})});if(!response.ok)throw Error("Operational status could not save. Please retry.");const result=await response.json();setValue(result.operational);setMessage(result.operational?"Branch reopened for customers.":"Branch closed for new customer visits and orders. Existing orders are retained.");}catch(reason){setMessage(reason instanceof Error?reason.message:"Could not save.");}finally{setBusy(false);}}
 return <section className="m-5 rounded-2xl border border-[#c4d4c9] bg-white p-5 text-[#143936]" aria-label="Branch operational status"><div className="flex items-center justify-between gap-2"><h3 className="font-bold">Customer operations</h3><AdminHelp title="Branch operational switch" description="OFF keeps this branch visible with a closure notice, but blocks its public home/menu and new orders. Existing orders, staff tools and unchanged reservation payment recovery remain available. Active is a separate switch that removes the branch from the public list." guidance="Turn OFF during temporary closure, and ON when the branch is ready to accept customers. This switch saves immediately; wait for the confirmation message. It does not cancel existing orders."/></div><label className="mt-3 flex min-h-11 items-center gap-3 font-semibold"><input type="checkbox" role="switch" checked={value===true} disabled={value===null||busy} onChange={()=>void change()}/>Branch is operational</label><p className="mt-2 text-sm leading-6">Off keeps the branch visible with “Currently not operational”, blocks its home/menu and new orders, and preserves placed orders. Deactivation is a separate setting that removes the branch from the public list.</p>{message&&<p role="status" className="mt-3 text-sm">{message}</p>}</section>;
}
