"use client";
import {useState} from "react";
import {adminFetch} from "@/services/adminApi";
import type {GiftSnapshot} from "@/types/occasionCatalogue";
import {prettyDate} from "@/components/occasion/OccasionDatePicker";

type Request = {id:string;serviceDate:string;fulfilment:string;gift?:GiftSnapshot|null;items:{productId:number;productName:string;quantity:number;unit:string;productionUnit?:string;suggestedProductionQuantity?:number|null}[]};
type Line={productId:number;name:string;unit:string;unitPrice:number;pieceGrams:number|null;productionQuantity:number;foodBase:number;foodTax:number;packagingAmount:number;grossAmount:number;cgstRate:number;sgstRate:number};
type Calculation={lines:Line[];foodBase:number;foodTax:number;packagingTotal:number;total:number;deposit:number;balance:number;expiresAt:string;balanceDueAt:string|null;expectedReadyAt:string|null};
const money=(value:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(value);
const instant=(value:string)=>new Date(value).toLocaleString("en-IN",{timeZone:"Asia/Kolkata",day:"numeric",month:"short",hour:"numeric",minute:"2-digit"});

export default function OccasionQuoteEditor<T extends Request>({enquiry,branchId,authorization,onSaved}: {enquiry:T;branchId:number;authorization:string;onSaved:(value:T)=>void}) {
    const [estimated,setEstimated]=useState(false);const [kg,setKg]=useState<Record<number,string>>({});
    const [extras,setExtras]=useState<{name:string;quantity:number;price:string}[]>(enquiry.gift?.includeSpoons?[{name:"Plastic spoons",quantity:enquiry.gift.boxCount,price:""}]:[]);
    const [rates,setRates]=useState<Record<number,string>>({});const [pieces,setPieces]=useState<Record<number,string>>({});
    const [packaging,setPackaging]=useState(enquiry.gift?.box.price==null?"":String(enquiry.gift.box.price));
    const [reviewed,setReviewed]=useState(false);const [percent,setPercent]=useState("50");const [ready,setReady]=useState("10:00");
    const [terms,setTerms]=useState("");const [calculation,setCalculation]=useState<Calculation|null>(null);
    const [busy,setBusy]=useState(false);const [error,setError]=useState("");
    const invalidate=()=>setCalculation(null);
    const input=()=>({rates:enquiry.items.map(item=>({productId:item.productId,unitPrice:rates[item.productId]?Number(rates[item.productId]):null,pieceGrams:pieces[item.productId]?Number(pieces[item.productId]):null,estimatedKg:kg[item.productId]?Number(kg[item.productId]):null})),
        estimated,extras:extras.map(extra=>({name:extra.name,quantity:extra.quantity,priceIncludingTax:extra.price!==""?Number(extra.price):null})),expectedTotal:calculation?.total??null,depositPercent:Number(percent),packagingPerBox:enquiry.gift&&packaging!==""?Number(packaging):null,packagingReviewed:reviewed,readyTime:enquiry.fulfilment==="PICKUP"?`${ready}:00`:null,terms:terms.trim()});
    async function act(action:"quote-preview"|"quote-from-rates"|"decline") {
        if(busy)return;setBusy(true);setError("");
        try {
            const response=await adminFetch(`/api/admin/branches/${branchId}/occasion-enquiries/${enquiry.id}/${action}`,authorization,
                {method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(action==="decline"?{reason:terms.trim()}:input())});
            const body=await response.json();if(!response.ok)throw new Error(body.message||body.detail||"Could not save. Check the request and try again.");
            if(action==="quote-preview")setCalculation(body as Calculation);else onSaved(body as T);
        } catch(failure){setError(failure instanceof Error?failure.message:"Could not calculate quote.");}finally{setBusy(false);}
    }
    return <section className="mt-5 space-y-5 rounded-2xl border border-teal-200 bg-[#f5faf7] p-4 sm:p-6" aria-label="Calculate occasion quote">
        <div><h3 className="text-lg font-bold">Build a clear quote</h3><p className="mt-1 text-sm">Configured branch rates and tax apply automatically. Review a rate only if this booking needs a different price.</p></div>
        <label className="flex gap-3 rounded-xl border bg-white p-4 text-sm"><input type="checkbox" checked={estimated} onChange={event=>{setEstimated(event.target.checked);if(event.target.checked&&percent==="100")setPercent("50");invalidate();}} /><span><strong>Final weight measured after packing</strong><span className="mt-1 block">For piece requests sold by kg, this is an estimate. The agreed rate stays fixed; the branch weighs the packed sweets on pickup day, then the customer reviews the final balance. Use a part advance.</span></span></label>
        <div className="grid gap-4 md:grid-cols-2">{enquiry.items.map(item=><fieldset key={item.productId} className="rounded-xl border bg-white p-4"><legend className="px-2 font-semibold">{item.productName}</legend>
            <p className="mb-3 text-sm">Requested {item.unit==="GRAM"?`${item.quantity/1000} kg`:`${item.quantity.toLocaleString("en-IN")} pieces`}</p>
            <label className="block text-sm">Rate before tax · ₹ per {item.productionUnit==="GRAM"?"kg":"piece"}<input type="number" min=".01" step=".01" placeholder="Use configured branch rate" value={rates[item.productId]??""}
                onChange={event=>{setRates(current=>({...current,[item.productId]:event.target.value}));invalidate();}} className="mt-1 w-full rounded-lg border p-3" />
                <span className="mt-1 block text-xs">Leave blank to use the live rate. Tax and line total are calculated by the server.</span></label>
            {item.productionUnit==="GRAM"&&<label className="mt-3 block text-sm">{estimated?"Estimated total kg":"Production quantity in kg"}<input type="number" min=".250" step=".001" value={kg[item.productId]??""} placeholder={item.suggestedProductionQuantity?String(item.suggestedProductionQuantity/1000):"Enter estimated kg for this item"} onChange={event=>{setKg(current=>({...current,[item.productId]:event.target.value}));invalidate();}} className="mt-1 w-full rounded-lg border p-3" /><span className="mt-1 block text-xs">Leave blank to calculate from requested kg or the configured piece size. All requested pieces must still be supplied.</span></label>}
            {item.productionUnit==="GRAM"&&item.unit==="PIECE"&&!kg[item.productId]&&<label className="mt-3 block text-sm">Measured grams per piece<input type="number" min=".001" step=".001" placeholder={item.suggestedProductionQuantity?String(item.suggestedProductionQuantity/item.quantity):"Required: weigh one piece"}
                value={pieces[item.productId]??""} onChange={event=>{setPieces(current=>({...current,[item.productId]:event.target.value}));invalidate();}} className="mt-1 w-full rounded-lg border p-3" />
                <span className="mt-1 block text-xs">We calculate total kg from the requested pieces. Leave blank when a piece size is already configured.</span></label>}
        </fieldset>)}</div>
        {enquiry.gift&&<fieldset className="rounded-xl border bg-white p-4"><legend className="px-2 font-semibold">{enquiry.gift.boxCount.toLocaleString("en-IN")} × {enquiry.gift.box.name}</legend>
            <label className="text-sm">Packaging per box, including tax ₹<input type="number" min="0" step=".01" value={packaging} onChange={event=>{setPackaging(event.target.value);invalidate();}} className="mt-1 block w-full rounded-lg border p-3" />
                <span className="mt-1 block text-xs">Box count × rate is added once to the quote. The server allocates it across the item tax snapshots automatically.</span></label>
            <label className="mt-3 flex gap-2 text-sm"><input type="checkbox" checked={reviewed} onChange={event=>{setReviewed(event.target.checked);invalidate();}} />I checked actual sweet sizes, box fit, packaging availability and branding.</label></fieldset>}
        <fieldset className="rounded-xl border bg-white p-4"><legend className="px-2 font-semibold">Accessories & additional packing</legend><p className="text-xs">Boxes are already included above. Add spoons or other agreed accessories once; each charge is tax inclusive and listed for the customer.</p>{extras.map((extra,index)=><div key={index} className="mt-3 grid gap-2 sm:grid-cols-3"><label className="text-sm">Accessory<input value={extra.name} maxLength={100} onChange={event=>{setExtras(current=>current.map((x,n)=>n===index?{...x,name:event.target.value}:x));invalidate();}} className="mt-1 w-full rounded-lg border p-3" /></label><label className="text-sm">Quantity<input type="number" min="1" max="100000" value={extra.quantity} onChange={event=>{setExtras(current=>current.map((x,n)=>n===index?{...x,quantity:Number(event.target.value)}:x));invalidate();}} className="mt-1 w-full rounded-lg border p-3" /></label><label className="text-sm">₹ each including tax<input type="number" min="0" step=".01" value={extra.price} onChange={event=>{setExtras(current=>current.map((x,n)=>n===index?{...x,price:event.target.value}:x));invalidate();}} className="mt-1 w-full rounded-lg border p-3" /></label><button type="button" onClick={()=>{setExtras(current=>current.filter((_,n)=>n!==index));invalidate();}} className="min-h-11 text-sm underline">Remove accessory</button></div>)}<button type="button" disabled={extras.length>=10} onClick={()=>{setExtras(current=>[...current,{name:"",quantity:enquiry.gift?.boxCount??1,price:""}]);invalidate();}} className="mt-3 min-h-11 rounded-lg border px-4">Add accessory</button></fieldset>
        <div className="grid gap-4 sm:grid-cols-2"><fieldset className="rounded-xl border bg-white p-4"><legend className="px-2 font-semibold">Customer’s requested date</legend><strong>{prettyDate(enquiry.serviceDate)}</strong>
            <p className="mt-1 text-xs">This date stays fixed. Decline with a reason if the kitchen cannot fulfil it.</p>
            {enquiry.fulfilment==="PICKUP"&&<><div className="mt-3 flex flex-wrap gap-2" aria-label="Suggested ready times">{["08:00","10:00","12:00","14:00","16:00","18:00"].map(time=><button key={time} type="button" aria-pressed={ready===time} onClick={()=>{setReady(time);invalidate();}} className={`min-h-11 rounded-xl border px-3 text-sm ${ready===time?"bg-[#143936] text-white":"bg-white"}`}>{`${Number(time.slice(0,2))%12||12} ${Number(time.slice(0,2))<12?"AM":"PM"}`}</button>)}</div><label className="mt-3 block text-sm">Ready time in India<div className="mt-1 flex gap-2"><select aria-label="Ready hour" value={ready.slice(0,2)} onChange={event=>{setReady(`${event.target.value}:${ready.slice(3,5)}`);invalidate();}} className="min-h-12 flex-1 rounded-lg border p-3">{Array.from({length:24},(_,hour)=><option key={hour} value={String(hour).padStart(2,"0")}>{String(hour).padStart(2,"0")}:00</option>)}</select><select aria-label="Ready minute" value={ready.slice(3,5)} onChange={event=>{setReady(`${ready.slice(0,2)}:${event.target.value}`);invalidate();}} className="min-h-12 flex-1 rounded-lg border p-3">{["00","15","30","45"].map(minute=><option key={minute}>{minute}</option>)}</select></div></label>
                <p className="mt-2 text-xs">Choose after reviewing ingredients, staffing and existing commitments. Approval creates the dedicated production plan automatically.</p></>}
        </fieldset><fieldset className="rounded-xl border bg-white p-4"><legend className="px-2 font-semibold">Payment plan</legend><label className="text-sm">Advance percentage<input type="number" min="1" max="100" step="1" value={percent} onChange={event=>{setPercent(event.target.value);invalidate();}} className="mt-1 w-full rounded-lg border p-3" /></label>
            <div className="mt-2 flex flex-wrap gap-2">{(estimated?[25,50]:[25,50,100]).map(value=><button key={value} type="button" aria-pressed={percent===String(value)} onClick={()=>{setPercent(String(value));invalidate();}} className="min-h-11 rounded-lg border px-3">{value===100?"Pay in full":`${value}%`}</button>)}</div>
            <p className="mt-2 text-xs">The advance is part of the total. {estimated?"The remaining balance opens after pickup-day packing and final weighing.":"Quote expiry and balance deadline are calculated before the requested date."} Shown for review below.</p></fieldset></div>
        <label className="block text-sm font-semibold">Customer-visible terms or decline reason<textarea maxLength={500} value={terms} onChange={event=>{setTerms(event.target.value);invalidate();}} className="mt-1 w-full rounded-xl border bg-white p-3" placeholder="Pickup instructions, inclusions and cancellation terms" /><span className="mt-1 block text-xs font-normal">Explain what the quote includes and any cancellation conditions in plain language.</span></label>
        {error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-red-800">{error}</p>}
        <div className="flex flex-wrap gap-3"><button type="button" disabled={busy||!terms.trim()} onClick={()=>void act("quote-preview")} className="min-h-12 rounded-xl bg-[#143936] px-5 font-semibold text-white disabled:opacity-50">Calculate and review quote</button><button type="button" disabled={busy||!terms.trim()} onClick={()=>void act("decline")} className="min-h-12 rounded-xl border px-5 disabled:opacity-50">Decline with reason</button></div>
        {calculation&&<div className="space-y-4 rounded-2xl border bg-white p-5" aria-label="Calculated quote summary"><h4 className="font-bold">Review before sending</h4>
            <dl className="grid grid-cols-2 gap-3 text-sm"><dt>Food before tax</dt><dd className="text-right">{money(calculation.foodBase)}</dd><dt>Food tax</dt><dd className="text-right">{money(calculation.foodTax)}</dd><dt>Packaging & accessories (tax included)</dt><dd className="text-right">{money(calculation.packagingTotal)}</dd><dt className="text-lg font-bold">{estimated?"Estimated total, including tax":"Total, including tax"}</dt><dd className="text-right text-lg font-bold">{money(calculation.total)}</dd><dt>Advance</dt><dd className="text-right">{money(calculation.deposit)}</dd><dt>Remaining balance</dt><dd className="text-right">{money(calculation.balance)}</dd></dl>
            {estimated&&<p className="rounded-lg bg-amber-50 p-3 text-sm font-semibold">Estimate: final measured weights at the agreed rates determine the invoice after packing. Advance stays credited.</p>}
            <p className="text-sm">Quote expires {instant(calculation.expiresAt)} IST.{calculation.balanceDueAt&&!estimated&&` Balance due ${instant(calculation.balanceDueAt)} IST.`}</p>
            {calculation.expectedReadyAt&&<p className="text-sm font-semibold">Ready on {prettyDate(enquiry.serviceDate)} at {ready} IST.</p>}
            <details><summary className="min-h-11 cursor-pointer text-sm font-semibold">Item prices, tax and production</summary><ul className="space-y-2 text-sm">{calculation.lines.map(line=><li key={line.productId} className="rounded-lg bg-[#f5faf7] p-3"><strong>{line.name} · {money(line.grossAmount)}</strong><p>{line.unit==="GRAM"?`${line.productionQuantity/1000} kg`:`${line.productionQuantity} pieces`} × {money(line.unitPrice)} per {line.unit==="GRAM"?"kg":"piece"}; food tax {line.cgstRate+line.sgstRate}%; packaging allocation {money(line.packagingAmount)}.</p></li>)}</ul></details>
            <button type="button" disabled={busy||!!enquiry.gift&&!reviewed} onClick={()=>void act("quote-from-rates")} className="min-h-12 w-full rounded-xl bg-[#143936] px-5 font-bold text-white disabled:opacity-50">{busy?"Saving…":"Send reviewed quote"}</button>
            {enquiry.gift&&!reviewed&&<p className="text-sm">Confirm packaging fit before sending.</p>}
        </div>}
    </section>;
}
