"use client";
import {useEffect, useState} from "react";
import {adminFetch} from "@/services/adminApi";
import type {OccasionCatalogue, OccasionBox, OccasionSweet} from "@/types/occasionCatalogue";
const empty: OccasionBox = {id:null,name:"",imageUrl:"",dimensions:"",material:"",compartments:3,capacityPieces:8,price:null,branding:"",leadDays:3,published:false};
export default function OccasionCatalogueEditor({branchId, authorization}: {branchId: number; authorization: string}) {
    const [catalogue,setCatalogue]=useState<OccasionCatalogue | null>(null);
    const [box,setBox]=useState<OccasionBox>(empty);
    const [message,setMessage]=useState("");
    const [busy,setBusy]=useState(false);
    const path=`/api/admin/branches/${branchId}/occasion-catalogue`;
    useEffect(()=>{const controller=new AbortController();void adminFetch(path,authorization,{signal:controller.signal}).then(async response=>{if(!response.ok)throw Error();return response.json() as Promise<OccasionCatalogue>;}).then(result=>{if(!controller.signal.aborted){setCatalogue(result);setBox(empty);}}).catch(()=>{if(!controller.signal.aborted)setMessage("Could not load the occasion catalogue.");});return()=>controller.abort();},[path,authorization]);
    async function save(url:string,body:object,method="PUT") {
        setBusy(true);setMessage("");
        try {const response=await adminFetch(url,authorization,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!response.ok)throw Error();const fresh=await adminFetch(path,authorization);if(!fresh.ok)throw Error();setCatalogue(await fresh.json());setMessage("Catalogue saved. Existing enquiry and quote snapshots are unchanged.");}
        catch {setMessage("Could not confirm the change. Check the fields and refresh before retrying.");}finally{setBusy(false);}
    }
    function updateSweet(sweet:OccasionSweet,patch:Partial<OccasionSweet>) {setCatalogue(current=>current ? {...current,sweets:current.sweets.map(item=>item.id===sweet.id?{...item,...patch}:item)}:current);}
    return <details className="rounded-2xl border bg-white p-5"><summary className="cursor-pointer text-xl font-bold">Occasion sweets & packaging catalogue</summary><p className="mt-3 text-sm">Create sweet products and upload their real photos in the existing branch menu editor, then configure their occasion availability here. Catalogue changes apply to new requests. Approved bookings retain their snapshots.</p>
        {message && <p role="status" className="mt-3 rounded-xl bg-amber-50 p-3">{message}</p>}
        <div className="mt-4 space-y-4">{catalogue?.sweets.map(sweet=><fieldset key={sweet.id} className="rounded-xl border p-4"><legend className="px-2 font-semibold">{sweet.name}</legend><div className="grid gap-4 sm:grid-cols-2">
            <label className="text-sm"><input type="checkbox" checked={sweet.occasionOnly} onChange={event=>updateSweet(sweet,{occasionOnly:event.target.checked})} /> Occasion only<span className="mt-1 block text-xs">Removes this sweet from the regular menu and ordinary checkout for this branch. Existing placed orders are unaffected.</span></label>
            <label className="text-sm"><input type="checkbox" checked={sweet.published} onChange={event=>updateSweet(sweet,{published:event.target.checked})} /> Publish for occasions<span className="mt-1 block text-xs">Customers can request this sweet only when published and the branch product is available.</span></label>
            <label className="text-sm">Minimum lead days<input type="number" min={0} max={365} value={sweet.leadDays} onChange={event=>updateSweet(sweet,{leadDays:Number(event.target.value)})} className="mt-1 block w-full rounded-lg border p-2" /><span className="mt-1 block text-xs">Calendar days needed before fulfilment for procurement and production.</span></label>
            {sweet.saleMode==="WEIGHT" && <label className="text-sm">Configured grams per piece (optional)<input type="number" min={0.001} step={0.001} value={sweet.pieceGrams??""} onChange={event=>updateSweet(sweet,{pieceGrams:event.target.value?Number(event.target.value):null})} className="mt-1 block w-full rounded-lg border p-2" /><span className="mt-1 block text-xs">Use a measured standard piece size. Leave blank for manager sizing. Never guess; quotes require an approved whole-gram production quantity.</span></label>}
            <button type="button" disabled={busy} onClick={()=>void save(`${path}/sweets/${sweet.id}`,{occasionOnly:sweet.occasionOnly,published:sweet.published,leadDays:sweet.leadDays,pieceGrams:sweet.pieceGrams})} className="min-h-11 rounded-xl border px-4 font-semibold">Save sweet settings</button>
        </div></fieldset>)}</div>
        <h3 className="mt-6 text-lg font-bold">Gift packaging</h3><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={()=>setBox(empty)} className="min-h-11 rounded-xl border px-3">New box</button>{catalogue?.boxes.map(item=><button type="button" key={item.id} onClick={()=>setBox(item)} className="min-h-11 rounded-xl border px-3">Edit {item.name}</button>)}</div>
        <form onSubmit={event=>{event.preventDefault();void save(`${path}/boxes`,box,"POST");}} className="mt-4 grid gap-4 sm:grid-cols-2">
            {([{key:"name",label:"Box name",help:"Customer-facing packaging name.",max:100},{key:"imageUrl",label:"Real photo URL (HTTPS)",help:"Use an actual photo uploaded through the existing image tool. Empty shows a labelled placeholder.",max:1000},{key:"dimensions",label:"Dimensions",help:"Usable inner dimensions with units, e.g. 18 × 12 × 4 cm. Manager checks physical fit.",max:100},{key:"material",label:"Material",help:"State actual material, e.g. food-safe cardboard with insert.",max:100},{key:"branding",label:"Branding options",help:"Describe available print, ribbon or personalised message options; agree any custom details in the quote.",max:300}] as const).map(field=><label key={field.key} className="text-sm">{field.label}<input required={field.key!=="imageUrl"&&field.key!=="branding"} maxLength={field.max} value={box[field.key]??""} onChange={event=>setBox(current=>({...current,[field.key]:event.target.value}))} className="mt-1 block w-full rounded-lg border p-2" /><span className="mt-1 block text-xs">{field.help}</span></label>)}
            {([{key:"compartments",label:"Compartments",help:"Maximum distinct sweets in this insert.",min:1,max:100},{key:"capacityPieces",label:"Maximum pieces per box",help:"Conservative capacity for the intended sweet size. Manager confirms the selected assortment fits.",min:1,max:1000},{key:"leadDays",label:"Packaging lead days",help:"Calendar days needed for sourcing or branding before fulfilment.",min:0,max:365}] as const).map(field=><label key={field.key} className="text-sm">{field.label}<input type="number" required min={field.min} max={field.max} value={box[field.key]} onChange={event=>setBox(current=>({...current,[field.key]:Number(event.target.value)}))} className="mt-1 block w-full rounded-lg border p-2" /><span className="mt-1 block text-xs">{field.help}</span></label>)}
            <label className="text-sm">Estimated packaging ₹ per box<input type="number" min={0} step={0.01} value={box.price??""} onChange={event=>setBox(current=>({...current,price:event.target.value?Number(event.target.value):null}))} className="mt-1 block w-full rounded-lg border p-2" /><span className="mt-1 block text-xs">Optional estimate, not a payment promise. Manager approves final packaging cost included in the quoted item totals.</span></label>
            <label className="text-sm"><input type="checkbox" checked={box.published} onChange={event=>setBox(current=>({...current,published:event.target.checked}))} /> Publish packaging<span className="mt-1 block text-xs">Only published boxes can be selected in new customer requests. Unpublish to stop new requests; existing snapshots remain.</span></label>
            <button disabled={busy} className="min-h-11 rounded-xl bg-[#173c39] px-4 font-bold text-white">Save packaging</button>
        </form>
    </details>;
}
