"use client";
import {T} from "@/lib/language";

import {prettyDate,addDays} from "@/components/occasion/OccasionDatePicker";
export type ProductionProduct={productId:number;name:string;requestedPieces:number;requestedGrams:number;committedPieces:number;committedGrams:number;approvedPieces:number;approvedGrams:number;readyPieces:number;readyGrams:number;approvalToken:string|null};
export type ProductionDay={date:string;orderCount:number;needsReview:number;committedOrders:number;products:ProductionProduct[]};
export type ProductionWeek={today:string;days:ProductionDay[]};
const quantities=(pieces:number,grams:number)=>[grams>0?`${(grams/1000).toLocaleString("en-IN")} kg`:"",pieces>0?`${pieces.toLocaleString("en-IN")} pieces`:""].filter(Boolean).join(" + ")||"—";
export default function OccasionProductionCalendar({week,date,onDate,onWeek,onApprove,canApprove,busy}:{week:ProductionWeek;date:string;onDate:(date:string)=>void;onWeek:(from:string)=>void;onApprove:(product:ProductionProduct)=>void;canApprove:boolean;busy:boolean}) {
 const selected=week.days.find(day=>day.date===date);return <section className="space-y-5" aria-label="Bulk production planning"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Plan the kitchen by date</h2><p className="mt-1 text-sm text-stone-600">Customer pickup dates and totals in India time. Swipe the dates to browse.</p></div><div className="flex gap-2"><button type="button" onClick={()=>onWeek(addDays(week.days[0].date,-7))} className="min-h-11 rounded-xl border bg-white px-4">Previous week</button><button type="button" onClick={()=>{onWeek(week.today);onDate(week.today);}} className="min-h-11 rounded-xl border bg-white px-4"><T text="Today" /></button><button type="button" onClick={()=>onWeek(addDays(week.days[0].date,7))} className="min-h-11 rounded-xl border bg-white px-4">Next week</button></div></div>
 <div className="flex gap-2 overflow-x-auto rounded-2xl border bg-white p-2" aria-label="Pickup date tabs">{week.days.map(day=><button key={day.date} type="button" aria-pressed={date===day.date} onClick={()=>onDate(day.date)} className={`min-w-36 flex-1 rounded-xl border-b-4 p-4 text-left ${date===day.date?"border-[#173c39] bg-[#eef6f1]":"border-transparent"}`}><span className="block whitespace-nowrap text-sm font-semibold">{new Date(`${day.date}T12:00:00+05:30`).toLocaleDateString("en-IN",{timeZone:"Asia/Kolkata",weekday:"short",day:"numeric",month:"short"})}</span><strong className="mt-2 block">{day.orderCount}{" "}<T text="orders" /></strong><small className="mt-1 block">{day.needsReview} awaiting quote</small></button>)}</div>
 <div className="grid gap-3 md:grid-cols-3" aria-label="Three-day production outlook">{week.days.slice(0,3).map(day=><div key={day.date} className="rounded-2xl border bg-white p-4"><h3 className="font-semibold">{prettyDate(day.date)}</h3><p className="mt-1 text-xs">Paid commitments · {day.committedOrders} bookings</p><ul className="mt-3 space-y-1 text-sm">{day.products.filter(p=>p.committedPieces>0||p.committedGrams>0).map(p=><li key={p.productId}>{p.name} <strong>{quantities(p.committedPieces,p.committedGrams)}</strong></li>)}</ul>{!day.products.some(p=>p.committedPieces>0||p.committedGrams>0)&&<p className="mt-3 text-sm text-stone-600">No active paid production commitments.</p>}</div>)}</div>
 {selected&&<div className="rounded-2xl border bg-white p-4 sm:p-6"><h3 className="text-lg font-bold">{prettyDate(date)} · product totals</h3><p className="mt-2 text-sm">Requested quantities await quote/payment. Paid commitments use approved production kg or pieces. Approve paid quantities into the dedicated bulk production register; this does not mark food prepared or add daily pickup stock.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{selected.products.map(product=><article key={product.productId} className="rounded-xl border bg-[#faf8f4] p-4"><h4 className="font-bold">{product.name}</h4><dl className="mt-3 grid grid-cols-2 gap-2 text-sm"><dt>Awaiting quote / payment</dt><dd className="text-right">{quantities(product.requestedPieces,product.requestedGrams)}</dd><dt>Paid production</dt><dd className="text-right font-semibold">{quantities(product.committedPieces,product.committedGrams)}</dd><dt>Kitchen-approved</dt><dd className="text-right">{quantities(product.approvedPieces,product.approvedGrams)}</dd><dt>Physically prepared</dt><dd className="text-right">{quantities(product.readyPieces,product.readyGrams)}</dd></dl>{canApprove&&product.approvalToken&&<button type="button" disabled={busy} onClick={()=>onApprove(product)} className="mt-4 min-h-11 w-full rounded-xl bg-[#173c39] px-4 font-semibold text-white disabled:opacity-50">Approve pending paid production</button>}</article>)}</div>{!selected.products.length&&<p className="mt-4 text-sm">No active demand or paid commitments for this date.</p>}</div>}
 </section>;
}
