/* eslint-disable @next/next/no-img-element -- Admin previews managed image uploads. */
"use client";
import {useEffect, useId, useState} from "react";
import {adminFetch} from "@/services/adminApi";
import type {OccasionCatalogue, OccasionBox, OccasionSweet, OccasionBranding} from "@/types/occasionCatalogue";
const empty: OccasionBox = {id:null,name:"",imageUrl:"",dimensions:"",material:"",compartments:3,capacityPieces:8,price:null,branding:"",leadDays:3,published:false};
export default function OccasionCatalogueEditor({branchId, authorization}: {branchId: number; authorization: string}) {
    const [expanded,setExpanded]=useState(false);
    const [loading,setLoading]=useState(true);
    const [reload,setReload]=useState(0);
    const panelId=useId();
    const [catalogue,setCatalogue]=useState<OccasionCatalogue | null>(null);
    const [branding,setBranding]=useState<OccasionBranding>({headline:"",description:"",imageUrl:null,published:false});
    const [box,setBox]=useState<OccasionBox>(empty);
    const [message,setMessage]=useState("");
    const [busy,setBusy]=useState(false);
    const path=`/api/admin/branches/${branchId}/occasion-catalogue`;
    useEffect(()=>{const controller=new AbortController();void adminFetch(path,authorization,{signal:controller.signal}).then(async response=>{if(!response.ok)throw Error();return response.json() as Promise<OccasionCatalogue>;}).then(result=>{if(!controller.signal.aborted){setCatalogue(result);setBox(empty);setBranding(result.branding??{headline:"",description:"",imageUrl:null,published:false});setMessage("");}}).catch(()=>{if(!controller.signal.aborted)setMessage("Could not load the occasion catalogue. Reload before making changes.");}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[path,authorization,reload]);
    async function save(url:string,body:object,method="PUT") {
        if(busy||loading||!catalogue)return;
        setBusy(true);setMessage("");
        try {const response=await adminFetch(url,authorization,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});if(!response.ok)throw Error();if(url.endsWith("/boxes")){const saved=await response.json() as OccasionBox;if(saved.id==null)throw Error();setBox(saved);}const fresh=await adminFetch(path,authorization);if(!fresh.ok)throw Error();setCatalogue(await fresh.json());setMessage("Catalogue saved. Existing enquiry and quote snapshots are unchanged.");}
        catch {setMessage("Could not confirm the change. Check the fields and refresh before retrying.");}finally{setBusy(false);}
    }
    async function upload(files:FileList|null, hero=false) {
        if(!files?.length)return;
        if(files.length+(hero?0:(box.imageUrls?.length??(box.imageUrl?1:0)))>(hero?1:6)){setMessage("Choose up to six packaging photos or one campaign photo.");return;}
        setBusy(true);setMessage("");
        const urls:string[]=[];
        try {
            for(const file of Array.from(files)) {
                if(file.size>5*1024*1024 || !["image/jpeg","image/png","image/webp"].includes(file.type))throw Error("Use JPG, PNG or WebP up to 5 MB per photo.");
                const body=new FormData();body.append("image",file);
                const response=await adminFetch(`${path}/photos`,authorization,{method:"POST",body});
                if(!response.ok)throw Error("Upload failed. Successfully uploaded previews are retained; retry remaining photos.");
                urls.push((await response.json()).url);
                if(hero)setBranding(current=>({...current,imageUrl:urls[0]}));
                else setBox(current=>({...current,imageUrls:[...(current.imageUrls?.length?current.imageUrls:current.imageUrl?[current.imageUrl]:[]),urls.at(-1)!],imageUrl:current.imageUrl||urls[0]}));
            }
            setMessage("Photos uploaded. Save to publish your changes.");
        }catch(error){setMessage(error instanceof Error?error.message:"Upload unavailable.");}finally{setBusy(false);}
    }
    function updateSweet(sweet:OccasionSweet,patch:Partial<OccasionSweet>) {setCatalogue(current=>current ? {...current,sweets:current.sweets.map(item=>item.id===sweet.id?{...item,...patch}:item)}:current);}
    return <section className="rounded-2xl border bg-white p-5" aria-label="Occasion catalogue"><h2><button type="button" aria-expanded={expanded} aria-controls={panelId} onClick={()=>setExpanded(current=>!current)} className="min-h-11 w-full text-left text-xl font-bold">Occasion sweets & packaging catalogue <span aria-hidden="true">{expanded?"▾":"▸"}</span></button></h2><div id={panelId} hidden={!expanded}><p className="mt-3 text-sm">Create sweet products and upload their real photos in the existing branch menu editor, then configure their occasion availability here. Catalogue changes apply to new requests. Approved bookings retain their snapshots.</p>
        {message && <p role="status" className="mt-3 rounded-xl bg-amber-50 p-3">{message}</p>}
        {loading && <p role="status">Loading occasion catalogue…</p>}
        {!loading && !catalogue && <button type="button" onClick={()=>{setLoading(true);setReload(value=>value+1);}} className="min-h-11 rounded-xl border px-4">Reload catalogue</button>}
        {catalogue && !loading && <fieldset disabled={busy} className="min-w-0 border-0 p-0">
        <div className="mt-4 space-y-4">{catalogue?.sweets.map(sweet=><fieldset key={sweet.id} className="rounded-xl border p-4"><legend className="px-2 font-semibold">{sweet.name}</legend><div className="grid gap-4 sm:grid-cols-2">
            <label className="text-sm"><input type="checkbox" checked={sweet.occasionOnly} onChange={event=>updateSweet(sweet,{occasionOnly:event.target.checked})} /> Occasion only<span className="mt-1 block text-xs">Removes this sweet from the regular menu and ordinary checkout for this branch. Existing placed orders are unaffected.</span></label>
            <label className="text-sm"><input type="checkbox" checked={sweet.published} onChange={event=>updateSweet(sweet,{published:event.target.checked})} /> Publish for occasions<span className="mt-1 block text-xs">Customers can request this sweet when published and the product is active. This is independent of daily menu availability.</span></label>
            <label className="text-sm">Minimum lead days<input type="number" min={0} max={365} value={sweet.leadDays} onChange={event=>updateSweet(sweet,{leadDays:Number(event.target.value)})} className="mt-1 block w-full rounded-lg border p-2" /><span className="mt-1 block text-xs">Calendar days needed before fulfilment for procurement and production.</span></label>
            {sweet.saleMode==="WEIGHT" && <label className="text-sm">Configured grams per piece (optional)<input type="number" min={0.001} step={0.001} value={sweet.pieceGrams??""} onChange={event=>updateSweet(sweet,{pieceGrams:event.target.value?Number(event.target.value):null})} className="mt-1 block w-full rounded-lg border p-2" /><span className="mt-1 block text-xs">Use a measured standard piece size. Leave blank for manager sizing. Never guess; quotes require an approved whole-gram production quantity.</span></label>}
            <button type="button" disabled={busy} onClick={()=>void save(`${path}/sweets/${sweet.id}`,{occasionOnly:sweet.occasionOnly,published:sweet.published,leadDays:sweet.leadDays,pieceGrams:sweet.pieceGrams})} className="min-h-11 rounded-xl border px-4 font-semibold">Save sweet settings</button>
        </div></fieldset>)}</div>
        <h3 className="mt-6 text-lg font-bold">Gift packaging</h3><div className="mt-3 flex flex-wrap gap-2"><button type="button" disabled={busy} onClick={()=>setBox(empty)} className="min-h-11 rounded-xl border px-3">New box</button>{catalogue?.boxes.map(item=><button type="button" key={item.id} disabled={busy} onClick={()=>setBox(item)} className="min-h-11 rounded-xl border px-3">Edit {item.name}</button>)}</div>
        <div className="mt-4 rounded-xl border p-4"><label className="block font-semibold">Upload packaging photos<input aria-label="Upload packaging photos" type="file" multiple accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={event=>{void upload(event.target.files);event.target.value="";}} className="mt-2 block w-full" /></label><p className="mt-2 text-sm">Up to six real photos, 5 MB each. First photo is the cover; show the outside, inside and filled box. Uploads appear after Save packaging.</p><div className="mt-3 flex flex-wrap gap-3">{(box.imageUrls?.length?box.imageUrls:box.imageUrl?[box.imageUrl]:[]).map((url,index)=><div key={url}><img src={url} alt={`Packaging preview ${index+1}`} className="h-24 w-32 rounded-xl object-cover" /><button type="button" disabled={busy} onClick={()=>setBox(current=>{const images=(current.imageUrls?.length?current.imageUrls:current.imageUrl?[current.imageUrl]:[]).filter(value=>value!==url);return {...current,imageUrls:images,imageUrl:images[0]??null};})} className="min-h-11 text-sm underline">Remove photo {index+1}</button></div>)}</div></div>
        <h3 role="status" className="mt-4 font-semibold">{box.id==null?"Create new packaging":"Editing packaging: "+box.name}</h3>
        <form onSubmit={event=>{event.preventDefault();void save(`${path}/boxes`,box,"POST");}} className="mt-4 grid gap-4 sm:grid-cols-2">
            {([{key:"name",label:"Box name",help:"Customer-facing packaging name.",max:100},{key:"dimensions",label:"Dimensions",help:"Usable inner dimensions with units, e.g. 18 × 12 × 4 cm. Manager checks physical fit.",max:100},{key:"material",label:"Material",help:"State actual material, e.g. food-safe cardboard with insert.",max:100},{key:"branding",label:"Branding options",help:"Describe available print, ribbon or personalised message options; agree any custom details in the quote.",max:300}] as const).map(field=><label key={field.key} className="text-sm">{field.label}<input required={field.key!=="branding"} maxLength={field.max} value={box[field.key]??""} onChange={event=>setBox(current=>({...current,[field.key]:event.target.value}))} className="mt-1 block w-full rounded-lg border p-2" /><span className="mt-1 block text-xs">{field.help}</span></label>)}
            {([{key:"compartments",label:"Compartments",help:"Physical sections in the box. Mixed sweets may share a section; review actual fit before quoting.",min:1,max:100},{key:"capacityPieces",label:"Maximum pieces per box",help:"Conservative capacity for the intended sweet size. Manager confirms the selected assortment fits.",min:1,max:1000},{key:"leadDays",label:"Packaging lead days",help:"Calendar days needed for sourcing or branding before fulfilment.",min:0,max:365}] as const).map(field=><label key={field.key} className="text-sm">{field.label}<input type="number" required min={field.min} max={field.max} value={box[field.key]} onChange={event=>setBox(current=>({...current,[field.key]:Number(event.target.value)}))} className="mt-1 block w-full rounded-lg border p-2" /><span className="mt-1 block text-xs">{field.help}</span></label>)}
            <label className="text-sm">Food weight capacity<select aria-label="Food weight capacity" value={box.capacityGrams??""} onChange={event=>setBox(current=>({...current,capacityGrams:event.target.value?Number(event.target.value):null}))} className="mt-1 block w-full rounded-lg border p-2"><option value="">Mixed pieces only / not weight-rated</option><option value={1000}>1 kg</option><option value={500}>500 g (½ kg)</option><option value={250}>250 g (¼ kg)</option></select><span className="mt-1 block text-xs">Publish separate real box types for each supported food weight. This is food weight, not container volume; a 400 ml plastic box is not automatically a 500 g box. Check the actual product fit.</span></label>
            <label className="text-sm">Estimated packaging ₹ per box<input type="number" min={0} step={0.01} value={box.price??""} onChange={event=>setBox(current=>({...current,price:event.target.value?Number(event.target.value):null}))} className="mt-1 block w-full rounded-lg border p-2" /><span className="mt-1 block text-xs">Optional estimate, not a payment promise. Manager approves final packaging cost included in the quoted item totals.</span></label>
            <label className="text-sm"><input type="checkbox" checked={box.published} onChange={event=>setBox(current=>({...current,published:event.target.checked}))} /> Publish packaging<span className="mt-1 block text-xs">Only published boxes can be selected in new customer requests. Unpublish to stop new requests; existing snapshots remain.</span></label>
            <button disabled={busy} className="min-h-11 rounded-xl bg-[#173c39] px-4 font-bold text-white">Save packaging</button>
        </form>
        <form onSubmit={event=>{event.preventDefault();void save(`${path}/branding`,branding);}} className="mt-6 space-y-4 rounded-xl border p-4"><h3 className="text-lg font-bold">Occasion page branding & promotion</h3><p className="text-sm">Branch-specific content shown above category browsing. Use genuine shop photos and accurate claims. Saving never changes existing quotes.</p><label className="block">Campaign headline<input required maxLength={100} value={branding.headline} onChange={event=>setBranding(current=>({...current,headline:event.target.value}))} className="mt-1 block w-full rounded-lg border p-2" /><span className="text-xs">A short invitation for weddings, family celebrations or corporate gifting.</span></label><label className="block">Campaign description<textarea required maxLength={500} value={branding.description} onChange={event=>setBranding(current=>({...current,description:event.target.value}))} className="mt-1 block w-full rounded-lg border p-2" /><span className="text-xs">Explain what the branch offers. Prices and promises must match the reviewed quote.</span></label><label className="block">Upload campaign photo<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={event=>{void upload(event.target.files,true);event.target.value="";}} className="mt-1 block w-full" /><span className="text-xs">One real JPG, PNG or WebP photo, up to 5 MB. Text remains readable beside the photo.</span></label>{branding.imageUrl&&<div><img src={branding.imageUrl} alt="Occasion campaign preview" className="h-40 w-full rounded-xl object-cover" /><button type="button" disabled={busy} onClick={()=>setBranding(current=>({...current,imageUrl:null}))} className="min-h-11 underline">Remove campaign photo</button></div>}<label className="block"><input type="checkbox" checked={branding.published} onChange={event=>setBranding(current=>({...current,published:event.target.checked}))} /> Publish occasion campaign<span className="block text-xs">Unpublished content is hidden from customers; the standard Gokul introduction remains.</span></label><button disabled={busy} className="min-h-11 rounded-xl bg-[#173c39] px-4 font-bold text-white">Save occasion campaign</button></form>
    </fieldset>}
    </div></section>;
}
