"use client";
import {useEffect,useState} from "react";
import {adminManagementApi} from "@/services/adminManagementApi";
import {useTranslation} from "@/lib/language";
type Fee={enabled:boolean;percentage:number;taxRate:number};
export default function OnlinePaymentFeeSettings({branchId,authorization}:{branchId:number;authorization:string}) {
 const t=useTranslation(),path=`/api/admin/branches/${branchId}/payment-fee`;
 const [fee,setFee]=useState<Fee>({enabled:false,percentage:0,taxRate:0}),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[reviewed,setReviewed]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 useEffect(()=>{const controller=new AbortController();adminManagementApi<Fee>(path,authorization,{signal:controller.signal}).then(value=>{setFee(value);setLoaded(true);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[path,authorization]);
 function change(next:Fee){setFee(next);setReviewed(false);setMessage("");}
 async function save(){if(busy||!loaded)return;setBusy(true);setError("");try{const saved=await adminManagementApi<Fee>(path,authorization,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({...fee,reviewed})});setFee(saved);setMessage("Saved. New online pickup and delivery quotes use this setting. Existing orders keep their agreed percentage.");}catch(e){setError(e instanceof Error?e.message:"Could not save fee.");}finally{setBusy(false);}}
 return <section aria-label={t("Online payment fee settings")} className="m-5 rounded-2xl border border-[#c4d4c9] bg-white p-5 text-[#143936]"><h3 className="text-lg font-bold">{t("Online payment fee")}</h3><p className="mt-3 text-sm">{t("A separate percentage charge on the payable amount after discounts, including convenience or delivery charges. The percentage includes fee tax; it is shown before payment. Off or 0% means no charge.")}</p><label className="mt-4 flex min-h-11 items-center gap-3 font-bold"><input type="checkbox" checked={fee.enabled} disabled={busy||!loaded} onChange={e=>change({...fee,enabled:e.target.checked})}/>{t("Enable online payment fee")}</label><div className="mt-3 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">{t("Payment fee (%)")}<input type="number" min="0" max="10" step="0.01" value={fee.percentage} disabled={busy||!loaded} onChange={e=>change({...fee,percentage:Number(e.target.value)})} className="mt-2 block min-h-11 w-full rounded-xl border p-3"/></label><label className="text-sm font-bold">{t("Payment fee tax rate (%)")}<input type="number" min="0" max="28" step="0.01" value={fee.taxRate} disabled={busy||!loaded} onChange={e=>change({...fee,taxRate:Number(e.target.value)})} className="mt-2 block min-h-11 w-full rounded-xl border p-3"/></label></div><p className="mt-3 text-sm">{t("Example: 2% on ₹1,000 adds ₹20. The global tax-off setting also turns off this fee’s tax component.")}</p><label className="mt-3 flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" checked={reviewed} disabled={busy||!loaded} onChange={e=>setReviewed(e.target.checked)}/>{t("Provider terms and fee tax treatment have been reviewed")}</label><button type="button" disabled={busy||!loaded||(fee.enabled&&fee.percentage>0&&!reviewed)} onClick={()=>void save()} className="mt-3 min-h-11 rounded-xl bg-[#143936] px-4 font-bold text-white disabled:opacity-50">{t(busy?"Saving…":"Save payment fee")}</button>{message&&<p role="status" className="mt-3 text-sm">{t(message)}</p>}{error&&<p role="alert" className="mt-3 text-sm text-red-800">{t(error)}</p>}</section>;
}
