"use client";
import {useCallback,useEffect,useRef,useState} from "react";
import {useAdminAuth} from "@/contexts/AdminAuthContext";
import {adminFetch} from "@/services/adminApi";
import {getActiveBranches} from "@/services/branchApi";
import {getPickupSlots} from "@/services/pickupApi";
import type {Branch} from "@/types/branch";
import type {PickupSlot} from "@/types/pickup";
import type {CorrectionSummary} from "@/components/order/OrderCancellation";
import AdminHelp from "./AdminHelp";
import {formatOrderCurrency as money,formatOrderTime} from "@/lib/orderTracking";
type Action={kind:"transfer"|"cancel-refund";body:{requestKey:string;reason:string;targetBranchId?:number;targetSlotId?:number;acceptedRefundAmount?:number;acceptedRetainedCharges?:number};review?:{branch:string;address:string;date:string;time:string}};
export default function OrderCorrectionPanel({orderNumber,branchId,pickupDate,onChanged}:{orderNumber:string;branchId:number;pickupDate:string|null;onChanged:()=>Promise<void>}){
 const {authorization,profile,hasPermission}=useAdminAuth();
 const [summary,setSummary]=useState<CorrectionSummary|null>(null),[branches,setBranches]=useState<Branch[]>([]),[slots,setSlots]=useState<PickupSlot[]>([]),[target,setTarget]=useState(""),[slot,setSlot]=useState(""),[reason,setReason]=useState(""),[date,setDate]=useState(pickupDate??""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[action,setAction]=useState<Action|null>(null);
 const dialog=useRef<HTMLDialogElement>(null),locked=useRef(false),key=`gokul-staff-correction:${orderNumber}`,path=`/api/admin/orders/${encodeURIComponent(orderNumber)}`;
 const read=useCallback(async(signal?:AbortSignal)=>{if(!authorization)return;const result=await adminFetch(`${path}/correction`,authorization,{signal});if(!result.ok)throw new Error("Order correction details are unavailable. Check your branch permissions.");const value=await result.json() as CorrectionSummary;if(!signal?.aborted)setSummary(value);},[authorization,path]);
 useEffect(()=>{const controller=new AbortController();void Promise.resolve().then(()=>read(controller.signal)).catch(e=>{if(!controller.signal.aborted)setError(e.message);});void getActiveBranches(controller.signal).then(values=>{if(!controller.signal.aborted)setBranches(values.filter(b=>b.id!==branchId&&b.operational!==false&&(profile?.roleName==="OWNER_ADMIN"||profile?.branchIds.includes(b.id))));}).catch(()=>{});return()=>controller.abort();},[read,branchId,profile]);
 useEffect(()=>{if(!target||!date)return;const controller=new AbortController();void getPickupSlots(Number(target),date,controller.signal).then(values=>{if(!controller.signal.aborted)setSlots(values.filter(value=>value.active));}).catch(()=>{if(!controller.signal.aborted)setError("Could not load receiving pickup times.");});return()=>controller.abort();},[target,date]);
 useEffect(()=>{if(action)dialog.current?.showModal();else dialog.current?.close();},[action]);
 async function review(kind:Action["kind"]){setError("");setBusy(true);try{const saved=sessionStorage.getItem(key);if(saved){setAction(JSON.parse(saved) as Action);return;}const result=await adminFetch(`${path}/correction`,authorization!);if(!result.ok)throw new Error("Refresh this order before changing it.");const current=await result.json() as CorrectionSummary;setSummary(current);setAction({kind,review:kind==="transfer"?{branch:branches.find(b=>b.id===Number(target))?.name??target,address:branches.find(b=>b.id===Number(target))?.address??"",date,time:slots.filter(s=>s.id===Number(slot)).map(s=>`${formatOrderTime(s.startTime)}–${formatOrderTime(s.endTime)}`).join("")}:undefined,body:kind==="transfer"?{requestKey:crypto.randomUUID(),targetBranchId:Number(target),targetSlotId:Number(slot),reason:reason.trim()}:{requestKey:crypto.randomUUID(),reason:reason.trim(),acceptedRefundAmount:current.refundAmount,acceptedRetainedCharges:current.retainedCharges}});}catch(e){setError(e instanceof Error?e.message:"Could not review this action.");}finally{setBusy(false);}}
 async function confirm(){if(!action||!authorization||locked.current)return;locked.current=true;setBusy(true);setError("");try{sessionStorage.setItem(key,JSON.stringify(action));const result=await adminFetch(`${path}/${action.kind}`,authorization,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(action.body),signal:AbortSignal.timeout(20000)});if(!result.ok){if([400,409].includes(result.status))sessionStorage.removeItem(key);const response=await result.json();throw new Error(response.message??"The action could not be confirmed. Retry the same recorded request.");}setSummary(await result.json());sessionStorage.removeItem(key);setAction(null);await onChanged();}catch(e){setError(e instanceof Error?e.message:"The result is unconfirmed. Retry to recover this exact action.");}finally{setBusy(false);locked.current=false;}}
 if(!hasPermission("ORDER_CANCEL"))return null;
 const input="mt-2 block min-h-11 w-full rounded-xl border p-3";
 return <section className="mt-6 rounded-2xl border border-[#d8e3dc] bg-[#fffaf2] p-4"><div className="flex items-center gap-2"><h2 className="font-bold">Wrong branch or incorrect order?</h2><AdminHelp title="Order correction" description="Transfer a confirmed pickup order before preparation only when every item price, tax and branch charge matches. Server validation reserves the receiving stock and pickup capacity atomically." guidance="Choose a branch you can manage, an available IST pickup time and an audit reason. If prices differ, cancel with a food refund and help the customer place a new order. Additional charges are retained. Staff cancellation is not limited to the customer's 10-minute window; collected or dispatched orders cannot use it."/></div>
 {summary&&<p className="mt-2 text-sm">Food refund {money(summary.refundAmount)} · retained charges {money(summary.retainedCharges)}. {summary.refundStatus!=="NOT_REQUESTED"?summary.refundStatus.replaceAll("_"," "):"Provider confirmation is required before a refund is complete."}</p>}
 <label className="mt-3 block text-sm">Audit reason<textarea className={input} maxLength={500} value={reason} disabled={busy} onChange={e=>setReason(e.target.value)}/></label>
 {summary?.canTransfer&&<div className="mt-3 grid gap-3 sm:grid-cols-3"><label className="text-sm">Receiving branch<select className={input} value={target} disabled={busy} onChange={e=>{setTarget(e.target.value);setSlot("");setSlots([]);}}><option value="">Choose branch</option>{branches.map(b=><option key={b.id} value={b.id}>{b.name} · {b.address??b.city}</option>)}</select></label><label className="text-sm">Pickup date (IST)<input className={input} type="date" value={date} disabled={busy} onChange={e=>{setDate(e.target.value);setSlot("");setSlots([]);}}/></label><label className="text-sm">Receiving time (IST)<select className={input} value={slot} disabled={busy} onChange={e=>setSlot(e.target.value)}><option value="">Choose pickup time</option>{slots.map(s=><option key={s.id} value={s.id}>{formatOrderTime(s.startTime)}–{formatOrderTime(s.endTime)}</option>)}</select></label></div>}
 <div className="mt-4 flex flex-wrap gap-3">{summary?.canTransfer&&<button type="button" className="min-h-11 rounded-xl bg-[#143936] px-4 font-bold text-white disabled:opacity-50" disabled={busy||!target||!slot||!reason.trim()} onClick={()=>void review("transfer")}>Review transfer</button>}{hasPermission("REFUND_CREATE")&&summary?.canCancel&&<button type="button" className="min-h-11 rounded-xl border border-[#a94d39] px-4 font-bold text-[#a94d39] disabled:opacity-50" disabled={busy||!reason.trim()} onClick={()=>void review("cancel-refund")}>Review cancellation & refund</button>}<button type="button" disabled={busy} className="min-h-11 rounded-xl border px-4" onClick={()=>void read().catch(e=>setError(e.message))}>Refresh correction status</button><button type="button" disabled={busy} className="min-h-11 rounded-xl border px-4" onClick={()=>{const value=sessionStorage.getItem(key);if(value)setAction(JSON.parse(value));else setError("No interrupted correction to retry.");}}>Recover interrupted action</button></div>
 {summary?.refundReviewRequired&&<p role="status" className="mt-3 rounded-xl border border-amber-300 bg-amber-50 p-3 text-sm">Refund confirmation needs staff review. Automatic status checks continue. Verify the transaction in PhonePe before initiating any manual refund.</p>}
 {error&&<p role="alert" className="mt-3 text-sm">{error}</p>}
 {action&&<dialog ref={dialog} aria-labelledby="staff-correction-title" className="m-auto max-h-[calc(100dvh-2rem)] w-[calc(100vw-2rem)] max-w-md overflow-auto rounded-2xl border bg-[#fffaf2] p-5 backdrop:bg-black/60" onCancel={e=>{if(busy)e.preventDefault();else setAction(null);}}><h2 id="staff-correction-title" className="text-lg font-bold">{action.kind==="transfer"?"Confirm pickup branch transfer?":"Cancel and request food refund?"}</h2><p className="mt-3 text-sm">{action.kind==="transfer"?"The backend checks matching prices, charges, service eligibility, stock and pickup capacity. Order number and pickup code remain unchanged.":`Food refund ${money((action.body as {acceptedRefundAmount:number}).acceptedRefundAmount)}. Additional charges ${money((action.body as {acceptedRetainedCharges:number}).acceptedRetainedCharges)} are retained. This requests a refund; it does not confirm bank credit.`}</p>{action.kind==="transfer"&&<div className="mt-3 rounded-xl border p-3 text-sm"><strong>Collect at {action.review?.branch??`Branch ${action.body.targetBranchId}`}</strong><p>{action.review?.address}</p><p>{action.review?`${action.review.date} · ${action.review.time} IST`:`Pickup slot ${action.body.targetSlotId} · server-validated IST time`}</p></div>}<p className="mt-3 text-sm">Audit reason: {action.body.reason}</p><div className="mt-4 flex flex-wrap gap-3"><button type="button" autoFocus disabled={busy} className="min-h-11 rounded-xl border px-4" onClick={()=>setAction(null)}>Keep order / Close</button><button type="button" disabled={busy} className="min-h-11 rounded-xl bg-[#143936] px-4 font-bold text-white" onClick={()=>void confirm()}>{busy?"Checking and saving…":"Confirm action"}</button></div>{error&&<p role="alert" className="mt-3 text-sm">{error}</p>}</dialog>}
 </section>;
}
