"use client";
import {T} from "@/lib/language";

import {useEffect,useState} from "react";
import {adminManagementApi} from "@/services/adminManagementApi";
type Fee={amount:number;taxRate:number};
export default function PickupFeeSettings({branchId,authorization}:{branchId:number;authorization:string}) {
 const path=`/api/admin/branches/${branchId}/pickup-fee`;
 const [amount,setAmount]=useState("0"),[taxRate,setTaxRate]=useState("0"),[reviewed,setReviewed]=useState(false),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 useEffect(()=>{const controller=new AbortController();adminManagementApi<Fee>(path,authorization,{signal:controller.signal}).then(f=>{setAmount(String(f.amount));setTaxRate(String(f.taxRate));setLoaded(true);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[path,authorization]);
 async function save(){if(busy||!loaded)return;setBusy(true);setError("");setMessage("");try{await adminManagementApi<Fee>(path,authorization,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({amount:Number(amount),taxRate:Number(taxRate),taxReviewed:reviewed})});setMessage("Saved. New normal-pickup quotes use this fee; paid orders stay unchanged.");}catch(e){setError(e instanceof Error?e.message:"Could not save fee.");}finally{setBusy(false);}}
 return <section aria-label="Pickup convenience fee settings" className="m-5 rounded-2xl border border-[#eadfd6] bg-white p-5"><p className="text-xs font-bold uppercase tracking-widest text-[#756763]">Online pickup pricing</p><h3 className="mt-1 text-lg font-bold"><T text="Convenience fee" /></h3><p className="mt-2 max-w-2xl text-sm text-[#756763]">A separate, transparent charge for normal online pickup. ₹0 turns it off. The amount includes fee tax and is never discounted or counted toward rebate thresholds.</p>
 <div className="mt-4 flex gap-2">{[0,5,10].map(value=><button key={value} type="button" disabled={busy||!loaded} onClick={()=>{setAmount(String(value));setReviewed(false);}} className={`min-h-11 rounded-xl border px-5 ${Number(amount)===value?"bg-[#173c39] text-white":"bg-white"}`}>₹{value}{value===0?" · Off":""}</button>)}</div>
 <div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-semibold">Fee including tax (₹)<input aria-label="Pickup convenience fee" type="number" min="0" max="100" step="0.01" value={amount} onChange={e=>{setAmount(e.target.value);setReviewed(false);}} className="mt-2 min-h-11 w-full rounded-xl border p-3"/><span className="mt-1 block text-xs font-normal text-[#756763]">Enter ₹0–₹100. Review customer savings and production costs before changing charges.</span></label>
 <label className="text-sm font-semibold">Combined fee tax rate (%)<input aria-label="Convenience fee tax rate" type="number" min="0" max="28" step="0.01" value={taxRate} onChange={e=>{setTaxRate(e.target.value);setReviewed(false);}} className="mt-2 min-h-11 w-full rounded-xl border p-3"/><span className="mt-1 block text-xs font-normal text-[#756763]">Finance-reviewed CGST + SGST for this charge. Use 0 only when appropriate; the app does not choose a tax classification.</span></label></div>
 <label className="mt-4 flex min-h-11 items-center gap-3 text-sm"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>Fee tax treatment has been reviewed</label><button type="button" disabled={busy||!loaded||!amount||!taxRate||(Number(amount)>0&&!reviewed)} onClick={()=>void save()} className="mt-2 min-h-11 rounded-xl bg-[#173c39] px-5 font-bold text-white disabled:opacity-50">{busy?"Saving…":"Save fee"}</button>{message&&<p role="status" className="mt-3 text-sm text-green-800">{message}</p>}{error&&<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}</section>;
}
