"use client";
import {useEffect,useState} from "react";
import {adminManagementApi} from "@/services/adminManagementApi";
import {T,useTranslation} from "@/lib/language";
export default function TaxCollectionControl({authorization}:{authorization:string}){
 const translate=useTranslation(),[enabled,setEnabled]=useState<boolean|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{const controller=new AbortController();adminManagementApi<{enabled:boolean}>('/api/admin/tax-collection',authorization,{signal:controller.signal}).then(s=>setEnabled(s.enabled)).catch(e=>{if(!controller.signal.aborted)setMessage(e.message);});return()=>controller.abort();},[authorization]);
 async function change(){if(enabled===null||busy)return;setBusy(true);setMessage('');try{const setting=await adminManagementApi<{enabled:boolean}>('/api/admin/tax-collection',authorization,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:!enabled})});setEnabled(setting.enabled);setMessage('Saved. New quotes use this setting. Existing orders keep their original amounts.');}catch(e){setMessage(e instanceof Error?e.message:'Could not save tax setting.');}finally{setBusy(false);}}
 return <section className="rounded-2xl border border-[#c4d4c9] bg-[#fffaf2] p-5"><h2 className="text-xl font-bold"><T text="Tax collection"/></h2><p className="my-3 text-sm"><T text="Apply configured product tax to new pickup and delivery orders. Turning this off keeps the tax rates saved for later."/></p><button type="button" role="switch" aria-checked={enabled===true} disabled={enabled===null||busy} onClick={()=>void change()} className="min-h-12 rounded-xl bg-[#143936] px-5 font-bold text-white disabled:opacity-50">{translate(busy?'Saving…':enabled===null?'Loading…':enabled?'Tax ON · tap to turn off':'Tax OFF · tap to turn on')}</button><p className="mt-3 text-xs"><T text="Existing paid orders and accepted occasion quotations are unchanged."/></p>{message&&<p role="status" className="mt-3 text-sm">{translate(message)}</p>}</section>;
}
