"use client";
import {useEffect, useRef, useState} from "react";
import Link from "next/link";
import WorkspaceDialog from "./WorkspaceDialog";
import {InventoryInfo} from "./inventory/InventoryHelp";
import {workspaceRequest, jsonRequest, type WorkspaceItem} from "@/services/menuWorkspaceApi";
import {readWorkspaceDraft, writeWorkspaceDraft, clearWorkspaceDraft} from "@/lib/menuWorkspaceDraft";
import styles from "./MenuWorkspace.module.css";

type Row = {item: WorkspaceItem; quantity: string; ready: string; status?: "saved" | "failed"; error?: string};
export default function WorkspaceRoutine({items, branch, date, draftKey, onClose, onSaved}: {
  items: WorkspaceItem[]; branch: number; date: string; draftKey: string;
  onClose: () => void; onSaved: (notice?: string) => void;
}) {
  const [initial] = useState(() => readWorkspaceDraft<{method: string; repeat: boolean; applyMethod?: boolean; reason: string; rows: Row[]}>(draftKey));
  const [method, setMethod] = useState(initial?.method ?? "DAILY_PRODUCTION");
  const [repeat, setRepeat] = useState(initial?.repeat ?? false);
  const [applyMethod, setApplyMethod] = useState(initial?.applyMethod ?? false);
  const [reason, setReason] = useState(initial?.reason ?? "Routine inventory setup");
  const [rows, setRows] = useState<Row[]>(initial?.rows ?? items.map(item => ({item, quantity: "", ready: ""})));
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const [defaults, setDefaults] = useState({UNIT: "", WEIGHT: ""});
  const [readyDefaults, setReadyDefaults] = useState({UNIT: "", WEIGHT: ""});
  const lock = useRef(false);
  useEffect(() => writeWorkspaceDraft(draftKey, {method, repeat, applyMethod, reason, rows}), [draftKey, method, repeat, applyMethod, reason, rows]);
  const prepared = method === "READY_STOCK";
  function close() {clearWorkspaceDraft(draftKey); onClose();}
  function update(index: number, key: "quantity" | "ready", value: string) {
    setRows(current => current.map((row, i) => i === index ? {...row, [key]: value, error: undefined} : row));
  }
  async function save() {
    if (lock.current) return;
    const pending = rows.filter(row => row.status !== "saved");
    if (!reason.trim() || pending.some(row => !Number.isFinite(Number(row.quantity)) || Number(row.quantity) <= 0 ||
      (row.item.saleMode === "UNIT" && !Number.isInteger(Number(row.quantity))) ||
      (prepared && (!Number.isFinite(Number(row.ready)) || Number(row.ready) <= 0 || Number(row.ready) > Number(row.quantity) ||
        (row.item.saleMode === "UNIT" && !Number.isInteger(Number(row.ready))))))) {
      setError("Enter a positive quantity for every item and a reason. Pieces must be whole numbers. Prepared stock must be positive and no larger than its online allocation."); return;
    }
    lock.current = true; setBusy(true); setError("");
    const next = rows.map(row => ({...row}));
    let cursor = 0;
    await Promise.all(Array.from({length: Math.min(4, pending.length)}, async () => {
      while (cursor < next.length) {
        const index = cursor++;
        const row = next[index];
        if (row.status === "saved") continue;
        const factor = row.item.saleMode === "WEIGHT" ? 1000 : 1;
        try {
          await workspaceRequest(branch, `/${row.item.productId}/routine/${date}`, jsonRequest("PUT", {
            branchVersion: row.item.branchVersion, policyVersion: row.item.policyVersion,
            allocationVersion: row.item.allocationVersion, method,
            quantity: Math.round(Number(row.quantity) * factor * 1000) / 1000,
            readyQuantity: prepared ? Math.round(Number(row.ready) * factor * 1000) / 1000 : null,
            repeatDaily: repeat, applyMethod, reason,
          }));
          next[index] = {...row, status: "saved", error: undefined};
        } catch (e) {next[index] = {...row, status: "failed", error: e instanceof Error ? e.message : "Save failed. Retry."};}
        setRows([...next]);
      }
    }));
    setBusy(false); lock.current = false;
    const failed = next.filter(row => row.status === "failed").length;
    if (!failed) {clearWorkspaceDraft(draftKey); onSaved(`${next.length} items saved for ${date}. ${repeat ? "Daily allocation rules saved; future allocations are generated by the scheduled job. Prepared stock still needs physical confirmation each day." : "Saved for this date only."}`);}
    else setError(`${next.length - failed} saved; ${failed} need attention. Retry saves only the failed items. A conflict requires closing and reloading fresh item versions.`);
  }
  return <WorkspaceDialog title="Quick inventory setup" scope={`Selected branch · ${date} IST · ${rows.length} items`} busy={busy} onClose={close}
    footer={<><button disabled={busy} onClick={close}>Close</button><button className={styles.primary} disabled={busy || rows.every(row => row.status === "saved")} onClick={() => void save()}>{busy ? "Saving items…" : rows.some(row => row.status === "saved") ? "Retry failed items" : "Reviewed · save selected items"}</button></>}>
    <p className={styles.notice}>Set up many items in one place. Saved items are skipped on retry. Quantities and original versions are restored after refresh. Existing custom policies or automation rules are preserved.</p>
    <fieldset disabled={busy || rows.some(row => row.status === "saved")}>
      <label>Selling method <InventoryInfo helpKey="controlMode" /><select value={method} onChange={e => setMethod(e.target.value)}>
        <option value="DAILY_PRODUCTION">Made to order · daily capacity</option><option value="READY_STOCK">Prepared stock · confirm ready quantity</option>
      </select></label>
      <p className={styles.muted}>{prepared ? "Customers can order only physically prepared stock. Enter what is ready, not what you intend to make." : "Use only for items the branch can reliably prepare for pickup. No separate Ready step is required for this policy; service hours and pickup validation still apply."}</p>
      <label><span><input type="checkbox" checked={applyMethod} onChange={e => setApplyMethod(e.target.checked)} /> Apply this selling method to existing policies too</span></label>
      <p className={styles.muted}>Leave off to keep current policies. When enabled, the chosen method and online ordering are applied to all selected items; safety buffers, daily ceilings, lead times and booking horizons are retained. Saving opens the selected items for new purchases subject to stock, service hours and pickup validation.</p>
      <label><span><input type="checkbox" checked={repeat} onChange={e => setRepeat(e.target.checked)} /> Repeat this allocation daily <InventoryInfo helpKey="guaranteed" /></span></label>
      <p className={styles.muted}>Optional: create an automatic rule for every day within the booking horizon (up to 14 days). Future dates are generated by the server schedule, not immediately by this save. Ready stock is never marked physically ready by automation. The standard server schedule runs at 01:15 IST; a sleeping backend may miss that run. Use Generate allocations on the automation page if dates are needed immediately. Existing schedules must be edited in <Link href="/admin/inventory/automation">Inventory automation</Link>.</p>
      <label>Reason <InventoryInfo helpKey="adjustmentReason" /><textarea maxLength={500} value={reason} onChange={e => setReason(e.target.value)} /></label>
    </fieldset>
    <fieldset disabled={busy}>
      <details><summary>Fill the same allocation for multiple items</summary><p>Weight and piece quantities are separate. Fill only amounts you can supply; review every row before saving.</p>
        {(["WEIGHT", "UNIT"] as const).map(unit => <label key={unit}>Default {unit === "WEIGHT" ? "kg" : "pieces"}<input type="number" min="0" step={unit === "WEIGHT" ? ".001" : "1"} value={defaults[unit]} onChange={e => setDefaults(current => ({...current, [unit]: e.target.value}))} /><button type="button" onClick={() => setRows(current => current.map(row => row.item.saleMode === unit && row.status !== "saved" ? {...row, quantity: defaults[unit]} : row))}>Fill allocation</button></label>)}
        {prepared && <><p>For verified stock counts only: fill a prepared quantity for this unit group, then review each item. This records actual prepared stock, not a production plan.</p>
          {(["WEIGHT", "UNIT"] as const).map(unit => <label key={`ready-${unit}`}>Verified prepared {unit === "WEIGHT" ? "kg" : "pieces"}<input type="number" min="0" step={unit === "WEIGHT" ? ".001" : "1"} value={readyDefaults[unit]} onChange={e => setReadyDefaults(current => ({...current, [unit]: e.target.value}))} /><button type="button" onClick={() => setRows(current => current.map(row => row.item.saleMode === unit && row.status !== "saved" ? {...row, ready: readyDefaults[unit]} : row))}>Fill verified prepared quantity</button></label>)}
        </>}
      </details>
      {rows.map((row, index) => <section className={styles.product} key={row.item.productId}>
        <strong>{row.item.name}</strong><span className={styles.muted}> · {row.item.code} · {row.item.saleMode === "WEIGHT" ? "kg" : "pieces"}</span>
        <fieldset disabled={row.status === "saved"}>
          <label>Online allocation <InventoryInfo helpKey="approved" /><input type="number" min=".001" step={row.item.saleMode === "WEIGHT" ? ".001" : "1"} aria-label={`${row.item.name} online allocation (${row.item.saleMode === "WEIGHT" ? "kg" : "pieces"})`} value={row.quantity} onChange={e => update(index, "quantity", e.target.value)} /></label>
          {prepared && <label>Physically prepared now <InventoryInfo helpKey="ready" /><input type="number" min=".001" step={row.item.saleMode === "WEIGHT" ? ".001" : "1"} aria-label={`${row.item.name} physically prepared (${row.item.saleMode === "WEIGHT" ? "kg" : "pieces"})`} value={row.ready} onChange={e => update(index, "ready", e.target.value)} /></label>}
        </fieldset>
        {row.status === "saved" && <p role="status">Saved</p>}{row.error && <p role="alert" className={styles.error}>{row.error}</p>}
      </section>)}
    </fieldset>
    {error && <p role="alert" className={styles.error}>{error}</p>}
  </WorkspaceDialog>;
}
