"use client";
import "../checkout/reward-controls.css";
import {useEffect,useState} from 'react';
import {getRewards,type RewardWallet} from '@/services/loyaltyApi';
import {formatBusinessTimestamp} from '@/lib/businessTime';
import {T} from '@/lib/language';
export default function CustomerRewards(){
 const [wallet,setWallet]=useState<RewardWallet|null>(null),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{const c=new AbortController();void getRewards(AbortSignal.any([c.signal,AbortSignal.timeout(15000)])).then(value=>{if(!c.signal.aborted){setWallet(value);setError('');}}).catch(()=>{if(!c.signal.aborted)setError('Your rewards could not be loaded. Try again.');});return()=>c.abort();},[revision]);
 return <section className="checkout-rewards customer-rewards" aria-label="Rewards"><div className="checkout-savings-heading"><h2><T text="Gokul rewards" /></h2><button type="button" onClick={()=>setRevision(v=>v+1)}><T text="Refresh" /></button></div>{error?<p role="alert">{error}</p>:wallet?<><p className="text-2xl font-bold mt-3">{wallet.balance} <T text="earned coins" /></p>{wallet.debt>0&&<p>{wallet.debt} <T text="coins will be offset against future earnings following refunds." /></p>}<p>{wallet.pendingCoins} <T text="coins pending order completion" /></p>{wallet.nextExpiry&&<p><T text="Next expiry" />: {formatBusinessTimestamp(wallet.nextExpiry,{day:'numeric',month:'short',year:'numeric'})} IST</p>}<div className="checkout-reward-choices">{wallet.rewards.map(reward=><div key={reward.code} className="rounded-xl border p-3"><strong>{reward.name}</strong><p>{reward.coins} <T text="coins" /> · <T text="Minimum" /> ₹{Number(reward.minimumSubtotal).toFixed(0)}</p><small>{Math.max(0,reward.coins-wallet.balance)} <T text="more coins to reach this reward" /></small></div>)}</div><details><summary><T text="Coin history" /></summary>{wallet.history.length?wallet.history.map(entry=><article key={entry.id} className="border-b py-3"><strong>{entry.coins>0?'+':''}{entry.coins} · {entry.kind}</strong><p>{entry.reason}</p><small>{formatBusinessTimestamp(entry.createdAt,{day:'numeric',month:'short',year:'numeric',hour:'numeric',minute:'2-digit'})} IST{entry.orderNumber&&<> · {entry.customerOrderNumber != null ? `#${entry.customerOrderNumber}` : entry.orderNumber}</>}</small></article>):<p><T text="Complete an eligible paid order to earn your first coins." /></p>}</details><details className="mt-3"><summary><T text="Rewards terms" /></summary><p>{wallet.terms}</p></details></>:<p role="status"><T text="Loading your earned rewards…" /></p>}</section>;
}
